package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"hmans.de/chatto/internal/core"
	"hmans.de/chatto/internal/graph/auth"
	"hmans.de/chatto/internal/graph/model"
	corev1 "hmans.de/chatto/internal/pb/chatto/core/v1"
)

// Roles is the resolver for the roles field.
func (r *instanceResolver) Roles(ctx context.Context, obj *model.Instance) ([]*core.RoleWithPermissions, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return nil, fmt.Errorf("authentication required")
	}
	spaceID, err := r.serverSpaceID(ctx)
	if err != nil || spaceID == "" {
		return nil, err
	}

	isMember, err := r.core.SpaceMembershipExists(ctx, user.Id, spaceID)
	if err != nil {
		return nil, err
	}
	if !isMember {
		return nil, core.ErrNotSpaceMember
	}

	roles, err := r.core.ListRoles(ctx, spaceID)
	if err != nil {
		return nil, err
	}

	return r.spaceRolesToGraphQL(ctx, spaceID, roles), nil
}

// Role is the resolver for the role field.
func (r *instanceResolver) Role(ctx context.Context, obj *model.Instance, name string) (*core.RoleWithPermissions, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return nil, fmt.Errorf("authentication required")
	}
	spaceID, err := r.serverSpaceID(ctx)
	if err != nil || spaceID == "" {
		return nil, err
	}

	isMember, err := r.core.SpaceMembershipExists(ctx, user.Id, spaceID)
	if err != nil {
		return nil, err
	}
	if !isMember {
		return nil, core.ErrNotSpaceMember
	}

	role, err := r.core.GetRole(ctx, spaceID, name)
	if err != nil {
		if err == core.ErrRoleNotFound {
			return nil, nil
		}
		return nil, err
	}

	return r.spaceRoleToGraphQL(ctx, spaceID, role), nil
}

// AvailablePermissions is the resolver for the availablePermissions field.
func (r *instanceResolver) AvailablePermissions(ctx context.Context, obj *model.Instance) ([]string, error) {
	perms := core.PermissionsForScope(core.ScopeSpace)
	result := make([]string, len(perms))
	for i, p := range perms {
		result[i] = string(p.Permission)
	}
	return result, nil
}

// ViewerPermissions is the resolver for the viewerPermissions field.
func (r *instanceResolver) ViewerPermissions(ctx context.Context, obj *model.Instance) ([]string, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return []string{}, nil
	}
	spaceID, err := r.serverSpaceID(ctx)
	if err != nil || spaceID == "" {
		return []string{}, err
	}

	perms, err := r.core.GetUserEffectiveSpacePermissions(ctx, spaceID, user.Id)
	if err != nil {
		return nil, err
	}

	result := make([]string, len(perms))
	for i, p := range perms {
		result[i] = string(p)
	}
	return result, nil
}

// ViewerCanManageRoles is the resolver for the viewerCanManageRoles field.
func (r *instanceResolver) ViewerCanManageRoles(ctx context.Context, obj *model.Instance) (bool, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return false, nil
	}
	spaceID, err := r.serverSpaceID(ctx)
	if err != nil || spaceID == "" {
		return false, err
	}
	return r.core.CanSpaceRolesManage(ctx, user.Id, spaceID)
}

// ViewerCanAssignRoles is the resolver for the viewerCanAssignRoles field.
func (r *instanceResolver) ViewerCanAssignRoles(ctx context.Context, obj *model.Instance) (bool, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return false, nil
	}
	spaceID, err := r.serverSpaceID(ctx)
	if err != nil || spaceID == "" {
		return false, err
	}
	return r.core.CanSpaceRolesAssign(ctx, user.Id, spaceID)
}

// ViewerCanManageUser is the resolver for the viewerCanManageUser field.
func (r *instanceResolver) ViewerCanManageUser(ctx context.Context, obj *model.Instance, userID string) (bool, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return false, nil
	}
	if user.Id == userID {
		return false, nil
	}
	spaceID, err := r.serverSpaceID(ctx)
	if err != nil || spaceID == "" {
		return false, err
	}
	return r.core.CanManageSpaceUser(ctx, spaceID, user.Id, userID)
}

// RoleUsers is the resolver for the roleUsers field.
func (r *instanceResolver) RoleUsers(ctx context.Context, obj *model.Instance, roleName string) ([]*corev1.User, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return nil, fmt.Errorf("authentication required")
	}
	spaceID, err := r.serverSpaceID(ctx)
	if err != nil || spaceID == "" {
		return nil, err
	}

	isMember, err := r.core.SpaceMembershipExists(ctx, user.Id, spaceID)
	if err != nil {
		return nil, err
	}
	if !isMember {
		return nil, core.ErrNotSpaceMember
	}

	userIDs, err := r.core.GetRoleUsers(ctx, spaceID, roleName)
	if err != nil {
		return nil, fmt.Errorf("failed to get role users: %w", err)
	}

	users := make([]*corev1.User, 0, len(userIDs))
	for _, uID := range userIDs {
		u, err := r.core.GetUser(ctx, uID)
		if err != nil {
			continue
		}
		users = append(users, u)
	}

	return users, nil
}

// UserRoleBasedPermissions is the resolver for the userRoleBasedPermissions field.
func (r *instanceResolver) UserRoleBasedPermissions(ctx context.Context, obj *model.Instance, userID string) ([]string, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return nil, fmt.Errorf("authentication required")
	}
	spaceID, err := r.serverSpaceID(ctx)
	if err != nil || spaceID == "" {
		return nil, err
	}

	isMember, err := r.core.SpaceMembershipExists(ctx, user.Id, spaceID)
	if err != nil {
		return nil, err
	}
	if !isMember {
		return nil, core.ErrNotSpaceMember
	}

	allPerms := core.PermissionsForScope(core.ScopeSpace)
	var rolePerms []string

	for _, permDef := range allPerms {
		has, err := r.core.HasSpaceUserPermissionViaRoles(ctx, spaceID, userID, core.Permission(permDef.Permission))
		if err != nil {
			return nil, err
		}
		if has {
			rolePerms = append(rolePerms, string(permDef.Permission))
		}
	}

	return rolePerms, nil
}

// UserRoleBasedDenials is the resolver for the userRoleBasedDenials field.
func (r *instanceResolver) UserRoleBasedDenials(ctx context.Context, obj *model.Instance, userID string) ([]string, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return nil, fmt.Errorf("authentication required")
	}
	spaceID, err := r.serverSpaceID(ctx)
	if err != nil || spaceID == "" {
		return nil, err
	}

	isMember, err := r.core.SpaceMembershipExists(ctx, user.Id, spaceID)
	if err != nil {
		return nil, err
	}
	if !isMember {
		return nil, core.ErrNotSpaceMember
	}

	allPerms := core.PermissionsForScope(core.ScopeSpace)
	var roleDenials []string

	for _, permDef := range allPerms {
		denied, err := r.core.HasSpaceUserPermissionDeniedViaRoles(ctx, spaceID, userID, core.Permission(permDef.Permission))
		if err != nil {
			return nil, err
		}
		if denied {
			roleDenials = append(roleDenials, string(permDef.Permission))
		}
	}

	return roleDenials, nil
}

// CreateSpaceRole is the resolver for the createSpaceRole field.
func (r *mutationResolver) CreateSpaceRole(ctx context.Context, input model.CreateSpaceRoleInput) (*core.RoleWithPermissions, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	spaceID, err := r.requireServerSpaceID(ctx)
	if err != nil {
		return nil, err
	}

	role, err := r.core.CreateRole(ctx, user.Id, spaceID, input.Name, input.DisplayName, input.Description)
	if err != nil {
		return nil, err
	}

	return r.spaceRoleToGraphQL(ctx, spaceID, role), nil
}

// UpdateSpaceRole is the resolver for the updateSpaceRole field.
func (r *mutationResolver) UpdateSpaceRole(ctx context.Context, input model.UpdateSpaceRoleInput) (*core.RoleWithPermissions, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	spaceID, err := r.requireServerSpaceID(ctx)
	if err != nil {
		return nil, err
	}

	role, err := r.core.UpdateRole(ctx, user.Id, spaceID, input.Name, input.DisplayName, input.Description)
	if err != nil {
		return nil, err
	}

	return r.spaceRoleToGraphQL(ctx, spaceID, role), nil
}

// DeleteSpaceRole is the resolver for the deleteSpaceRole field.
func (r *mutationResolver) DeleteSpaceRole(ctx context.Context, input model.DeleteSpaceRoleInput) (bool, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	spaceID, err := r.requireServerSpaceID(ctx)
	if err != nil {
		return false, err
	}

	if err := r.core.DeleteRole(ctx, user.Id, spaceID, input.Name); err != nil {
		return false, err
	}
	return true, nil
}

// GrantSpacePermission is the resolver for the grantSpacePermission field.
func (r *mutationResolver) GrantSpacePermission(ctx context.Context, input model.GrantSpacePermissionInput) (bool, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	spaceID, err := r.requireServerSpaceID(ctx)
	if err != nil {
		return false, err
	}

	if err := r.core.GrantSpacePermission(ctx, user.Id, spaceID, input.Role, core.Permission(input.Permission)); err != nil {
		return false, err
	}
	return true, nil
}

// RevokeSpacePermission is the resolver for the revokeSpacePermission field.
func (r *mutationResolver) RevokeSpacePermission(ctx context.Context, input model.RevokeSpacePermissionInput) (bool, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	spaceID, err := r.requireServerSpaceID(ctx)
	if err != nil {
		return false, err
	}

	if err := r.core.RevokeSpacePermission(ctx, user.Id, spaceID, input.Role, core.Permission(input.Permission)); err != nil {
		return false, err
	}
	return true, nil
}

// DenySpacePermission is the resolver for the denySpacePermission field.
func (r *mutationResolver) DenySpacePermission(ctx context.Context, input model.DenySpacePermissionInput) (bool, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	spaceID, err := r.requireServerSpaceID(ctx)
	if err != nil {
		return false, err
	}

	if err := r.core.DenySpacePermission(ctx, user.Id, spaceID, input.Role, core.Permission(input.Permission)); err != nil {
		return false, err
	}
	return true, nil
}

// ClearSpacePermissionState is the resolver for the clearSpacePermissionState field.
func (r *mutationResolver) ClearSpacePermissionState(ctx context.Context, input model.ClearSpacePermissionStateInput) (bool, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	spaceID, err := r.requireServerSpaceID(ctx)
	if err != nil {
		return false, err
	}

	if err := r.core.ClearSpacePermissionState(ctx, user.Id, spaceID, input.Role, core.Permission(input.Permission)); err != nil {
		return false, err
	}
	return true, nil
}

// AssignSpaceRole is the resolver for the assignSpaceRole field.
func (r *mutationResolver) AssignSpaceRole(ctx context.Context, input model.AssignSpaceRoleInput) (bool, error) {
	caller, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	spaceID, err := r.requireServerSpaceID(ctx)
	if err != nil {
		return false, err
	}

	if err := r.core.AssignRole(ctx, caller.Id, spaceID, input.UserID, input.RoleName); err != nil {
		return false, err
	}
	return true, nil
}

// RevokeSpaceRole is the resolver for the revokeSpaceRole field.
func (r *mutationResolver) RevokeSpaceRole(ctx context.Context, input model.RevokeSpaceRoleInput) (bool, error) {
	caller, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	spaceID, err := r.requireServerSpaceID(ctx)
	if err != nil {
		return false, err
	}

	if err := r.core.RevokeRole(ctx, caller.Id, spaceID, input.UserID, input.RoleName); err != nil {
		return false, err
	}
	return true, nil
}

// ReorderSpaceRoles is the resolver for the reorderSpaceRoles field.
func (r *mutationResolver) ReorderSpaceRoles(ctx context.Context, input model.ReorderSpaceRolesInput) ([]*core.RoleWithPermissions, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	spaceID, err := r.requireServerSpaceID(ctx)
	if err != nil {
		return nil, err
	}

	roles, err := r.core.ReorderSpaceRoles(ctx, user.Id, spaceID, input.RoleNames)
	if err != nil {
		return nil, err
	}

	return r.spaceRolesToGraphQL(ctx, spaceID, roles), nil
}

// GrantRoomPermission is the resolver for the grantRoomPermission field.
func (r *mutationResolver) GrantRoomPermission(ctx context.Context, input model.GrantRoomPermissionInput) (bool, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	spaceID, err := r.requireServerSpaceID(ctx)
	if err != nil {
		return false, err
	}

	if err := r.core.GrantRoomRolePermission(ctx, user.Id, spaceID, input.RoomID, input.Role, core.Permission(input.Permission)); err != nil {
		return false, err
	}
	return true, nil
}

// DenyRoomPermission is the resolver for the denyRoomPermission field.
func (r *mutationResolver) DenyRoomPermission(ctx context.Context, input model.DenyRoomPermissionInput) (bool, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	spaceID, err := r.requireServerSpaceID(ctx)
	if err != nil {
		return false, err
	}

	if err := r.core.DenyRoomRolePermission(ctx, user.Id, spaceID, input.RoomID, input.Role, core.Permission(input.Permission)); err != nil {
		return false, err
	}
	return true, nil
}

// ClearRoomPermission is the resolver for the clearRoomPermission field.
func (r *mutationResolver) ClearRoomPermission(ctx context.Context, input model.ClearRoomPermissionInput) (bool, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	spaceID, err := r.requireServerSpaceID(ctx)
	if err != nil {
		return false, err
	}

	if err := r.core.ClearRoomRolePermission(ctx, user.Id, spaceID, input.RoomID, input.Role, core.Permission(input.Permission)); err != nil {
		return false, err
	}
	return true, nil
}

// RoomPermissionOverrides is the resolver for the roomPermissionOverrides field.
func (r *roomResolver) RoomPermissionOverrides(ctx context.Context, obj *corev1.Room) ([]*model.RoleRoomPermissions, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return nil, fmt.Errorf("authentication required")
	}

	can, err := r.core.CanSpaceRolesManage(ctx, user.Id, obj.SpaceId)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, core.ErrPermissionDenied
	}

	var result []*model.RoleRoomPermissions

	spaceRoles, err := r.core.ListRoles(ctx, obj.SpaceId)
	if err != nil {
		return nil, err
	}
	for _, role := range spaceRoles {
		grants, denials, err := r.core.GetRoleRoomPermissions(ctx, obj.SpaceId, obj.Id, role.Name)
		if err != nil {
			return nil, err
		}
		grantStrs := make([]string, len(grants))
		for i, g := range grants {
			grantStrs[i] = string(g)
		}
		denialStrs := make([]string, len(denials))
		for i, d := range denials {
			denialStrs[i] = string(d)
		}
		result = append(result, &model.RoleRoomPermissions{
			RoleName:          role.Name,
			DisplayName:       role.DisplayName,
			IsInstanceRole:    false,
			IsSystem:          core.IsSpaceSystemRole(role.Name),
			Position:          role.Position,
			Permissions:       grantStrs,
			PermissionDenials: denialStrs,
		})
	}

	instanceRoles, err := r.core.ListInstanceRoles(ctx)
	if err != nil {
		return nil, err
	}
	for _, irole := range instanceRoles {
		if core.IsSpaceUniversalRole(irole.Name) {
			continue
		}
		grants, denials, err := r.core.GetRoleRoomPermissions(ctx, obj.SpaceId, obj.Id, irole.Name)
		if err != nil {
			return nil, err
		}
		grantStrs := make([]string, len(grants))
		for i, g := range grants {
			grantStrs[i] = string(g)
		}
		denialStrs := make([]string, len(denials))
		for i, d := range denials {
			denialStrs[i] = string(d)
		}
		result = append(result, &model.RoleRoomPermissions{
			RoleName:          irole.Name,
			DisplayName:       irole.DisplayName,
			IsInstanceRole:    true,
			IsSystem:          irole.IsSystem,
			Position:          irole.Position,
			Permissions:       grantStrs,
			PermissionDenials: denialStrs,
		})
	}

	return result, nil
}

// AvailableRoomPermissions is the resolver for the availableRoomPermissions field.
func (r *roomResolver) AvailableRoomPermissions(ctx context.Context, obj *corev1.Room) ([]string, error) {
	perms := core.PermissionsForScope(core.ScopeRoom)
	result := make([]string, len(perms))
	for i, p := range perms {
		result[i] = string(p.Permission)
	}
	return result, nil
}
