package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"hmans.de/chatto/internal/graph/model"
)

// PermissionExplanation is the resolver for the permissionExplanation field.
func (r *queryResolver) PermissionExplanation(ctx context.Context, userID string, roomID *string) ([]*model.PermissionExplanation, error) {
	viewer, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	scopedRoomID := ""
	if roomID != nil {
		scopedRoomID = *roomID
	}

	// Room scope implies the deployment's primary space; instance scope
	// (no roomId) leaves spaceID empty so the resolver runs in instance-only
	// mode.
	scopedSpaceID := ""
	if scopedRoomID != "" {
		scopedSpaceID, err = r.requireServerSpaceID(ctx)
		if err != nil {
			return nil, err
		}
	}

	if err := r.authorizePermissionExplanation(ctx, viewer.Id, userID, scopedSpaceID, scopedRoomID); err != nil {
		return nil, err
	}

	results, err := r.core.PermResolver().ExplainAllPermissions(ctx, userID, scopedSpaceID, scopedRoomID)
	if err != nil {
		return nil, err
	}

	out := make([]*model.PermissionExplanation, 0, len(results))
	for _, exp := range results {
		out = append(out, toModelExplanation(exp))
	}
	return out, nil
}
