package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"hmans.de/chatto/internal/core"
	corev1 "hmans.de/chatto/internal/pb/chatto/core/v1"
)

// Room is the resolver for the room field.
func (r *queryResolver) Room(ctx context.Context, roomID string) (*corev1.Room, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	kind, err := r.resolveRoomKind(ctx, roomID)
	if err != nil {
		return nil, err
	}

	// Authorization: require room membership
	isMember, err := r.core.RoomMembershipExists(ctx, kind, user.Id, roomID)
	if err != nil {
		return nil, err
	}
	if !isMember {
		return nil, core.ErrNotRoomMember
	}

	return r.core.GetRoom(ctx, kind, roomID)
}

// RoomByName is the resolver for the roomByName field.
func (r *queryResolver) RoomByName(ctx context.Context, name string) (*corev1.Room, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	room, err := r.core.FindRoomByName(ctx, name)
	if err != nil {
		return nil, err
	}
	kind := core.KindOfRoom(room)

	// Authorization: require room membership, matching room(roomId).
	isMember, err := r.core.RoomMembershipExists(ctx, kind, user.Id, room.Id)
	if err != nil {
		return nil, err
	}
	if !isMember {
		return nil, core.ErrNotRoomMember
	}

	return room, nil
}

// User is the resolver for the user field.
// User profiles are visible to authenticated server users.
func (r *queryResolver) User(ctx context.Context, userID string) (*corev1.User, error) {
	return r.core.GetUser(ctx, userID)
}

// UserByLogin is the resolver for the userByLogin field.
// Returns the user with the given login name, or null if not found.
// User profiles are visible to authenticated server users.
func (r *queryResolver) UserByLogin(ctx context.Context, login string) (*corev1.User, error) {
	user, err := r.core.GetUserByLogin(ctx, login)
	if err != nil {
		// Return nil instead of error for "not found" cases
		return nil, nil
	}
	return user, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
