package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"hmans.de/chatto/internal/graph/model"
)

// RolePermissions is the resolver for the rolePermissions field.
//
// Scopes resolve as follows:
//   - no roomId → server scope only.
//   - roomId    → server + room.
func (r *queryResolver) RolePermissions(ctx context.Context, roleName string, roomID *string) (*model.RoleAcrossTiers, error) {
	viewer, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	scopedRoomID := ""
	if roomID != nil {
		scopedRoomID = *roomID
	}

	scopedKind := ""
	if scopedRoomID != "" {
		scopedKind = "channel"
	}

	if err := r.authorizeRolePermissions(ctx, viewer.Id, scopedKind, scopedRoomID); err != nil {
		return nil, err
	}

	return r.buildRoleAcrossTiers(ctx, roleName, scopedKind, scopedRoomID)
}

// TierRoles is the resolver for the tierRoles field.
func (r *queryResolver) TierRoles(ctx context.Context, roomID *string, groupID *string) (*model.TierRoles, error) {
	viewer, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	scopedRoomID := ""
	if roomID != nil {
		scopedRoomID = *roomID
	}
	scopedGroupID := ""
	if groupID != nil {
		scopedGroupID = *groupID
	}
	if scopedRoomID != "" && scopedGroupID != "" {
		return nil, fmt.Errorf("tierRoles: pass roomId OR groupId, not both")
	}

	scopedKind := ""
	if scopedRoomID != "" || scopedGroupID != "" {
		scopedKind = "channel"
	}

	if err := r.authorizeRolePermissions(ctx, viewer.Id, scopedKind, scopedRoomID); err != nil {
		return nil, err
	}

	return r.buildTierRoles(ctx, scopedKind, scopedRoomID, scopedGroupID)
}
