package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"hmans.de/chatto/internal/graph/model"
	corev1 "hmans.de/chatto/internal/pb/chatto/core/v1"
)

// Rooms is the resolver for the rooms field.
// Returns the ordered list of rooms in this set.
// Room IDs that don't exist (or that the viewer isn't a member of) are silently skipped.
func (r *roomGroupResolver) Rooms(ctx context.Context, obj *model.RoomGroupModel) ([]*corev1.Room, error) {
	if obj.ViewerRooms == nil {
		return []*corev1.Room{}, nil
	}

	var rooms []*corev1.Room
	for _, roomID := range obj.RoomIds {
		if room, ok := obj.ViewerRooms[roomID]; ok {
			rooms = append(rooms, room)
		}
	}

	return rooms, nil
}

// Items is the resolver for the items field.
func (r *roomGroupResolver) Items(ctx context.Context, obj *model.RoomGroupModel) ([]*model.RoomGroupItem, error) {
	links := make(map[string]*corev1.SidebarLink, len(obj.SidebarLinks))
	for _, link := range obj.SidebarLinks {
		links[link.GetId()] = link
	}

	items := make([]*model.RoomGroupItem, 0, len(obj.Entries))
	for _, entry := range obj.Entries {
		switch entry.GetKind() {
		case corev1.SidebarGroupEntry_ROOM:
			var room *corev1.Room
			if obj.ViewerRooms != nil {
				room = obj.ViewerRooms[entry.GetId()]
				if room == nil {
					continue
				}
			}
			items = append(items, &model.RoomGroupItem{
				Type: model.RoomGroupItemTypeRoom,
				ID:   entry.GetId(),
				Room: room,
			})
		case corev1.SidebarGroupEntry_SIDEBAR_LINK:
			link := links[entry.GetId()]
			if link == nil {
				continue
			}
			items = append(items, &model.RoomGroupItem{
				Type: model.RoomGroupItemTypeSidebarLink,
				ID:   entry.GetId(),
				Link: link,
			})
		}
	}
	return items, nil
}

// RoomGroup returns RoomGroupResolver implementation.
func (r *Resolver) RoomGroup() RoomGroupResolver { return &roomGroupResolver{r} }

type roomGroupResolver struct{ *Resolver }
