package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"errors"

	"hmans.de/chatto/internal/graph/auth"
	"hmans.de/chatto/internal/graph/model"
	corev1 "hmans.de/chatto/internal/pb/chatto/core/v1"
)

// Member is the resolver for the member field.
func (r *spaceResolver) Member(ctx context.Context, obj *corev1.Space, userID string) (*corev1.User, error) {
	caller := auth.ForContext(ctx)
	if caller == nil {
		return nil, errors.New("authentication required")
	}

	// Check space membership of caller
	isMember, err := r.core.SpaceMembershipExists(ctx, caller.Id, obj.Id)
	if err != nil {
		return nil, err
	}
	if !isMember {
		return nil, errors.New("space membership required")
	}

	// Check if the target user is a member
	targetIsMember, err := r.core.SpaceMembershipExists(ctx, userID, obj.Id)
	if err != nil {
		return nil, err
	}
	if !targetIsMember {
		return nil, nil // User is not a member
	}

	// Get user data
	return r.core.GetUser(ctx, userID)
}

// Members is the resolver for the members field.
func (r *spaceResolver) Members(ctx context.Context, obj *corev1.Space, search *string, limit *int32, offset *int32) (*model.SpaceMembersConnection, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return nil, errors.New("authentication required")
	}

	// Check space membership
	isMember, err := r.core.SpaceMembershipExists(ctx, user.Id, obj.Id)
	if err != nil {
		return nil, err
	}
	if !isMember {
		return nil, errors.New("space membership required")
	}

	// Set defaults
	searchStr := ""
	if search != nil {
		searchStr = *search
	}
	limitVal := 20
	if limit != nil && *limit > 0 {
		limitVal = int(*limit)
		if limitVal > 100 {
			limitVal = 100
		}
	}
	offsetVal := 0
	if offset != nil && *offset >= 0 {
		offsetVal = int(*offset)
	}

	// Get members from core
	members, totalCount, err := r.core.GetSpaceMembers(ctx, obj.Id, searchStr, limitVal, offsetVal)
	if err != nil {
		return nil, err
	}

	// Convert to User objects
	users := make([]*corev1.User, 0, len(members))
	for _, m := range members {
		user, err := r.core.GetUser(ctx, m.UserID)
		if err != nil {
			continue // Skip users that can't be loaded
		}
		users = append(users, user)
	}

	return &model.SpaceMembersConnection{
		Users:      users,
		TotalCount: int32(totalCount),
		HasMore:    offsetVal+len(users) < totalCount,
	}, nil
}
