package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"time"

	"hmans.de/chatto/internal/core"
)

// MyEvents is the resolver for the myEvents field.
//
// Backed by a single core stream (StreamMyEvents) that consumes
// `live.sync.>` transient LiveEvent messages and `live.evt.>` raw EVT
// republish messages, plus presence and heartbeats.
func (r *subscriptionResolver) MyEvents(ctx context.Context, after *string) (<-chan core.EventEnvelope, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	var afterSeq uint64
	if after != nil {
		afterSeq, err = r.core.ParseEventDeliveryCursor(user.Id, *after, time.Now())
		if err != nil {
			if core.EventReplayRequiresFullRefresh(err) {
				return nil, myEventsFullRefreshRequiredError(err)
			}
			return nil, fmt.Errorf("invalid after cursor: %w", err)
		}
	}

	events, err := r.core.StreamMyEvents(ctx, user.Id, afterSeq)
	if err != nil {
		if core.EventReplayRequiresFullRefresh(err) {
			return nil, myEventsFullRefreshRequiredError(err)
		}
		return nil, fmt.Errorf("subscribe events: %w", err)
	}
	return events, nil
}

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
