package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"hmans.de/chatto/internal/graph/model"
)

// UserPermissionMatrix is the resolver for the userPermissionMatrix field.
// Authorization mirrors the user-level mutation gate: callers need
// role.manage AND must strictly outrank the target user. Self-introspection
// is intentionally not allowed — the matrix is an operator surface.
func (r *queryResolver) UserPermissionMatrix(ctx context.Context, userID string) (*model.UserPermissionMatrix, error) {
	caller, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	if err := r.requireUserPermissionTarget(ctx, caller.Id, userID); err != nil {
		return nil, err
	}
	return r.buildUserPermissionMatrix(ctx, userID)
}
