// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/api/v1/link_previews.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { FetchLinkPreviewRequest, FetchLinkPreviewResponse } from "./link_previews_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Fetches link preview metadata for message composers.
 *
 * @generated from service chatto.api.v1.LinkPreviewService
 */
export const LinkPreviewService = {
  typeName: "chatto.api.v1.LinkPreviewService",
  methods: {
    /**
     * Fetches and caches metadata for a URL. Authentication is required to avoid
     * exposing the preview fetcher as an unauthenticated network proxy.
     *
     * @generated from rpc chatto.api.v1.LinkPreviewService.FetchLinkPreview
     */
    fetchLinkPreview: {
      name: "FetchLinkPreview",
      I: FetchLinkPreviewRequest,
      O: FetchLinkPreviewResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;
