// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/api/v1/roles.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ListRolesRequest, ListRolesResponse } from "./roles_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Provides authenticated reads for public role metadata.
 *
 * @generated from service chatto.api.v1.RoleService
 */
export const RoleService = {
  typeName: "chatto.api.v1.RoleService",
  methods: {
    /**
     * Lists the current role catalog as a finite snapshot. Requires an
     * authenticated user.
     *
     * @generated from rpc chatto.api.v1.RoleService.ListRoles
     */
    listRoles: {
      name: "ListRoles",
      I: ListRolesRequest,
      O: ListRolesResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;
