// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/admin/v1/members.proto

package adminv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	v1 "hmans.de/chatto/internal/pb/chatto/api/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User row returned by server-admin member management reads.
//
// The embedded user record carries public identity fields; remaining fields are
// admin/member metadata with visibility controlled by the service.
type AdminMember struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Explicit role assignments. The implicit everyone role is omitted.
	Roles []string `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"`
	// Account creation time, when known.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Whether the caller may see that the user has a verified email and one exists.
	HasVerifiedEmail bool `protobuf:"varint,8,opt,name=has_verified_email,json=hasVerifiedEmail,proto3" json:"has_verified_email,omitempty"`
	// Verified email addresses visible to the caller.
	VerifiedEmails []string `protobuf:"bytes,9,rep,name=verified_emails,json=verifiedEmails,proto3" json:"verified_emails,omitempty"`
	// Whether the caller may delete this account.
	ViewerCanDeleteAccount bool `protobuf:"varint,10,opt,name=viewer_can_delete_account,json=viewerCanDeleteAccount,proto3" json:"viewer_can_delete_account,omitempty"`
	// Last self-service username change, when visible and known.
	LastLoginChange *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_login_change,json=lastLoginChange,proto3" json:"last_login_change,omitempty"`
	// Public identity fields for this user.
	User          *v1.User `protobuf:"bytes,12,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminMember) Reset() {
	*x = AdminMember{}
	mi := &file_chatto_admin_v1_members_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminMember) ProtoMessage() {}

func (x *AdminMember) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_members_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminMember.ProtoReflect.Descriptor instead.
func (*AdminMember) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_members_proto_rawDescGZIP(), []int{0}
}

func (x *AdminMember) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *AdminMember) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AdminMember) GetHasVerifiedEmail() bool {
	if x != nil {
		return x.HasVerifiedEmail
	}
	return false
}

func (x *AdminMember) GetVerifiedEmails() []string {
	if x != nil {
		return x.VerifiedEmails
	}
	return nil
}

func (x *AdminMember) GetViewerCanDeleteAccount() bool {
	if x != nil {
		return x.ViewerCanDeleteAccount
	}
	return false
}

func (x *AdminMember) GetLastLoginChange() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLoginChange
	}
	return nil
}

func (x *AdminMember) GetUser() *v1.User {
	if x != nil {
		return x.User
	}
	return nil
}

// Legacy role reference used by operator.v1 response shapes.
type AdminRoleReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable role name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Display name shown in operator UI.
	DisplayName   string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminRoleReference) Reset() {
	*x = AdminRoleReference{}
	mi := &file_chatto_admin_v1_members_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRoleReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRoleReference) ProtoMessage() {}

func (x *AdminRoleReference) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_members_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRoleReference.ProtoReflect.Descriptor instead.
func (*AdminRoleReference) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_members_proto_rawDescGZIP(), []int{1}
}

func (x *AdminRoleReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminRoleReference) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// Legacy role details used by operator.v1 response shapes.
type AdminMemberRole struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable role name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Display name shown in operator UI.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Display/order position.
	Position int32 `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	// Permissions granted by this role.
	Permissions []string `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	// Permissions denied by this role.
	PermissionDenials []string `protobuf:"bytes,5,rep,name=permission_denials,json=permissionDenials,proto3" json:"permission_denials,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AdminMemberRole) Reset() {
	*x = AdminMemberRole{}
	mi := &file_chatto_admin_v1_members_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminMemberRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminMemberRole) ProtoMessage() {}

func (x *AdminMemberRole) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_members_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminMemberRole.ProtoReflect.Descriptor instead.
func (*AdminMemberRole) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_members_proto_rawDescGZIP(), []int{2}
}

func (x *AdminMemberRole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminMemberRole) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AdminMemberRole) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *AdminMemberRole) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *AdminMemberRole) GetPermissionDenials() []string {
	if x != nil {
		return x.PermissionDenials
	}
	return nil
}

// Request server-admin member rows.
type ListMembersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Case-insensitive login/display-name search term. Empty disables search.
	Search string `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	// Page request. Defaults to 20 results when absent or limit is zero.
	Page          *v1.PageRequest `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_chatto_admin_v1_members_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_members_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_members_proto_rawDescGZIP(), []int{3}
}

func (x *ListMembersRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListMembersRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

// Server-admin member rows plus role summaries.
type ListMembersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matching users.
	Users []*AdminMember `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	// Public roles for display-name lookup.
	Roles []*v1.Role `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	// Page metadata.
	Page          *v1.PageInfo `protobuf:"bytes,5,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_chatto_admin_v1_members_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_members_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_members_proto_rawDescGZIP(), []int{4}
}

func (x *ListMembersResponse) GetUsers() []*AdminMember {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListMembersResponse) GetRoles() []*v1.Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ListMembersResponse) GetPage() *v1.PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

// Request one server-admin member detail record.
type GetMemberRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target user ID.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Target login. Provide either user_id or login.
	Login         string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberRequest) Reset() {
	*x = GetMemberRequest{}
	mi := &file_chatto_admin_v1_members_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberRequest) ProtoMessage() {}

func (x *GetMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_members_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberRequest.ProtoReflect.Descriptor instead.
func (*GetMemberRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_members_proto_rawDescGZIP(), []int{5}
}

func (x *GetMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetMemberRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

// Server-admin member detail payload.
type GetMemberResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Member record.
	Member *AdminMember `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	// Roles for assignment UI.
	Roles []*AdminRole `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	// Permissions available for per-user overrides.
	AvailablePermissions []string `protobuf:"bytes,3,rep,name=available_permissions,json=availablePermissions,proto3" json:"available_permissions,omitempty"`
	// Whether the caller may assign/revoke roles.
	ViewerCanAssignRoles bool `protobuf:"varint,4,opt,name=viewer_can_assign_roles,json=viewerCanAssignRoles,proto3" json:"viewer_can_assign_roles,omitempty"`
	// Whether the caller may edit role definitions.
	ViewerCanManageRoles bool `protobuf:"varint,5,opt,name=viewer_can_manage_roles,json=viewerCanManageRoles,proto3" json:"viewer_can_manage_roles,omitempty"`
	// Whether the caller may edit direct user permissions.
	ViewerCanManageUserPermissions bool `protobuf:"varint,6,opt,name=viewer_can_manage_user_permissions,json=viewerCanManageUserPermissions,proto3" json:"viewer_can_manage_user_permissions,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *GetMemberResponse) Reset() {
	*x = GetMemberResponse{}
	mi := &file_chatto_admin_v1_members_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberResponse) ProtoMessage() {}

func (x *GetMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_members_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberResponse.ProtoReflect.Descriptor instead.
func (*GetMemberResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_members_proto_rawDescGZIP(), []int{6}
}

func (x *GetMemberResponse) GetMember() *AdminMember {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *GetMemberResponse) GetRoles() []*AdminRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *GetMemberResponse) GetAvailablePermissions() []string {
	if x != nil {
		return x.AvailablePermissions
	}
	return nil
}

func (x *GetMemberResponse) GetViewerCanAssignRoles() bool {
	if x != nil {
		return x.ViewerCanAssignRoles
	}
	return false
}

func (x *GetMemberResponse) GetViewerCanManageRoles() bool {
	if x != nil {
		return x.ViewerCanManageRoles
	}
	return false
}

func (x *GetMemberResponse) GetViewerCanManageUserPermissions() bool {
	if x != nil {
		return x.ViewerCanManageUserPermissions
	}
	return false
}

// Request to assign a role to a user.
type AssignRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target user ID.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Role name to assign.
	RoleName      string `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleRequest) Reset() {
	*x = AssignRoleRequest{}
	mi := &file_chatto_admin_v1_members_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleRequest) ProtoMessage() {}

func (x *AssignRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_members_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleRequest.ProtoReflect.Descriptor instead.
func (*AssignRoleRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_members_proto_rawDescGZIP(), []int{7}
}

func (x *AssignRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignRoleRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

// Result of assigning a role.
type AssignRoleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the request completed.
	Assigned bool `protobuf:"varint,1,opt,name=assigned,proto3" json:"assigned,omitempty"`
	// Updated admin member row.
	Member        *AdminMember `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleResponse) Reset() {
	*x = AssignRoleResponse{}
	mi := &file_chatto_admin_v1_members_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleResponse) ProtoMessage() {}

func (x *AssignRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_members_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleResponse.ProtoReflect.Descriptor instead.
func (*AssignRoleResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_members_proto_rawDescGZIP(), []int{8}
}

func (x *AssignRoleResponse) GetAssigned() bool {
	if x != nil {
		return x.Assigned
	}
	return false
}

func (x *AssignRoleResponse) GetMember() *AdminMember {
	if x != nil {
		return x.Member
	}
	return nil
}

// Request to revoke a role from a user.
type RevokeRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target user ID.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Role name to revoke.
	RoleName      string `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRoleRequest) Reset() {
	*x = RevokeRoleRequest{}
	mi := &file_chatto_admin_v1_members_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRoleRequest) ProtoMessage() {}

func (x *RevokeRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_members_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRoleRequest.ProtoReflect.Descriptor instead.
func (*RevokeRoleRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_members_proto_rawDescGZIP(), []int{9}
}

func (x *RevokeRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RevokeRoleRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

// Result of revoking a role.
type RevokeRoleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the request completed.
	Revoked bool `protobuf:"varint,1,opt,name=revoked,proto3" json:"revoked,omitempty"`
	// Updated admin member row.
	Member        *AdminMember `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRoleResponse) Reset() {
	*x = RevokeRoleResponse{}
	mi := &file_chatto_admin_v1_members_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRoleResponse) ProtoMessage() {}

func (x *RevokeRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_members_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRoleResponse.ProtoReflect.Descriptor instead.
func (*RevokeRoleResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_members_proto_rawDescGZIP(), []int{10}
}

func (x *RevokeRoleResponse) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *RevokeRoleResponse) GetMember() *AdminMember {
	if x != nil {
		return x.Member
	}
	return nil
}

// Request to update a user's identity as a server-admin action.
type UpdateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target user ID.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// New display name, when changing it.
	DisplayName *string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	// New login identifier, when changing it.
	Login         *string `protobuf:"bytes,3,opt,name=login,proto3,oneof" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_chatto_admin_v1_members_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_members_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_members_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UpdateUserRequest) GetLogin() string {
	if x != nil && x.Login != nil {
		return *x.Login
	}
	return ""
}

// Result of an admin user update.
type UpdateUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated user profile.
	User *v1.User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// Updated admin member row.
	Member        *AdminMember `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_chatto_admin_v1_members_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_members_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_members_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateUserResponse) GetUser() *v1.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UpdateUserResponse) GetMember() *AdminMember {
	if x != nil {
		return x.Member
	}
	return nil
}

// Request to set a user's password as a server-admin action.
type SetUserPasswordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target user ID.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// New password. The server applies the same password policy as registration
	// and password reset.
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserPasswordRequest) Reset() {
	*x = SetUserPasswordRequest{}
	mi := &file_chatto_admin_v1_members_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserPasswordRequest) ProtoMessage() {}

func (x *SetUserPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_members_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserPasswordRequest.ProtoReflect.Descriptor instead.
func (*SetUserPasswordRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_members_proto_rawDescGZIP(), []int{13}
}

func (x *SetUserPasswordRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetUserPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Result of an admin password update.
type SetUserPasswordResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the request completed.
	Updated       bool `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserPasswordResponse) Reset() {
	*x = SetUserPasswordResponse{}
	mi := &file_chatto_admin_v1_members_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserPasswordResponse) ProtoMessage() {}

func (x *SetUserPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_members_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserPasswordResponse.ProtoReflect.Descriptor instead.
func (*SetUserPasswordResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_members_proto_rawDescGZIP(), []int{14}
}

func (x *SetUserPasswordResponse) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

// Request to clear a user's self-service username-change cooldown.
type ClearUsernameCooldownRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target user ID.
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearUsernameCooldownRequest) Reset() {
	*x = ClearUsernameCooldownRequest{}
	mi := &file_chatto_admin_v1_members_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearUsernameCooldownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearUsernameCooldownRequest) ProtoMessage() {}

func (x *ClearUsernameCooldownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_members_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearUsernameCooldownRequest.ProtoReflect.Descriptor instead.
func (*ClearUsernameCooldownRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_members_proto_rawDescGZIP(), []int{15}
}

func (x *ClearUsernameCooldownRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Result of clearing a user's username-change cooldown.
type ClearUsernameCooldownResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the request completed.
	Cleared       bool `protobuf:"varint,1,opt,name=cleared,proto3" json:"cleared,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearUsernameCooldownResponse) Reset() {
	*x = ClearUsernameCooldownResponse{}
	mi := &file_chatto_admin_v1_members_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearUsernameCooldownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearUsernameCooldownResponse) ProtoMessage() {}

func (x *ClearUsernameCooldownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_members_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearUsernameCooldownResponse.ProtoReflect.Descriptor instead.
func (*ClearUsernameCooldownResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_members_proto_rawDescGZIP(), []int{16}
}

func (x *ClearUsernameCooldownResponse) GetCleared() bool {
	if x != nil {
		return x.Cleared
	}
	return false
}

// Request to delete a user account as a server-admin action.
type DeleteUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target user ID.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Current password proof for accounts with a password when the active
	// runtime credential is no longer fresh.
	CurrentPassword string `protobuf:"bytes,2,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_chatto_admin_v1_members_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_members_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_members_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteUserRequest) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

// Result of deleting a user account.
type DeleteUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the user was deleted.
	Deleted       bool `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_chatto_admin_v1_members_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_members_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_members_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteUserResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_chatto_admin_v1_members_proto protoreflect.FileDescriptor

const file_chatto_admin_v1_members_proto_rawDesc = "" +
	"\n" +
	"\x1dchatto/admin/v1/members.proto\x12\x0fchatto.admin.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1echatto/api/v1/pagination.proto\x1a\x19chatto/api/v1/roles.proto\x1a\x19chatto/api/v1/users.proto\x1a\x1bchatto/admin/v1/roles.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\x03\n" +
	"\vAdminMember\x12\x14\n" +
	"\x05roles\x18\x05 \x03(\tR\x05roles\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12,\n" +
	"\x12has_verified_email\x18\b \x01(\bR\x10hasVerifiedEmail\x12'\n" +
	"\x0fverified_emails\x18\t \x03(\tR\x0everifiedEmails\x129\n" +
	"\x19viewer_can_delete_account\x18\n" +
	" \x01(\bR\x16viewerCanDeleteAccount\x12F\n" +
	"\x11last_login_change\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x0flastLoginChange\x12'\n" +
	"\x04user\x18\f \x01(\v2\x13.chatto.api.v1.UserR\x04userJ\x04\b\x01\x10\x05J\x04\b\a\x10\bR\x02idR\x05loginR\fdisplay_nameR\n" +
	"avatar_urlR\adeleted\"K\n" +
	"\x12AdminRoleReference\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"\xb5\x01\n" +
	"\x0fAdminMemberRole\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x05R\bposition\x12 \n" +
	"\vpermissions\x18\x04 \x03(\tR\vpermissions\x12-\n" +
	"\x12permission_denials\x18\x05 \x03(\tR\x11permissionDenials\"w\n" +
	"\x12ListMembersRequest\x12\x16\n" +
	"\x06search\x18\x01 \x01(\tR\x06search\x12.\n" +
	"\x04page\x18\x04 \x01(\v2\x1a.chatto.api.v1.PageRequestR\x04pageJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04R\x05limitR\x06offset\"\xc4\x01\n" +
	"\x13ListMembersResponse\x122\n" +
	"\x05users\x18\x01 \x03(\v2\x1c.chatto.admin.v1.AdminMemberR\x05users\x12)\n" +
	"\x05roles\x18\x02 \x03(\v2\x13.chatto.api.v1.RoleR\x05roles\x12+\n" +
	"\x04page\x18\x05 \x01(\v2\x17.chatto.api.v1.PageInfoR\x04pageJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05R\vtotal_countR\bhas_more\"A\n" +
	"\x10GetMemberRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\"\xea\x02\n" +
	"\x11GetMemberResponse\x124\n" +
	"\x06member\x18\x01 \x01(\v2\x1c.chatto.admin.v1.AdminMemberR\x06member\x120\n" +
	"\x05roles\x18\x02 \x03(\v2\x1a.chatto.admin.v1.AdminRoleR\x05roles\x123\n" +
	"\x15available_permissions\x18\x03 \x03(\tR\x14availablePermissions\x125\n" +
	"\x17viewer_can_assign_roles\x18\x04 \x01(\bR\x14viewerCanAssignRoles\x125\n" +
	"\x17viewer_can_manage_roles\x18\x05 \x01(\bR\x14viewerCanManageRoles\x12J\n" +
	"\"viewer_can_manage_user_permissions\x18\x06 \x01(\bR\x1eviewerCanManageUserPermissions\"[\n" +
	"\x11AssignRoleRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\x12$\n" +
	"\trole_name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\broleName\"f\n" +
	"\x12AssignRoleResponse\x12\x1a\n" +
	"\bassigned\x18\x01 \x01(\bR\bassigned\x124\n" +
	"\x06member\x18\x02 \x01(\v2\x1c.chatto.admin.v1.AdminMemberR\x06member\"[\n" +
	"\x11RevokeRoleRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\x12$\n" +
	"\trole_name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\broleName\"d\n" +
	"\x12RevokeRoleResponse\x12\x18\n" +
	"\arevoked\x18\x01 \x01(\bR\arevoked\x124\n" +
	"\x06member\x18\x02 \x01(\v2\x1c.chatto.admin.v1.AdminMemberR\x06member\"\x93\x01\n" +
	"\x11UpdateUserRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\x12&\n" +
	"\fdisplay_name\x18\x02 \x01(\tH\x00R\vdisplayName\x88\x01\x01\x12\x19\n" +
	"\x05login\x18\x03 \x01(\tH\x01R\x05login\x88\x01\x01B\x0f\n" +
	"\r_display_nameB\b\n" +
	"\x06_login\"s\n" +
	"\x12UpdateUserResponse\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.chatto.api.v1.UserR\x04user\x124\n" +
	"\x06member\x18\x02 \x01(\v2\x1c.chatto.admin.v1.AdminMemberR\x06member\"V\n" +
	"\x16SetUserPasswordRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"3\n" +
	"\x17SetUserPasswordResponse\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\bR\aupdated\"@\n" +
	"\x1cClearUsernameCooldownRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\"9\n" +
	"\x1dClearUsernameCooldownResponse\x12\x18\n" +
	"\acleared\x18\x01 \x01(\bR\acleared\"`\n" +
	"\x11DeleteUserRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\x12)\n" +
	"\x10current_password\x18\x02 \x01(\tR\x0fcurrentPassword\".\n" +
	"\x12DeleteUserResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted2\xfc\x05\n" +
	"\x12AdminMemberService\x12X\n" +
	"\vListMembers\x12#.chatto.admin.v1.ListMembersRequest\x1a$.chatto.admin.v1.ListMembersResponse\x12R\n" +
	"\tGetMember\x12!.chatto.admin.v1.GetMemberRequest\x1a\".chatto.admin.v1.GetMemberResponse\x12U\n" +
	"\n" +
	"AssignRole\x12\".chatto.admin.v1.AssignRoleRequest\x1a#.chatto.admin.v1.AssignRoleResponse\x12U\n" +
	"\n" +
	"RevokeRole\x12\".chatto.admin.v1.RevokeRoleRequest\x1a#.chatto.admin.v1.RevokeRoleResponse\x12U\n" +
	"\n" +
	"UpdateUser\x12\".chatto.admin.v1.UpdateUserRequest\x1a#.chatto.admin.v1.UpdateUserResponse\x12d\n" +
	"\x0fSetUserPassword\x12'.chatto.admin.v1.SetUserPasswordRequest\x1a(.chatto.admin.v1.SetUserPasswordResponse\x12v\n" +
	"\x15ClearUsernameCooldown\x12-.chatto.admin.v1.ClearUsernameCooldownRequest\x1a..chatto.admin.v1.ClearUsernameCooldownResponse\x12U\n" +
	"\n" +
	"DeleteUser\x12\".chatto.admin.v1.DeleteUserRequest\x1a#.chatto.admin.v1.DeleteUserResponseB\xb6\x01\n" +
	"\x13com.chatto.admin.v1B\fMembersProtoP\x01Z3hmans.de/chatto/internal/pb/chatto/admin/v1;adminv1\xa2\x02\x03CAX\xaa\x02\x0fChatto.Admin.V1\xca\x02\x0fChatto\\Admin\\V1\xe2\x02\x1bChatto\\Admin\\V1\\GPBMetadata\xea\x02\x11Chatto::Admin::V1b\x06proto3"

var (
	file_chatto_admin_v1_members_proto_rawDescOnce sync.Once
	file_chatto_admin_v1_members_proto_rawDescData []byte
)

func file_chatto_admin_v1_members_proto_rawDescGZIP() []byte {
	file_chatto_admin_v1_members_proto_rawDescOnce.Do(func() {
		file_chatto_admin_v1_members_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_admin_v1_members_proto_rawDesc), len(file_chatto_admin_v1_members_proto_rawDesc)))
	})
	return file_chatto_admin_v1_members_proto_rawDescData
}

var file_chatto_admin_v1_members_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_chatto_admin_v1_members_proto_goTypes = []any{
	(*AdminMember)(nil),                   // 0: chatto.admin.v1.AdminMember
	(*AdminRoleReference)(nil),            // 1: chatto.admin.v1.AdminRoleReference
	(*AdminMemberRole)(nil),               // 2: chatto.admin.v1.AdminMemberRole
	(*ListMembersRequest)(nil),            // 3: chatto.admin.v1.ListMembersRequest
	(*ListMembersResponse)(nil),           // 4: chatto.admin.v1.ListMembersResponse
	(*GetMemberRequest)(nil),              // 5: chatto.admin.v1.GetMemberRequest
	(*GetMemberResponse)(nil),             // 6: chatto.admin.v1.GetMemberResponse
	(*AssignRoleRequest)(nil),             // 7: chatto.admin.v1.AssignRoleRequest
	(*AssignRoleResponse)(nil),            // 8: chatto.admin.v1.AssignRoleResponse
	(*RevokeRoleRequest)(nil),             // 9: chatto.admin.v1.RevokeRoleRequest
	(*RevokeRoleResponse)(nil),            // 10: chatto.admin.v1.RevokeRoleResponse
	(*UpdateUserRequest)(nil),             // 11: chatto.admin.v1.UpdateUserRequest
	(*UpdateUserResponse)(nil),            // 12: chatto.admin.v1.UpdateUserResponse
	(*SetUserPasswordRequest)(nil),        // 13: chatto.admin.v1.SetUserPasswordRequest
	(*SetUserPasswordResponse)(nil),       // 14: chatto.admin.v1.SetUserPasswordResponse
	(*ClearUsernameCooldownRequest)(nil),  // 15: chatto.admin.v1.ClearUsernameCooldownRequest
	(*ClearUsernameCooldownResponse)(nil), // 16: chatto.admin.v1.ClearUsernameCooldownResponse
	(*DeleteUserRequest)(nil),             // 17: chatto.admin.v1.DeleteUserRequest
	(*DeleteUserResponse)(nil),            // 18: chatto.admin.v1.DeleteUserResponse
	(*timestamppb.Timestamp)(nil),         // 19: google.protobuf.Timestamp
	(*v1.User)(nil),                       // 20: chatto.api.v1.User
	(*v1.PageRequest)(nil),                // 21: chatto.api.v1.PageRequest
	(*v1.Role)(nil),                       // 22: chatto.api.v1.Role
	(*v1.PageInfo)(nil),                   // 23: chatto.api.v1.PageInfo
	(*AdminRole)(nil),                     // 24: chatto.admin.v1.AdminRole
}
var file_chatto_admin_v1_members_proto_depIdxs = []int32{
	19, // 0: chatto.admin.v1.AdminMember.created_at:type_name -> google.protobuf.Timestamp
	19, // 1: chatto.admin.v1.AdminMember.last_login_change:type_name -> google.protobuf.Timestamp
	20, // 2: chatto.admin.v1.AdminMember.user:type_name -> chatto.api.v1.User
	21, // 3: chatto.admin.v1.ListMembersRequest.page:type_name -> chatto.api.v1.PageRequest
	0,  // 4: chatto.admin.v1.ListMembersResponse.users:type_name -> chatto.admin.v1.AdminMember
	22, // 5: chatto.admin.v1.ListMembersResponse.roles:type_name -> chatto.api.v1.Role
	23, // 6: chatto.admin.v1.ListMembersResponse.page:type_name -> chatto.api.v1.PageInfo
	0,  // 7: chatto.admin.v1.GetMemberResponse.member:type_name -> chatto.admin.v1.AdminMember
	24, // 8: chatto.admin.v1.GetMemberResponse.roles:type_name -> chatto.admin.v1.AdminRole
	0,  // 9: chatto.admin.v1.AssignRoleResponse.member:type_name -> chatto.admin.v1.AdminMember
	0,  // 10: chatto.admin.v1.RevokeRoleResponse.member:type_name -> chatto.admin.v1.AdminMember
	20, // 11: chatto.admin.v1.UpdateUserResponse.user:type_name -> chatto.api.v1.User
	0,  // 12: chatto.admin.v1.UpdateUserResponse.member:type_name -> chatto.admin.v1.AdminMember
	3,  // 13: chatto.admin.v1.AdminMemberService.ListMembers:input_type -> chatto.admin.v1.ListMembersRequest
	5,  // 14: chatto.admin.v1.AdminMemberService.GetMember:input_type -> chatto.admin.v1.GetMemberRequest
	7,  // 15: chatto.admin.v1.AdminMemberService.AssignRole:input_type -> chatto.admin.v1.AssignRoleRequest
	9,  // 16: chatto.admin.v1.AdminMemberService.RevokeRole:input_type -> chatto.admin.v1.RevokeRoleRequest
	11, // 17: chatto.admin.v1.AdminMemberService.UpdateUser:input_type -> chatto.admin.v1.UpdateUserRequest
	13, // 18: chatto.admin.v1.AdminMemberService.SetUserPassword:input_type -> chatto.admin.v1.SetUserPasswordRequest
	15, // 19: chatto.admin.v1.AdminMemberService.ClearUsernameCooldown:input_type -> chatto.admin.v1.ClearUsernameCooldownRequest
	17, // 20: chatto.admin.v1.AdminMemberService.DeleteUser:input_type -> chatto.admin.v1.DeleteUserRequest
	4,  // 21: chatto.admin.v1.AdminMemberService.ListMembers:output_type -> chatto.admin.v1.ListMembersResponse
	6,  // 22: chatto.admin.v1.AdminMemberService.GetMember:output_type -> chatto.admin.v1.GetMemberResponse
	8,  // 23: chatto.admin.v1.AdminMemberService.AssignRole:output_type -> chatto.admin.v1.AssignRoleResponse
	10, // 24: chatto.admin.v1.AdminMemberService.RevokeRole:output_type -> chatto.admin.v1.RevokeRoleResponse
	12, // 25: chatto.admin.v1.AdminMemberService.UpdateUser:output_type -> chatto.admin.v1.UpdateUserResponse
	14, // 26: chatto.admin.v1.AdminMemberService.SetUserPassword:output_type -> chatto.admin.v1.SetUserPasswordResponse
	16, // 27: chatto.admin.v1.AdminMemberService.ClearUsernameCooldown:output_type -> chatto.admin.v1.ClearUsernameCooldownResponse
	18, // 28: chatto.admin.v1.AdminMemberService.DeleteUser:output_type -> chatto.admin.v1.DeleteUserResponse
	21, // [21:29] is the sub-list for method output_type
	13, // [13:21] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_chatto_admin_v1_members_proto_init() }
func file_chatto_admin_v1_members_proto_init() {
	if File_chatto_admin_v1_members_proto != nil {
		return
	}
	file_chatto_admin_v1_roles_proto_init()
	file_chatto_admin_v1_members_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_admin_v1_members_proto_rawDesc), len(file_chatto_admin_v1_members_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatto_admin_v1_members_proto_goTypes,
		DependencyIndexes: file_chatto_admin_v1_members_proto_depIdxs,
		MessageInfos:      file_chatto_admin_v1_members_proto_msgTypes,
	}.Build()
	File_chatto_admin_v1_members_proto = out.File
	file_chatto_admin_v1_members_proto_goTypes = nil
	file_chatto_admin_v1_members_proto_depIdxs = nil
}
