// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/core/v1/identity_claim_events.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdentityClaimKind int32

const (
	IdentityClaimKind_IDENTITY_CLAIM_KIND_UNSPECIFIED  IdentityClaimKind = 0
	IdentityClaimKind_IDENTITY_CLAIM_KIND_LOGIN        IdentityClaimKind = 1
	IdentityClaimKind_IDENTITY_CLAIM_KIND_EMAIL        IdentityClaimKind = 2
	IdentityClaimKind_IDENTITY_CLAIM_KIND_OIDC_SUBJECT IdentityClaimKind = 3
)

// Enum value maps for IdentityClaimKind.
var (
	IdentityClaimKind_name = map[int32]string{
		0: "IDENTITY_CLAIM_KIND_UNSPECIFIED",
		1: "IDENTITY_CLAIM_KIND_LOGIN",
		2: "IDENTITY_CLAIM_KIND_EMAIL",
		3: "IDENTITY_CLAIM_KIND_OIDC_SUBJECT",
	}
	IdentityClaimKind_value = map[string]int32{
		"IDENTITY_CLAIM_KIND_UNSPECIFIED":  0,
		"IDENTITY_CLAIM_KIND_LOGIN":        1,
		"IDENTITY_CLAIM_KIND_EMAIL":        2,
		"IDENTITY_CLAIM_KIND_OIDC_SUBJECT": 3,
	}
)

func (x IdentityClaimKind) Enum() *IdentityClaimKind {
	p := new(IdentityClaimKind)
	*p = x
	return p
}

func (x IdentityClaimKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentityClaimKind) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_core_v1_identity_claim_events_proto_enumTypes[0].Descriptor()
}

func (IdentityClaimKind) Type() protoreflect.EnumType {
	return &file_chatto_core_v1_identity_claim_events_proto_enumTypes[0]
}

func (x IdentityClaimKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdentityClaimKind.Descriptor instead.
func (IdentityClaimKind) EnumDescriptor() ([]byte, []int) {
	return file_chatto_core_v1_identity_claim_events_proto_rawDescGZIP(), []int{0}
}

type IdentityClaimedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClaimId       string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	OwnerUserId   string                 `protobuf:"bytes,2,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	Kind          IdentityClaimKind      `protobuf:"varint,3,opt,name=kind,proto3,enum=chatto.core.v1.IdentityClaimKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityClaimedEvent) Reset() {
	*x = IdentityClaimedEvent{}
	mi := &file_chatto_core_v1_identity_claim_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityClaimedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityClaimedEvent) ProtoMessage() {}

func (x *IdentityClaimedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_identity_claim_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityClaimedEvent.ProtoReflect.Descriptor instead.
func (*IdentityClaimedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_identity_claim_events_proto_rawDescGZIP(), []int{0}
}

func (x *IdentityClaimedEvent) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *IdentityClaimedEvent) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *IdentityClaimedEvent) GetKind() IdentityClaimKind {
	if x != nil {
		return x.Kind
	}
	return IdentityClaimKind_IDENTITY_CLAIM_KIND_UNSPECIFIED
}

type IdentityClaimReleasedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClaimId       string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	OwnerUserId   string                 `protobuf:"bytes,2,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	Kind          IdentityClaimKind      `protobuf:"varint,3,opt,name=kind,proto3,enum=chatto.core.v1.IdentityClaimKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityClaimReleasedEvent) Reset() {
	*x = IdentityClaimReleasedEvent{}
	mi := &file_chatto_core_v1_identity_claim_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityClaimReleasedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityClaimReleasedEvent) ProtoMessage() {}

func (x *IdentityClaimReleasedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_identity_claim_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityClaimReleasedEvent.ProtoReflect.Descriptor instead.
func (*IdentityClaimReleasedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_identity_claim_events_proto_rawDescGZIP(), []int{1}
}

func (x *IdentityClaimReleasedEvent) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *IdentityClaimReleasedEvent) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *IdentityClaimReleasedEvent) GetKind() IdentityClaimKind {
	if x != nil {
		return x.Kind
	}
	return IdentityClaimKind_IDENTITY_CLAIM_KIND_UNSPECIFIED
}

var File_chatto_core_v1_identity_claim_events_proto protoreflect.FileDescriptor

const file_chatto_core_v1_identity_claim_events_proto_rawDesc = "" +
	"\n" +
	"*chatto/core/v1/identity_claim_events.proto\x12\x0echatto.core.v1\"\x8c\x01\n" +
	"\x14IdentityClaimedEvent\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\x12\"\n" +
	"\rowner_user_id\x18\x02 \x01(\tR\vownerUserId\x125\n" +
	"\x04kind\x18\x03 \x01(\x0e2!.chatto.core.v1.IdentityClaimKindR\x04kind\"\x92\x01\n" +
	"\x1aIdentityClaimReleasedEvent\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\x12\"\n" +
	"\rowner_user_id\x18\x02 \x01(\tR\vownerUserId\x125\n" +
	"\x04kind\x18\x03 \x01(\x0e2!.chatto.core.v1.IdentityClaimKindR\x04kind*\x9c\x01\n" +
	"\x11IdentityClaimKind\x12#\n" +
	"\x1fIDENTITY_CLAIM_KIND_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19IDENTITY_CLAIM_KIND_LOGIN\x10\x01\x12\x1d\n" +
	"\x19IDENTITY_CLAIM_KIND_EMAIL\x10\x02\x12$\n" +
	" IDENTITY_CLAIM_KIND_OIDC_SUBJECT\x10\x03B\xbb\x01\n" +
	"\x12com.chatto.core.v1B\x18IdentityClaimEventsProtoP\x01Z1hmans.de/chatto/internal/pb/chatto/core/v1;corev1\xa2\x02\x03CCX\xaa\x02\x0eChatto.Core.V1\xca\x02\x0eChatto\\Core\\V1\xe2\x02\x1aChatto\\Core\\V1\\GPBMetadata\xea\x02\x10Chatto::Core::V1b\x06proto3"

var (
	file_chatto_core_v1_identity_claim_events_proto_rawDescOnce sync.Once
	file_chatto_core_v1_identity_claim_events_proto_rawDescData []byte
)

func file_chatto_core_v1_identity_claim_events_proto_rawDescGZIP() []byte {
	file_chatto_core_v1_identity_claim_events_proto_rawDescOnce.Do(func() {
		file_chatto_core_v1_identity_claim_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_core_v1_identity_claim_events_proto_rawDesc), len(file_chatto_core_v1_identity_claim_events_proto_rawDesc)))
	})
	return file_chatto_core_v1_identity_claim_events_proto_rawDescData
}

var file_chatto_core_v1_identity_claim_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chatto_core_v1_identity_claim_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chatto_core_v1_identity_claim_events_proto_goTypes = []any{
	(IdentityClaimKind)(0),             // 0: chatto.core.v1.IdentityClaimKind
	(*IdentityClaimedEvent)(nil),       // 1: chatto.core.v1.IdentityClaimedEvent
	(*IdentityClaimReleasedEvent)(nil), // 2: chatto.core.v1.IdentityClaimReleasedEvent
}
var file_chatto_core_v1_identity_claim_events_proto_depIdxs = []int32{
	0, // 0: chatto.core.v1.IdentityClaimedEvent.kind:type_name -> chatto.core.v1.IdentityClaimKind
	0, // 1: chatto.core.v1.IdentityClaimReleasedEvent.kind:type_name -> chatto.core.v1.IdentityClaimKind
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_chatto_core_v1_identity_claim_events_proto_init() }
func file_chatto_core_v1_identity_claim_events_proto_init() {
	if File_chatto_core_v1_identity_claim_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_core_v1_identity_claim_events_proto_rawDesc), len(file_chatto_core_v1_identity_claim_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatto_core_v1_identity_claim_events_proto_goTypes,
		DependencyIndexes: file_chatto_core_v1_identity_claim_events_proto_depIdxs,
		EnumInfos:         file_chatto_core_v1_identity_claim_events_proto_enumTypes,
		MessageInfos:      file_chatto_core_v1_identity_claim_events_proto_msgTypes,
	}.Build()
	File_chatto_core_v1_identity_claim_events_proto = out.File
	file_chatto_core_v1_identity_claim_events_proto_goTypes = nil
	file_chatto_core_v1_identity_claim_events_proto_depIdxs = nil
}
