// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/core/v1/moderation_events.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RoomMemberBannedEvent records a moderator banning a user from a channel room.
// The Event envelope actor_id is the moderator. The payload user_id is the
// target. Absence of expires_at means the ban is indefinite.
type RoomMemberBannedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomMemberBannedEvent) Reset() {
	*x = RoomMemberBannedEvent{}
	mi := &file_chatto_core_v1_moderation_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomMemberBannedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMemberBannedEvent) ProtoMessage() {}

func (x *RoomMemberBannedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_moderation_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMemberBannedEvent.ProtoReflect.Descriptor instead.
func (*RoomMemberBannedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_moderation_events_proto_rawDescGZIP(), []int{0}
}

func (x *RoomMemberBannedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomMemberBannedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RoomMemberBannedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RoomMemberBannedEvent) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// RoomMemberUnbannedEvent records a moderator removing a room ban.
// The Event envelope actor_id is the moderator. The payload user_id is the
// target.
type RoomMemberUnbannedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomMemberUnbannedEvent) Reset() {
	*x = RoomMemberUnbannedEvent{}
	mi := &file_chatto_core_v1_moderation_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomMemberUnbannedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMemberUnbannedEvent) ProtoMessage() {}

func (x *RoomMemberUnbannedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_moderation_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMemberUnbannedEvent.ProtoReflect.Descriptor instead.
func (*RoomMemberUnbannedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_moderation_events_proto_rawDescGZIP(), []int{1}
}

func (x *RoomMemberUnbannedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomMemberUnbannedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RoomMemberUnbannedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_chatto_core_v1_moderation_events_proto protoreflect.FileDescriptor

const file_chatto_core_v1_moderation_events_proto_rawDesc = "" +
	"\n" +
	"&chatto/core/v1/moderation_events.proto\x12\x0echatto.core.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x01\n" +
	"\x15RoomMemberBannedEvent\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12>\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\texpiresAt\x88\x01\x01B\r\n" +
	"\v_expires_at\"c\n" +
	"\x17RoomMemberUnbannedEvent\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reasonB\xb8\x01\n" +
	"\x12com.chatto.core.v1B\x15ModerationEventsProtoP\x01Z1hmans.de/chatto/internal/pb/chatto/core/v1;corev1\xa2\x02\x03CCX\xaa\x02\x0eChatto.Core.V1\xca\x02\x0eChatto\\Core\\V1\xe2\x02\x1aChatto\\Core\\V1\\GPBMetadata\xea\x02\x10Chatto::Core::V1b\x06proto3"

var (
	file_chatto_core_v1_moderation_events_proto_rawDescOnce sync.Once
	file_chatto_core_v1_moderation_events_proto_rawDescData []byte
)

func file_chatto_core_v1_moderation_events_proto_rawDescGZIP() []byte {
	file_chatto_core_v1_moderation_events_proto_rawDescOnce.Do(func() {
		file_chatto_core_v1_moderation_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_core_v1_moderation_events_proto_rawDesc), len(file_chatto_core_v1_moderation_events_proto_rawDesc)))
	})
	return file_chatto_core_v1_moderation_events_proto_rawDescData
}

var file_chatto_core_v1_moderation_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chatto_core_v1_moderation_events_proto_goTypes = []any{
	(*RoomMemberBannedEvent)(nil),   // 0: chatto.core.v1.RoomMemberBannedEvent
	(*RoomMemberUnbannedEvent)(nil), // 1: chatto.core.v1.RoomMemberUnbannedEvent
	(*timestamppb.Timestamp)(nil),   // 2: google.protobuf.Timestamp
}
var file_chatto_core_v1_moderation_events_proto_depIdxs = []int32{
	2, // 0: chatto.core.v1.RoomMemberBannedEvent.expires_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chatto_core_v1_moderation_events_proto_init() }
func file_chatto_core_v1_moderation_events_proto_init() {
	if File_chatto_core_v1_moderation_events_proto != nil {
		return
	}
	file_chatto_core_v1_moderation_events_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_core_v1_moderation_events_proto_rawDesc), len(file_chatto_core_v1_moderation_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatto_core_v1_moderation_events_proto_goTypes,
		DependencyIndexes: file_chatto_core_v1_moderation_events_proto_depIdxs,
		MessageInfos:      file_chatto_core_v1_moderation_events_proto_msgTypes,
	}.Build()
	File_chatto_core_v1_moderation_events_proto = out.File
	file_chatto_core_v1_moderation_events_proto_goTypes = nil
	file_chatto_core_v1_moderation_events_proto_depIdxs = nil
}
