// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file chatto/api/v1/room_timeline.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from enum chatto.api.v1.RoomTimelineVideoProcessingStatus
 */
export enum RoomTimelineVideoProcessingStatus {
  /**
   * @generated from enum value: ROOM_TIMELINE_VIDEO_PROCESSING_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ROOM_TIMELINE_VIDEO_PROCESSING_STATUS_PROCESSING = 1;
   */
  PROCESSING = 1,

  /**
   * @generated from enum value: ROOM_TIMELINE_VIDEO_PROCESSING_STATUS_COMPLETED = 2;
   */
  COMPLETED = 2,

  /**
   * @generated from enum value: ROOM_TIMELINE_VIDEO_PROCESSING_STATUS_FAILED = 3;
   */
  FAILED = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(RoomTimelineVideoProcessingStatus)
proto3.util.setEnumType(RoomTimelineVideoProcessingStatus, "chatto.api.v1.RoomTimelineVideoProcessingStatus", [
  { no: 0, name: "ROOM_TIMELINE_VIDEO_PROCESSING_STATUS_UNSPECIFIED" },
  { no: 1, name: "ROOM_TIMELINE_VIDEO_PROCESSING_STATUS_PROCESSING" },
  { no: 2, name: "ROOM_TIMELINE_VIDEO_PROCESSING_STATUS_COMPLETED" },
  { no: 3, name: "ROOM_TIMELINE_VIDEO_PROCESSING_STATUS_FAILED" },
]);

/**
 * @generated from message chatto.api.v1.RoomTimelineUser
 */
export class RoomTimelineUser extends Message<RoomTimelineUser> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string login = 2;
   */
  login = "";

  /**
   * @generated from field: string display_name = 3;
   */
  displayName = "";

  /**
   * @generated from field: bool deleted = 4;
   */
  deleted = false;

  /**
   * @generated from field: string avatar_url = 5;
   */
  avatarUrl = "";

  constructor(data?: PartialMessage<RoomTimelineUser>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.RoomTimelineUser";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "login", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "deleted", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "avatar_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoomTimelineUser {
    return new RoomTimelineUser().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoomTimelineUser {
    return new RoomTimelineUser().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoomTimelineUser {
    return new RoomTimelineUser().fromJsonString(jsonString, options);
  }

  static equals(a: RoomTimelineUser | PlainMessage<RoomTimelineUser> | undefined, b: RoomTimelineUser | PlainMessage<RoomTimelineUser> | undefined): boolean {
    return proto3.util.equals(RoomTimelineUser, a, b);
  }
}

/**
 * @generated from message chatto.api.v1.RoomTimelineIncludes
 */
export class RoomTimelineIncludes extends Message<RoomTimelineIncludes> {
  /**
   * @generated from field: map<string, chatto.api.v1.RoomTimelineUser> users = 1;
   */
  users: { [key: string]: RoomTimelineUser } = {};

  constructor(data?: PartialMessage<RoomTimelineIncludes>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.RoomTimelineIncludes";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "users", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: RoomTimelineUser} },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoomTimelineIncludes {
    return new RoomTimelineIncludes().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoomTimelineIncludes {
    return new RoomTimelineIncludes().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoomTimelineIncludes {
    return new RoomTimelineIncludes().fromJsonString(jsonString, options);
  }

  static equals(a: RoomTimelineIncludes | PlainMessage<RoomTimelineIncludes> | undefined, b: RoomTimelineIncludes | PlainMessage<RoomTimelineIncludes> | undefined): boolean {
    return proto3.util.equals(RoomTimelineIncludes, a, b);
  }
}

/**
 * @generated from message chatto.api.v1.RoomTimelineAssetUrl
 */
export class RoomTimelineAssetUrl extends Message<RoomTimelineAssetUrl> {
  /**
   * @generated from field: string url = 1;
   */
  url = "";

  /**
   * @generated from field: google.protobuf.Timestamp expires_at = 2;
   */
  expiresAt?: Timestamp;

  constructor(data?: PartialMessage<RoomTimelineAssetUrl>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.RoomTimelineAssetUrl";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "expires_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoomTimelineAssetUrl {
    return new RoomTimelineAssetUrl().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoomTimelineAssetUrl {
    return new RoomTimelineAssetUrl().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoomTimelineAssetUrl {
    return new RoomTimelineAssetUrl().fromJsonString(jsonString, options);
  }

  static equals(a: RoomTimelineAssetUrl | PlainMessage<RoomTimelineAssetUrl> | undefined, b: RoomTimelineAssetUrl | PlainMessage<RoomTimelineAssetUrl> | undefined): boolean {
    return proto3.util.equals(RoomTimelineAssetUrl, a, b);
  }
}

/**
 * @generated from message chatto.api.v1.RoomTimelineVideoVariant
 */
export class RoomTimelineVideoVariant extends Message<RoomTimelineVideoVariant> {
  /**
   * @generated from field: string quality = 1;
   */
  quality = "";

  /**
   * @generated from field: int32 width = 2;
   */
  width = 0;

  /**
   * @generated from field: int32 height = 3;
   */
  height = 0;

  /**
   * @generated from field: int64 size = 4;
   */
  size = protoInt64.zero;

  /**
   * @generated from field: chatto.api.v1.RoomTimelineAssetUrl asset_url = 5;
   */
  assetUrl?: RoomTimelineAssetUrl;

  constructor(data?: PartialMessage<RoomTimelineVideoVariant>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.RoomTimelineVideoVariant";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "quality", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "width", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "height", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "size", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "asset_url", kind: "message", T: RoomTimelineAssetUrl },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoomTimelineVideoVariant {
    return new RoomTimelineVideoVariant().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoomTimelineVideoVariant {
    return new RoomTimelineVideoVariant().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoomTimelineVideoVariant {
    return new RoomTimelineVideoVariant().fromJsonString(jsonString, options);
  }

  static equals(a: RoomTimelineVideoVariant | PlainMessage<RoomTimelineVideoVariant> | undefined, b: RoomTimelineVideoVariant | PlainMessage<RoomTimelineVideoVariant> | undefined): boolean {
    return proto3.util.equals(RoomTimelineVideoVariant, a, b);
  }
}

/**
 * @generated from message chatto.api.v1.RoomTimelineVideoProcessing
 */
export class RoomTimelineVideoProcessing extends Message<RoomTimelineVideoProcessing> {
  /**
   * @generated from field: chatto.api.v1.RoomTimelineVideoProcessingStatus status = 1;
   */
  status = RoomTimelineVideoProcessingStatus.UNSPECIFIED;

  /**
   * @generated from field: int64 duration_ms = 2;
   */
  durationMs = protoInt64.zero;

  /**
   * @generated from field: int32 width = 3;
   */
  width = 0;

  /**
   * @generated from field: int32 height = 4;
   */
  height = 0;

  /**
   * @generated from field: bool source_available = 5;
   */
  sourceAvailable = false;

  /**
   * @generated from field: string reason_code = 6;
   */
  reasonCode = "";

  /**
   * @generated from field: chatto.api.v1.RoomTimelineAssetUrl thumbnail_asset_url = 7;
   */
  thumbnailAssetUrl?: RoomTimelineAssetUrl;

  /**
   * @generated from field: repeated chatto.api.v1.RoomTimelineVideoVariant variants = 8;
   */
  variants: RoomTimelineVideoVariant[] = [];

  constructor(data?: PartialMessage<RoomTimelineVideoProcessing>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.RoomTimelineVideoProcessing";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "status", kind: "enum", T: proto3.getEnumType(RoomTimelineVideoProcessingStatus) },
    { no: 2, name: "duration_ms", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "width", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "height", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "source_available", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "reason_code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "thumbnail_asset_url", kind: "message", T: RoomTimelineAssetUrl },
    { no: 8, name: "variants", kind: "message", T: RoomTimelineVideoVariant, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoomTimelineVideoProcessing {
    return new RoomTimelineVideoProcessing().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoomTimelineVideoProcessing {
    return new RoomTimelineVideoProcessing().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoomTimelineVideoProcessing {
    return new RoomTimelineVideoProcessing().fromJsonString(jsonString, options);
  }

  static equals(a: RoomTimelineVideoProcessing | PlainMessage<RoomTimelineVideoProcessing> | undefined, b: RoomTimelineVideoProcessing | PlainMessage<RoomTimelineVideoProcessing> | undefined): boolean {
    return proto3.util.equals(RoomTimelineVideoProcessing, a, b);
  }
}

/**
 * @generated from message chatto.api.v1.RoomTimelineAttachment
 */
export class RoomTimelineAttachment extends Message<RoomTimelineAttachment> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string filename = 2;
   */
  filename = "";

  /**
   * @generated from field: string content_type = 3;
   */
  contentType = "";

  /**
   * @generated from field: int32 width = 4;
   */
  width = 0;

  /**
   * @generated from field: int32 height = 5;
   */
  height = 0;

  /**
   * @generated from field: chatto.api.v1.RoomTimelineAssetUrl asset_url = 6;
   */
  assetUrl?: RoomTimelineAssetUrl;

  /**
   * @generated from field: chatto.api.v1.RoomTimelineAssetUrl thumbnail_asset_url = 7;
   */
  thumbnailAssetUrl?: RoomTimelineAssetUrl;

  /**
   * @generated from field: chatto.api.v1.RoomTimelineVideoProcessing video_processing = 8;
   */
  videoProcessing?: RoomTimelineVideoProcessing;

  constructor(data?: PartialMessage<RoomTimelineAttachment>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.RoomTimelineAttachment";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "filename", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "content_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "width", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "height", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "asset_url", kind: "message", T: RoomTimelineAssetUrl },
    { no: 7, name: "thumbnail_asset_url", kind: "message", T: RoomTimelineAssetUrl },
    { no: 8, name: "video_processing", kind: "message", T: RoomTimelineVideoProcessing },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoomTimelineAttachment {
    return new RoomTimelineAttachment().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoomTimelineAttachment {
    return new RoomTimelineAttachment().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoomTimelineAttachment {
    return new RoomTimelineAttachment().fromJsonString(jsonString, options);
  }

  static equals(a: RoomTimelineAttachment | PlainMessage<RoomTimelineAttachment> | undefined, b: RoomTimelineAttachment | PlainMessage<RoomTimelineAttachment> | undefined): boolean {
    return proto3.util.equals(RoomTimelineAttachment, a, b);
  }
}

/**
 * @generated from message chatto.api.v1.RoomTimelineLinkPreview
 */
export class RoomTimelineLinkPreview extends Message<RoomTimelineLinkPreview> {
  /**
   * @generated from field: string url = 1;
   */
  url = "";

  /**
   * @generated from field: string title = 2;
   */
  title = "";

  /**
   * @generated from field: string description = 3;
   */
  description = "";

  /**
   * @generated from field: string site_name = 4;
   */
  siteName = "";

  /**
   * @generated from field: string image_url = 5;
   */
  imageUrl = "";

  /**
   * @generated from field: string embed_type = 6;
   */
  embedType = "";

  /**
   * @generated from field: string embed_id = 7;
   */
  embedId = "";

  constructor(data?: PartialMessage<RoomTimelineLinkPreview>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.RoomTimelineLinkPreview";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "site_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "image_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "embed_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "embed_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoomTimelineLinkPreview {
    return new RoomTimelineLinkPreview().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoomTimelineLinkPreview {
    return new RoomTimelineLinkPreview().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoomTimelineLinkPreview {
    return new RoomTimelineLinkPreview().fromJsonString(jsonString, options);
  }

  static equals(a: RoomTimelineLinkPreview | PlainMessage<RoomTimelineLinkPreview> | undefined, b: RoomTimelineLinkPreview | PlainMessage<RoomTimelineLinkPreview> | undefined): boolean {
    return proto3.util.equals(RoomTimelineLinkPreview, a, b);
  }
}

/**
 * @generated from message chatto.api.v1.RoomTimelineReactionSummary
 */
export class RoomTimelineReactionSummary extends Message<RoomTimelineReactionSummary> {
  /**
   * @generated from field: string emoji = 1;
   */
  emoji = "";

  /**
   * @generated from field: int32 count = 2;
   */
  count = 0;

  /**
   * @generated from field: bool has_reacted = 3;
   */
  hasReacted = false;

  /**
   * @generated from field: repeated string user_ids = 4;
   */
  userIds: string[] = [];

  constructor(data?: PartialMessage<RoomTimelineReactionSummary>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.RoomTimelineReactionSummary";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "emoji", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "has_reacted", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "user_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoomTimelineReactionSummary {
    return new RoomTimelineReactionSummary().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoomTimelineReactionSummary {
    return new RoomTimelineReactionSummary().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoomTimelineReactionSummary {
    return new RoomTimelineReactionSummary().fromJsonString(jsonString, options);
  }

  static equals(a: RoomTimelineReactionSummary | PlainMessage<RoomTimelineReactionSummary> | undefined, b: RoomTimelineReactionSummary | PlainMessage<RoomTimelineReactionSummary> | undefined): boolean {
    return proto3.util.equals(RoomTimelineReactionSummary, a, b);
  }
}

/**
 * @generated from message chatto.api.v1.RoomTimelineMessagePosted
 */
export class RoomTimelineMessagePosted extends Message<RoomTimelineMessagePosted> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * @generated from field: string body = 2;
   */
  body = "";

  /**
   * @generated from field: bool body_present = 3;
   */
  bodyPresent = false;

  /**
   * @generated from field: repeated chatto.api.v1.RoomTimelineAttachment attachments = 4;
   */
  attachments: RoomTimelineAttachment[] = [];

  /**
   * @generated from field: chatto.api.v1.RoomTimelineLinkPreview link_preview = 5;
   */
  linkPreview?: RoomTimelineLinkPreview;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 6;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: string in_reply_to = 7;
   */
  inReplyTo = "";

  /**
   * @generated from field: string thread_root_event_id = 8;
   */
  threadRootEventId = "";

  /**
   * @generated from field: string echo_of_event_id = 9;
   */
  echoOfEventId = "";

  /**
   * @generated from field: string echo_from_thread_root_event_id = 10;
   */
  echoFromThreadRootEventId = "";

  /**
   * @generated from field: string channel_echo_event_id = 11;
   */
  channelEchoEventId = "";

  /**
   * @generated from field: int32 reply_count = 12;
   */
  replyCount = 0;

  /**
   * @generated from field: google.protobuf.Timestamp last_reply_at = 13;
   */
  lastReplyAt?: Timestamp;

  /**
   * @generated from field: repeated string thread_participant_user_ids = 14;
   */
  threadParticipantUserIds: string[] = [];

  /**
   * @generated from field: bool viewer_is_following_thread = 15;
   */
  viewerIsFollowingThread = false;

  /**
   * @generated from field: bool viewer_is_following_thread_present = 16;
   */
  viewerIsFollowingThreadPresent = false;

  /**
   * @generated from field: repeated chatto.api.v1.RoomTimelineReactionSummary reactions = 17;
   */
  reactions: RoomTimelineReactionSummary[] = [];

  constructor(data?: PartialMessage<RoomTimelineMessagePosted>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.RoomTimelineMessagePosted";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "body", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "body_present", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "attachments", kind: "message", T: RoomTimelineAttachment, repeated: true },
    { no: 5, name: "link_preview", kind: "message", T: RoomTimelineLinkPreview },
    { no: 6, name: "updated_at", kind: "message", T: Timestamp },
    { no: 7, name: "in_reply_to", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "thread_root_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "echo_of_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "echo_from_thread_root_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "channel_echo_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "reply_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 13, name: "last_reply_at", kind: "message", T: Timestamp },
    { no: 14, name: "thread_participant_user_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 15, name: "viewer_is_following_thread", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 16, name: "viewer_is_following_thread_present", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 17, name: "reactions", kind: "message", T: RoomTimelineReactionSummary, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoomTimelineMessagePosted {
    return new RoomTimelineMessagePosted().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoomTimelineMessagePosted {
    return new RoomTimelineMessagePosted().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoomTimelineMessagePosted {
    return new RoomTimelineMessagePosted().fromJsonString(jsonString, options);
  }

  static equals(a: RoomTimelineMessagePosted | PlainMessage<RoomTimelineMessagePosted> | undefined, b: RoomTimelineMessagePosted | PlainMessage<RoomTimelineMessagePosted> | undefined): boolean {
    return proto3.util.equals(RoomTimelineMessagePosted, a, b);
  }
}

/**
 * @generated from message chatto.api.v1.RoomTimelineRoomEvent
 */
export class RoomTimelineRoomEvent extends Message<RoomTimelineRoomEvent> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  constructor(data?: PartialMessage<RoomTimelineRoomEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.RoomTimelineRoomEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoomTimelineRoomEvent {
    return new RoomTimelineRoomEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoomTimelineRoomEvent {
    return new RoomTimelineRoomEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoomTimelineRoomEvent {
    return new RoomTimelineRoomEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RoomTimelineRoomEvent | PlainMessage<RoomTimelineRoomEvent> | undefined, b: RoomTimelineRoomEvent | PlainMessage<RoomTimelineRoomEvent> | undefined): boolean {
    return proto3.util.equals(RoomTimelineRoomEvent, a, b);
  }
}

/**
 * @generated from message chatto.api.v1.RoomTimelineEvent
 */
export class RoomTimelineEvent extends Message<RoomTimelineEvent> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 2;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: string actor_id = 3;
   */
  actorId = "";

  /**
   * @generated from oneof chatto.api.v1.RoomTimelineEvent.event
   */
  event: {
    /**
     * @generated from field: chatto.api.v1.RoomTimelineMessagePosted message_posted = 10;
     */
    value: RoomTimelineMessagePosted;
    case: "messagePosted";
  } | {
    /**
     * @generated from field: chatto.api.v1.RoomTimelineRoomEvent room_created = 20;
     */
    value: RoomTimelineRoomEvent;
    case: "roomCreated";
  } | {
    /**
     * @generated from field: chatto.api.v1.RoomTimelineRoomEvent room_updated = 21;
     */
    value: RoomTimelineRoomEvent;
    case: "roomUpdated";
  } | {
    /**
     * @generated from field: chatto.api.v1.RoomTimelineRoomEvent room_deleted = 22;
     */
    value: RoomTimelineRoomEvent;
    case: "roomDeleted";
  } | {
    /**
     * @generated from field: chatto.api.v1.RoomTimelineRoomEvent room_archived = 23;
     */
    value: RoomTimelineRoomEvent;
    case: "roomArchived";
  } | {
    /**
     * @generated from field: chatto.api.v1.RoomTimelineRoomEvent room_unarchived = 24;
     */
    value: RoomTimelineRoomEvent;
    case: "roomUnarchived";
  } | {
    /**
     * @generated from field: chatto.api.v1.RoomTimelineRoomEvent user_joined_room = 30;
     */
    value: RoomTimelineRoomEvent;
    case: "userJoinedRoom";
  } | {
    /**
     * @generated from field: chatto.api.v1.RoomTimelineRoomEvent user_left_room = 31;
     */
    value: RoomTimelineRoomEvent;
    case: "userLeftRoom";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<RoomTimelineEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.RoomTimelineEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "created_at", kind: "message", T: Timestamp },
    { no: 3, name: "actor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "message_posted", kind: "message", T: RoomTimelineMessagePosted, oneof: "event" },
    { no: 20, name: "room_created", kind: "message", T: RoomTimelineRoomEvent, oneof: "event" },
    { no: 21, name: "room_updated", kind: "message", T: RoomTimelineRoomEvent, oneof: "event" },
    { no: 22, name: "room_deleted", kind: "message", T: RoomTimelineRoomEvent, oneof: "event" },
    { no: 23, name: "room_archived", kind: "message", T: RoomTimelineRoomEvent, oneof: "event" },
    { no: 24, name: "room_unarchived", kind: "message", T: RoomTimelineRoomEvent, oneof: "event" },
    { no: 30, name: "user_joined_room", kind: "message", T: RoomTimelineRoomEvent, oneof: "event" },
    { no: 31, name: "user_left_room", kind: "message", T: RoomTimelineRoomEvent, oneof: "event" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoomTimelineEvent {
    return new RoomTimelineEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoomTimelineEvent {
    return new RoomTimelineEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoomTimelineEvent {
    return new RoomTimelineEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RoomTimelineEvent | PlainMessage<RoomTimelineEvent> | undefined, b: RoomTimelineEvent | PlainMessage<RoomTimelineEvent> | undefined): boolean {
    return proto3.util.equals(RoomTimelineEvent, a, b);
  }
}

/**
 * @generated from message chatto.api.v1.RoomTimelinePage
 */
export class RoomTimelinePage extends Message<RoomTimelinePage> {
  /**
   * @generated from field: repeated chatto.api.v1.RoomTimelineEvent events = 1;
   */
  events: RoomTimelineEvent[] = [];

  /**
   * @generated from field: string start_cursor = 2;
   */
  startCursor = "";

  /**
   * @generated from field: string end_cursor = 3;
   */
  endCursor = "";

  /**
   * @generated from field: bool has_older = 4;
   */
  hasOlder = false;

  /**
   * @generated from field: bool has_newer = 5;
   */
  hasNewer = false;

  /**
   * @generated from field: chatto.api.v1.RoomTimelineIncludes includes = 6;
   */
  includes?: RoomTimelineIncludes;

  constructor(data?: PartialMessage<RoomTimelinePage>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.RoomTimelinePage";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "events", kind: "message", T: RoomTimelineEvent, repeated: true },
    { no: 2, name: "start_cursor", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "end_cursor", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "has_older", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "has_newer", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "includes", kind: "message", T: RoomTimelineIncludes },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoomTimelinePage {
    return new RoomTimelinePage().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoomTimelinePage {
    return new RoomTimelinePage().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoomTimelinePage {
    return new RoomTimelinePage().fromJsonString(jsonString, options);
  }

  static equals(a: RoomTimelinePage | PlainMessage<RoomTimelinePage> | undefined, b: RoomTimelinePage | PlainMessage<RoomTimelinePage> | undefined): boolean {
    return proto3.util.equals(RoomTimelinePage, a, b);
  }
}

/**
 * @generated from message chatto.api.v1.GetRoomEventsRequest
 */
export class GetRoomEventsRequest extends Message<GetRoomEventsRequest> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * @generated from field: int32 limit = 2;
   */
  limit = 0;

  /**
   * @generated from oneof chatto.api.v1.GetRoomEventsRequest.cursor
   */
  cursor: {
    /**
     * @generated from field: string before = 3;
     */
    value: string;
    case: "before";
  } | {
    /**
     * @generated from field: string after = 4;
     */
    value: string;
    case: "after";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<GetRoomEventsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetRoomEventsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "before", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "cursor" },
    { no: 4, name: "after", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "cursor" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetRoomEventsRequest {
    return new GetRoomEventsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetRoomEventsRequest {
    return new GetRoomEventsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetRoomEventsRequest {
    return new GetRoomEventsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetRoomEventsRequest | PlainMessage<GetRoomEventsRequest> | undefined, b: GetRoomEventsRequest | PlainMessage<GetRoomEventsRequest> | undefined): boolean {
    return proto3.util.equals(GetRoomEventsRequest, a, b);
  }
}

/**
 * @generated from message chatto.api.v1.GetRoomEventsResponse
 */
export class GetRoomEventsResponse extends Message<GetRoomEventsResponse> {
  /**
   * @generated from field: chatto.api.v1.RoomTimelinePage page = 1;
   */
  page?: RoomTimelinePage;

  constructor(data?: PartialMessage<GetRoomEventsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetRoomEventsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "page", kind: "message", T: RoomTimelinePage },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetRoomEventsResponse {
    return new GetRoomEventsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetRoomEventsResponse {
    return new GetRoomEventsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetRoomEventsResponse {
    return new GetRoomEventsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetRoomEventsResponse | PlainMessage<GetRoomEventsResponse> | undefined, b: GetRoomEventsResponse | PlainMessage<GetRoomEventsResponse> | undefined): boolean {
    return proto3.util.equals(GetRoomEventsResponse, a, b);
  }
}

/**
 * @generated from message chatto.api.v1.GetRoomEventsAroundRequest
 */
export class GetRoomEventsAroundRequest extends Message<GetRoomEventsAroundRequest> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * @generated from field: string event_id = 2;
   */
  eventId = "";

  /**
   * @generated from field: int32 limit = 3;
   */
  limit = 0;

  constructor(data?: PartialMessage<GetRoomEventsAroundRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetRoomEventsAroundRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetRoomEventsAroundRequest {
    return new GetRoomEventsAroundRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetRoomEventsAroundRequest {
    return new GetRoomEventsAroundRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetRoomEventsAroundRequest {
    return new GetRoomEventsAroundRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetRoomEventsAroundRequest | PlainMessage<GetRoomEventsAroundRequest> | undefined, b: GetRoomEventsAroundRequest | PlainMessage<GetRoomEventsAroundRequest> | undefined): boolean {
    return proto3.util.equals(GetRoomEventsAroundRequest, a, b);
  }
}

/**
 * @generated from message chatto.api.v1.GetRoomEventsAroundResponse
 */
export class GetRoomEventsAroundResponse extends Message<GetRoomEventsAroundResponse> {
  /**
   * @generated from field: chatto.api.v1.RoomTimelinePage page = 1;
   */
  page?: RoomTimelinePage;

  /**
   * @generated from field: int32 target_index = 2;
   */
  targetIndex = 0;

  constructor(data?: PartialMessage<GetRoomEventsAroundResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetRoomEventsAroundResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "page", kind: "message", T: RoomTimelinePage },
    { no: 2, name: "target_index", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetRoomEventsAroundResponse {
    return new GetRoomEventsAroundResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetRoomEventsAroundResponse {
    return new GetRoomEventsAroundResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetRoomEventsAroundResponse {
    return new GetRoomEventsAroundResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetRoomEventsAroundResponse | PlainMessage<GetRoomEventsAroundResponse> | undefined, b: GetRoomEventsAroundResponse | PlainMessage<GetRoomEventsAroundResponse> | undefined): boolean {
    return proto3.util.equals(GetRoomEventsAroundResponse, a, b);
  }
}

