// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/api/v1/server.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetServerRequest, GetServerResponse } from "./server_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service chatto.api.v1.ServerService
 */
export const ServerService = {
  typeName: "chatto.api.v1.ServerService",
  methods: {
    /**
     * @generated from rpc chatto.api.v1.ServerService.GetServer
     */
    getServer: {
      name: "GetServer",
      I: GetServerRequest,
      O: GetServerResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

