// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chatto/api/v1/account.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "hmans.de/chatto/internal/pb/chatto/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AccountServiceName is the fully-qualified name of the AccountService service.
	AccountServiceName = "chatto.api.v1.AccountService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AccountServiceUpdateProfileProcedure is the fully-qualified name of the AccountService's
	// UpdateProfile RPC.
	AccountServiceUpdateProfileProcedure = "/chatto.api.v1.AccountService/UpdateProfile"
	// AccountServiceUploadAvatarProcedure is the fully-qualified name of the AccountService's
	// UploadAvatar RPC.
	AccountServiceUploadAvatarProcedure = "/chatto.api.v1.AccountService/UploadAvatar"
	// AccountServiceDeleteAvatarProcedure is the fully-qualified name of the AccountService's
	// DeleteAvatar RPC.
	AccountServiceDeleteAvatarProcedure = "/chatto.api.v1.AccountService/DeleteAvatar"
	// AccountServiceUpdateSettingsProcedure is the fully-qualified name of the AccountService's
	// UpdateSettings RPC.
	AccountServiceUpdateSettingsProcedure = "/chatto.api.v1.AccountService/UpdateSettings"
	// AccountServiceRequestAccountDeletionProcedure is the fully-qualified name of the AccountService's
	// RequestAccountDeletion RPC.
	AccountServiceRequestAccountDeletionProcedure = "/chatto.api.v1.AccountService/RequestAccountDeletion"
	// AccountServiceDeleteMyAccountProcedure is the fully-qualified name of the AccountService's
	// DeleteMyAccount RPC.
	AccountServiceDeleteMyAccountProcedure = "/chatto.api.v1.AccountService/DeleteMyAccount"
)

// AccountServiceClient is a client for the chatto.api.v1.AccountService service.
type AccountServiceClient interface {
	// Updates the authenticated user's login and/or display name.
	UpdateProfile(context.Context, *connect.Request[v1.UpdateProfileRequest]) (*connect.Response[v1.UpdateProfileResponse], error)
	// Uploads and sets the authenticated user's avatar.
	UploadAvatar(context.Context, *connect.Request[v1.UploadAvatarRequest]) (*connect.Response[v1.UploadAvatarResponse], error)
	// Deletes the authenticated user's avatar. The call is idempotent.
	DeleteAvatar(context.Context, *connect.Request[v1.DeleteAvatarRequest]) (*connect.Response[v1.DeleteAvatarResponse], error)
	// Updates the authenticated user's display preferences.
	UpdateSettings(context.Context, *connect.Request[v1.UpdateSettingsRequest]) (*connect.Response[v1.UpdateSettingsResponse], error)
	// Issues a short-lived token used to confirm self-deletion.
	RequestAccountDeletion(context.Context, *connect.Request[v1.RequestAccountDeletionRequest]) (*connect.Response[v1.RequestAccountDeletionResponse], error)
	// Permanently deletes the authenticated account after token validation.
	DeleteMyAccount(context.Context, *connect.Request[v1.DeleteMyAccountRequest]) (*connect.Response[v1.DeleteMyAccountResponse], error)
}

// NewAccountServiceClient constructs a client for the chatto.api.v1.AccountService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAccountServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AccountServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	accountServiceMethods := v1.File_chatto_api_v1_account_proto.Services().ByName("AccountService").Methods()
	return &accountServiceClient{
		updateProfile: connect.NewClient[v1.UpdateProfileRequest, v1.UpdateProfileResponse](
			httpClient,
			baseURL+AccountServiceUpdateProfileProcedure,
			connect.WithSchema(accountServiceMethods.ByName("UpdateProfile")),
			connect.WithClientOptions(opts...),
		),
		uploadAvatar: connect.NewClient[v1.UploadAvatarRequest, v1.UploadAvatarResponse](
			httpClient,
			baseURL+AccountServiceUploadAvatarProcedure,
			connect.WithSchema(accountServiceMethods.ByName("UploadAvatar")),
			connect.WithClientOptions(opts...),
		),
		deleteAvatar: connect.NewClient[v1.DeleteAvatarRequest, v1.DeleteAvatarResponse](
			httpClient,
			baseURL+AccountServiceDeleteAvatarProcedure,
			connect.WithSchema(accountServiceMethods.ByName("DeleteAvatar")),
			connect.WithClientOptions(opts...),
		),
		updateSettings: connect.NewClient[v1.UpdateSettingsRequest, v1.UpdateSettingsResponse](
			httpClient,
			baseURL+AccountServiceUpdateSettingsProcedure,
			connect.WithSchema(accountServiceMethods.ByName("UpdateSettings")),
			connect.WithClientOptions(opts...),
		),
		requestAccountDeletion: connect.NewClient[v1.RequestAccountDeletionRequest, v1.RequestAccountDeletionResponse](
			httpClient,
			baseURL+AccountServiceRequestAccountDeletionProcedure,
			connect.WithSchema(accountServiceMethods.ByName("RequestAccountDeletion")),
			connect.WithClientOptions(opts...),
		),
		deleteMyAccount: connect.NewClient[v1.DeleteMyAccountRequest, v1.DeleteMyAccountResponse](
			httpClient,
			baseURL+AccountServiceDeleteMyAccountProcedure,
			connect.WithSchema(accountServiceMethods.ByName("DeleteMyAccount")),
			connect.WithClientOptions(opts...),
		),
	}
}

// accountServiceClient implements AccountServiceClient.
type accountServiceClient struct {
	updateProfile          *connect.Client[v1.UpdateProfileRequest, v1.UpdateProfileResponse]
	uploadAvatar           *connect.Client[v1.UploadAvatarRequest, v1.UploadAvatarResponse]
	deleteAvatar           *connect.Client[v1.DeleteAvatarRequest, v1.DeleteAvatarResponse]
	updateSettings         *connect.Client[v1.UpdateSettingsRequest, v1.UpdateSettingsResponse]
	requestAccountDeletion *connect.Client[v1.RequestAccountDeletionRequest, v1.RequestAccountDeletionResponse]
	deleteMyAccount        *connect.Client[v1.DeleteMyAccountRequest, v1.DeleteMyAccountResponse]
}

// UpdateProfile calls chatto.api.v1.AccountService.UpdateProfile.
func (c *accountServiceClient) UpdateProfile(ctx context.Context, req *connect.Request[v1.UpdateProfileRequest]) (*connect.Response[v1.UpdateProfileResponse], error) {
	return c.updateProfile.CallUnary(ctx, req)
}

// UploadAvatar calls chatto.api.v1.AccountService.UploadAvatar.
func (c *accountServiceClient) UploadAvatar(ctx context.Context, req *connect.Request[v1.UploadAvatarRequest]) (*connect.Response[v1.UploadAvatarResponse], error) {
	return c.uploadAvatar.CallUnary(ctx, req)
}

// DeleteAvatar calls chatto.api.v1.AccountService.DeleteAvatar.
func (c *accountServiceClient) DeleteAvatar(ctx context.Context, req *connect.Request[v1.DeleteAvatarRequest]) (*connect.Response[v1.DeleteAvatarResponse], error) {
	return c.deleteAvatar.CallUnary(ctx, req)
}

// UpdateSettings calls chatto.api.v1.AccountService.UpdateSettings.
func (c *accountServiceClient) UpdateSettings(ctx context.Context, req *connect.Request[v1.UpdateSettingsRequest]) (*connect.Response[v1.UpdateSettingsResponse], error) {
	return c.updateSettings.CallUnary(ctx, req)
}

// RequestAccountDeletion calls chatto.api.v1.AccountService.RequestAccountDeletion.
func (c *accountServiceClient) RequestAccountDeletion(ctx context.Context, req *connect.Request[v1.RequestAccountDeletionRequest]) (*connect.Response[v1.RequestAccountDeletionResponse], error) {
	return c.requestAccountDeletion.CallUnary(ctx, req)
}

// DeleteMyAccount calls chatto.api.v1.AccountService.DeleteMyAccount.
func (c *accountServiceClient) DeleteMyAccount(ctx context.Context, req *connect.Request[v1.DeleteMyAccountRequest]) (*connect.Response[v1.DeleteMyAccountResponse], error) {
	return c.deleteMyAccount.CallUnary(ctx, req)
}

// AccountServiceHandler is an implementation of the chatto.api.v1.AccountService service.
type AccountServiceHandler interface {
	// Updates the authenticated user's login and/or display name.
	UpdateProfile(context.Context, *connect.Request[v1.UpdateProfileRequest]) (*connect.Response[v1.UpdateProfileResponse], error)
	// Uploads and sets the authenticated user's avatar.
	UploadAvatar(context.Context, *connect.Request[v1.UploadAvatarRequest]) (*connect.Response[v1.UploadAvatarResponse], error)
	// Deletes the authenticated user's avatar. The call is idempotent.
	DeleteAvatar(context.Context, *connect.Request[v1.DeleteAvatarRequest]) (*connect.Response[v1.DeleteAvatarResponse], error)
	// Updates the authenticated user's display preferences.
	UpdateSettings(context.Context, *connect.Request[v1.UpdateSettingsRequest]) (*connect.Response[v1.UpdateSettingsResponse], error)
	// Issues a short-lived token used to confirm self-deletion.
	RequestAccountDeletion(context.Context, *connect.Request[v1.RequestAccountDeletionRequest]) (*connect.Response[v1.RequestAccountDeletionResponse], error)
	// Permanently deletes the authenticated account after token validation.
	DeleteMyAccount(context.Context, *connect.Request[v1.DeleteMyAccountRequest]) (*connect.Response[v1.DeleteMyAccountResponse], error)
}

// NewAccountServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAccountServiceHandler(svc AccountServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	accountServiceMethods := v1.File_chatto_api_v1_account_proto.Services().ByName("AccountService").Methods()
	accountServiceUpdateProfileHandler := connect.NewUnaryHandler(
		AccountServiceUpdateProfileProcedure,
		svc.UpdateProfile,
		connect.WithSchema(accountServiceMethods.ByName("UpdateProfile")),
		connect.WithHandlerOptions(opts...),
	)
	accountServiceUploadAvatarHandler := connect.NewUnaryHandler(
		AccountServiceUploadAvatarProcedure,
		svc.UploadAvatar,
		connect.WithSchema(accountServiceMethods.ByName("UploadAvatar")),
		connect.WithHandlerOptions(opts...),
	)
	accountServiceDeleteAvatarHandler := connect.NewUnaryHandler(
		AccountServiceDeleteAvatarProcedure,
		svc.DeleteAvatar,
		connect.WithSchema(accountServiceMethods.ByName("DeleteAvatar")),
		connect.WithHandlerOptions(opts...),
	)
	accountServiceUpdateSettingsHandler := connect.NewUnaryHandler(
		AccountServiceUpdateSettingsProcedure,
		svc.UpdateSettings,
		connect.WithSchema(accountServiceMethods.ByName("UpdateSettings")),
		connect.WithHandlerOptions(opts...),
	)
	accountServiceRequestAccountDeletionHandler := connect.NewUnaryHandler(
		AccountServiceRequestAccountDeletionProcedure,
		svc.RequestAccountDeletion,
		connect.WithSchema(accountServiceMethods.ByName("RequestAccountDeletion")),
		connect.WithHandlerOptions(opts...),
	)
	accountServiceDeleteMyAccountHandler := connect.NewUnaryHandler(
		AccountServiceDeleteMyAccountProcedure,
		svc.DeleteMyAccount,
		connect.WithSchema(accountServiceMethods.ByName("DeleteMyAccount")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chatto.api.v1.AccountService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AccountServiceUpdateProfileProcedure:
			accountServiceUpdateProfileHandler.ServeHTTP(w, r)
		case AccountServiceUploadAvatarProcedure:
			accountServiceUploadAvatarHandler.ServeHTTP(w, r)
		case AccountServiceDeleteAvatarProcedure:
			accountServiceDeleteAvatarHandler.ServeHTTP(w, r)
		case AccountServiceUpdateSettingsProcedure:
			accountServiceUpdateSettingsHandler.ServeHTTP(w, r)
		case AccountServiceRequestAccountDeletionProcedure:
			accountServiceRequestAccountDeletionHandler.ServeHTTP(w, r)
		case AccountServiceDeleteMyAccountProcedure:
			accountServiceDeleteMyAccountHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAccountServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAccountServiceHandler struct{}

func (UnimplementedAccountServiceHandler) UpdateProfile(context.Context, *connect.Request[v1.UpdateProfileRequest]) (*connect.Response[v1.UpdateProfileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.AccountService.UpdateProfile is not implemented"))
}

func (UnimplementedAccountServiceHandler) UploadAvatar(context.Context, *connect.Request[v1.UploadAvatarRequest]) (*connect.Response[v1.UploadAvatarResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.AccountService.UploadAvatar is not implemented"))
}

func (UnimplementedAccountServiceHandler) DeleteAvatar(context.Context, *connect.Request[v1.DeleteAvatarRequest]) (*connect.Response[v1.DeleteAvatarResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.AccountService.DeleteAvatar is not implemented"))
}

func (UnimplementedAccountServiceHandler) UpdateSettings(context.Context, *connect.Request[v1.UpdateSettingsRequest]) (*connect.Response[v1.UpdateSettingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.AccountService.UpdateSettings is not implemented"))
}

func (UnimplementedAccountServiceHandler) RequestAccountDeletion(context.Context, *connect.Request[v1.RequestAccountDeletionRequest]) (*connect.Response[v1.RequestAccountDeletionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.AccountService.RequestAccountDeletion is not implemented"))
}

func (UnimplementedAccountServiceHandler) DeleteMyAccount(context.Context, *connect.Request[v1.DeleteMyAccountRequest]) (*connect.Response[v1.DeleteMyAccountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.AccountService.DeleteMyAccount is not implemented"))
}
