// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chatto/api/v1/admin_user_management.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "hmans.de/chatto/internal/pb/chatto/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AdminUserManagementServiceName is the fully-qualified name of the AdminUserManagementService
	// service.
	AdminUserManagementServiceName = "chatto.api.v1.AdminUserManagementService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AdminUserManagementServiceListMembersProcedure is the fully-qualified name of the
	// AdminUserManagementService's ListMembers RPC.
	AdminUserManagementServiceListMembersProcedure = "/chatto.api.v1.AdminUserManagementService/ListMembers"
	// AdminUserManagementServiceGetMemberProcedure is the fully-qualified name of the
	// AdminUserManagementService's GetMember RPC.
	AdminUserManagementServiceGetMemberProcedure = "/chatto.api.v1.AdminUserManagementService/GetMember"
	// AdminUserManagementServiceAssignRoleProcedure is the fully-qualified name of the
	// AdminUserManagementService's AssignRole RPC.
	AdminUserManagementServiceAssignRoleProcedure = "/chatto.api.v1.AdminUserManagementService/AssignRole"
	// AdminUserManagementServiceRevokeRoleProcedure is the fully-qualified name of the
	// AdminUserManagementService's RevokeRole RPC.
	AdminUserManagementServiceRevokeRoleProcedure = "/chatto.api.v1.AdminUserManagementService/RevokeRole"
	// AdminUserManagementServiceUpdateUserProcedure is the fully-qualified name of the
	// AdminUserManagementService's UpdateUser RPC.
	AdminUserManagementServiceUpdateUserProcedure = "/chatto.api.v1.AdminUserManagementService/UpdateUser"
	// AdminUserManagementServiceClearUsernameCooldownProcedure is the fully-qualified name of the
	// AdminUserManagementService's ClearUsernameCooldown RPC.
	AdminUserManagementServiceClearUsernameCooldownProcedure = "/chatto.api.v1.AdminUserManagementService/ClearUsernameCooldown"
)

// AdminUserManagementServiceClient is a client for the chatto.api.v1.AdminUserManagementService
// service.
type AdminUserManagementServiceClient interface {
	// Lists server members for the admin members screen.
	ListMembers(context.Context, *connect.Request[v1.ListMembersRequest]) (*connect.Response[v1.ListMembersResponse], error)
	// Gets one server member plus role/permission metadata for admin details.
	GetMember(context.Context, *connect.Request[v1.GetMemberRequest]) (*connect.Response[v1.GetMemberResponse], error)
	// Assigns a server role to a user.
	AssignRole(context.Context, *connect.Request[v1.AssignRoleRequest]) (*connect.Response[v1.AssignRoleResponse], error)
	// Revokes a server role from a user.
	RevokeRole(context.Context, *connect.Request[v1.RevokeRoleRequest]) (*connect.Response[v1.RevokeRoleResponse], error)
	// Updates a user's login and/or display name as an admin action.
	UpdateUser(context.Context, *connect.Request[v1.UpdateUserRequest]) (*connect.Response[v1.UpdateUserResponse], error)
	// Clears the target user's self-service username-change cooldown.
	ClearUsernameCooldown(context.Context, *connect.Request[v1.ClearUsernameCooldownRequest]) (*connect.Response[v1.ClearUsernameCooldownResponse], error)
}

// NewAdminUserManagementServiceClient constructs a client for the
// chatto.api.v1.AdminUserManagementService service. By default, it uses the Connect protocol with
// the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To use
// the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdminUserManagementServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdminUserManagementServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	adminUserManagementServiceMethods := v1.File_chatto_api_v1_admin_user_management_proto.Services().ByName("AdminUserManagementService").Methods()
	return &adminUserManagementServiceClient{
		listMembers: connect.NewClient[v1.ListMembersRequest, v1.ListMembersResponse](
			httpClient,
			baseURL+AdminUserManagementServiceListMembersProcedure,
			connect.WithSchema(adminUserManagementServiceMethods.ByName("ListMembers")),
			connect.WithClientOptions(opts...),
		),
		getMember: connect.NewClient[v1.GetMemberRequest, v1.GetMemberResponse](
			httpClient,
			baseURL+AdminUserManagementServiceGetMemberProcedure,
			connect.WithSchema(adminUserManagementServiceMethods.ByName("GetMember")),
			connect.WithClientOptions(opts...),
		),
		assignRole: connect.NewClient[v1.AssignRoleRequest, v1.AssignRoleResponse](
			httpClient,
			baseURL+AdminUserManagementServiceAssignRoleProcedure,
			connect.WithSchema(adminUserManagementServiceMethods.ByName("AssignRole")),
			connect.WithClientOptions(opts...),
		),
		revokeRole: connect.NewClient[v1.RevokeRoleRequest, v1.RevokeRoleResponse](
			httpClient,
			baseURL+AdminUserManagementServiceRevokeRoleProcedure,
			connect.WithSchema(adminUserManagementServiceMethods.ByName("RevokeRole")),
			connect.WithClientOptions(opts...),
		),
		updateUser: connect.NewClient[v1.UpdateUserRequest, v1.UpdateUserResponse](
			httpClient,
			baseURL+AdminUserManagementServiceUpdateUserProcedure,
			connect.WithSchema(adminUserManagementServiceMethods.ByName("UpdateUser")),
			connect.WithClientOptions(opts...),
		),
		clearUsernameCooldown: connect.NewClient[v1.ClearUsernameCooldownRequest, v1.ClearUsernameCooldownResponse](
			httpClient,
			baseURL+AdminUserManagementServiceClearUsernameCooldownProcedure,
			connect.WithSchema(adminUserManagementServiceMethods.ByName("ClearUsernameCooldown")),
			connect.WithClientOptions(opts...),
		),
	}
}

// adminUserManagementServiceClient implements AdminUserManagementServiceClient.
type adminUserManagementServiceClient struct {
	listMembers           *connect.Client[v1.ListMembersRequest, v1.ListMembersResponse]
	getMember             *connect.Client[v1.GetMemberRequest, v1.GetMemberResponse]
	assignRole            *connect.Client[v1.AssignRoleRequest, v1.AssignRoleResponse]
	revokeRole            *connect.Client[v1.RevokeRoleRequest, v1.RevokeRoleResponse]
	updateUser            *connect.Client[v1.UpdateUserRequest, v1.UpdateUserResponse]
	clearUsernameCooldown *connect.Client[v1.ClearUsernameCooldownRequest, v1.ClearUsernameCooldownResponse]
}

// ListMembers calls chatto.api.v1.AdminUserManagementService.ListMembers.
func (c *adminUserManagementServiceClient) ListMembers(ctx context.Context, req *connect.Request[v1.ListMembersRequest]) (*connect.Response[v1.ListMembersResponse], error) {
	return c.listMembers.CallUnary(ctx, req)
}

// GetMember calls chatto.api.v1.AdminUserManagementService.GetMember.
func (c *adminUserManagementServiceClient) GetMember(ctx context.Context, req *connect.Request[v1.GetMemberRequest]) (*connect.Response[v1.GetMemberResponse], error) {
	return c.getMember.CallUnary(ctx, req)
}

// AssignRole calls chatto.api.v1.AdminUserManagementService.AssignRole.
func (c *adminUserManagementServiceClient) AssignRole(ctx context.Context, req *connect.Request[v1.AssignRoleRequest]) (*connect.Response[v1.AssignRoleResponse], error) {
	return c.assignRole.CallUnary(ctx, req)
}

// RevokeRole calls chatto.api.v1.AdminUserManagementService.RevokeRole.
func (c *adminUserManagementServiceClient) RevokeRole(ctx context.Context, req *connect.Request[v1.RevokeRoleRequest]) (*connect.Response[v1.RevokeRoleResponse], error) {
	return c.revokeRole.CallUnary(ctx, req)
}

// UpdateUser calls chatto.api.v1.AdminUserManagementService.UpdateUser.
func (c *adminUserManagementServiceClient) UpdateUser(ctx context.Context, req *connect.Request[v1.UpdateUserRequest]) (*connect.Response[v1.UpdateUserResponse], error) {
	return c.updateUser.CallUnary(ctx, req)
}

// ClearUsernameCooldown calls chatto.api.v1.AdminUserManagementService.ClearUsernameCooldown.
func (c *adminUserManagementServiceClient) ClearUsernameCooldown(ctx context.Context, req *connect.Request[v1.ClearUsernameCooldownRequest]) (*connect.Response[v1.ClearUsernameCooldownResponse], error) {
	return c.clearUsernameCooldown.CallUnary(ctx, req)
}

// AdminUserManagementServiceHandler is an implementation of the
// chatto.api.v1.AdminUserManagementService service.
type AdminUserManagementServiceHandler interface {
	// Lists server members for the admin members screen.
	ListMembers(context.Context, *connect.Request[v1.ListMembersRequest]) (*connect.Response[v1.ListMembersResponse], error)
	// Gets one server member plus role/permission metadata for admin details.
	GetMember(context.Context, *connect.Request[v1.GetMemberRequest]) (*connect.Response[v1.GetMemberResponse], error)
	// Assigns a server role to a user.
	AssignRole(context.Context, *connect.Request[v1.AssignRoleRequest]) (*connect.Response[v1.AssignRoleResponse], error)
	// Revokes a server role from a user.
	RevokeRole(context.Context, *connect.Request[v1.RevokeRoleRequest]) (*connect.Response[v1.RevokeRoleResponse], error)
	// Updates a user's login and/or display name as an admin action.
	UpdateUser(context.Context, *connect.Request[v1.UpdateUserRequest]) (*connect.Response[v1.UpdateUserResponse], error)
	// Clears the target user's self-service username-change cooldown.
	ClearUsernameCooldown(context.Context, *connect.Request[v1.ClearUsernameCooldownRequest]) (*connect.Response[v1.ClearUsernameCooldownResponse], error)
}

// NewAdminUserManagementServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdminUserManagementServiceHandler(svc AdminUserManagementServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	adminUserManagementServiceMethods := v1.File_chatto_api_v1_admin_user_management_proto.Services().ByName("AdminUserManagementService").Methods()
	adminUserManagementServiceListMembersHandler := connect.NewUnaryHandler(
		AdminUserManagementServiceListMembersProcedure,
		svc.ListMembers,
		connect.WithSchema(adminUserManagementServiceMethods.ByName("ListMembers")),
		connect.WithHandlerOptions(opts...),
	)
	adminUserManagementServiceGetMemberHandler := connect.NewUnaryHandler(
		AdminUserManagementServiceGetMemberProcedure,
		svc.GetMember,
		connect.WithSchema(adminUserManagementServiceMethods.ByName("GetMember")),
		connect.WithHandlerOptions(opts...),
	)
	adminUserManagementServiceAssignRoleHandler := connect.NewUnaryHandler(
		AdminUserManagementServiceAssignRoleProcedure,
		svc.AssignRole,
		connect.WithSchema(adminUserManagementServiceMethods.ByName("AssignRole")),
		connect.WithHandlerOptions(opts...),
	)
	adminUserManagementServiceRevokeRoleHandler := connect.NewUnaryHandler(
		AdminUserManagementServiceRevokeRoleProcedure,
		svc.RevokeRole,
		connect.WithSchema(adminUserManagementServiceMethods.ByName("RevokeRole")),
		connect.WithHandlerOptions(opts...),
	)
	adminUserManagementServiceUpdateUserHandler := connect.NewUnaryHandler(
		AdminUserManagementServiceUpdateUserProcedure,
		svc.UpdateUser,
		connect.WithSchema(adminUserManagementServiceMethods.ByName("UpdateUser")),
		connect.WithHandlerOptions(opts...),
	)
	adminUserManagementServiceClearUsernameCooldownHandler := connect.NewUnaryHandler(
		AdminUserManagementServiceClearUsernameCooldownProcedure,
		svc.ClearUsernameCooldown,
		connect.WithSchema(adminUserManagementServiceMethods.ByName("ClearUsernameCooldown")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chatto.api.v1.AdminUserManagementService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdminUserManagementServiceListMembersProcedure:
			adminUserManagementServiceListMembersHandler.ServeHTTP(w, r)
		case AdminUserManagementServiceGetMemberProcedure:
			adminUserManagementServiceGetMemberHandler.ServeHTTP(w, r)
		case AdminUserManagementServiceAssignRoleProcedure:
			adminUserManagementServiceAssignRoleHandler.ServeHTTP(w, r)
		case AdminUserManagementServiceRevokeRoleProcedure:
			adminUserManagementServiceRevokeRoleHandler.ServeHTTP(w, r)
		case AdminUserManagementServiceUpdateUserProcedure:
			adminUserManagementServiceUpdateUserHandler.ServeHTTP(w, r)
		case AdminUserManagementServiceClearUsernameCooldownProcedure:
			adminUserManagementServiceClearUsernameCooldownHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdminUserManagementServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdminUserManagementServiceHandler struct{}

func (UnimplementedAdminUserManagementServiceHandler) ListMembers(context.Context, *connect.Request[v1.ListMembersRequest]) (*connect.Response[v1.ListMembersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.AdminUserManagementService.ListMembers is not implemented"))
}

func (UnimplementedAdminUserManagementServiceHandler) GetMember(context.Context, *connect.Request[v1.GetMemberRequest]) (*connect.Response[v1.GetMemberResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.AdminUserManagementService.GetMember is not implemented"))
}

func (UnimplementedAdminUserManagementServiceHandler) AssignRole(context.Context, *connect.Request[v1.AssignRoleRequest]) (*connect.Response[v1.AssignRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.AdminUserManagementService.AssignRole is not implemented"))
}

func (UnimplementedAdminUserManagementServiceHandler) RevokeRole(context.Context, *connect.Request[v1.RevokeRoleRequest]) (*connect.Response[v1.RevokeRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.AdminUserManagementService.RevokeRole is not implemented"))
}

func (UnimplementedAdminUserManagementServiceHandler) UpdateUser(context.Context, *connect.Request[v1.UpdateUserRequest]) (*connect.Response[v1.UpdateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.AdminUserManagementService.UpdateUser is not implemented"))
}

func (UnimplementedAdminUserManagementServiceHandler) ClearUsernameCooldown(context.Context, *connect.Request[v1.ClearUsernameCooldownRequest]) (*connect.Response[v1.ClearUsernameCooldownResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.AdminUserManagementService.ClearUsernameCooldown is not implemented"))
}
