// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chatto/api/v1/roles.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "hmans.de/chatto/internal/pb/chatto/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RoleServiceName is the fully-qualified name of the RoleService service.
	RoleServiceName = "chatto.api.v1.RoleService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RoleServiceListRolesProcedure is the fully-qualified name of the RoleService's ListRoles RPC.
	RoleServiceListRolesProcedure = "/chatto.api.v1.RoleService/ListRoles"
	// RoleServiceGetRoleProcedure is the fully-qualified name of the RoleService's GetRole RPC.
	RoleServiceGetRoleProcedure = "/chatto.api.v1.RoleService/GetRole"
	// RoleServiceCreateRoleProcedure is the fully-qualified name of the RoleService's CreateRole RPC.
	RoleServiceCreateRoleProcedure = "/chatto.api.v1.RoleService/CreateRole"
	// RoleServiceUpdateRoleProcedure is the fully-qualified name of the RoleService's UpdateRole RPC.
	RoleServiceUpdateRoleProcedure = "/chatto.api.v1.RoleService/UpdateRole"
	// RoleServiceDeleteRoleProcedure is the fully-qualified name of the RoleService's DeleteRole RPC.
	RoleServiceDeleteRoleProcedure = "/chatto.api.v1.RoleService/DeleteRole"
	// RoleServiceReorderRolesProcedure is the fully-qualified name of the RoleService's ReorderRoles
	// RPC.
	RoleServiceReorderRolesProcedure = "/chatto.api.v1.RoleService/ReorderRoles"
)

// RoleServiceClient is a client for the chatto.api.v1.RoleService service.
type RoleServiceClient interface {
	// Lists the server role catalog. Requires an authenticated user.
	ListRoles(context.Context, *connect.Request[v1.ListRolesRequest]) (*connect.Response[v1.ListRolesResponse], error)
	// Gets one server role plus admin detail metadata. Returns NOT_FOUND when the
	// role does not exist.
	GetRole(context.Context, *connect.Request[v1.GetRoleRequest]) (*connect.Response[v1.GetRoleResponse], error)
	// Creates a custom server role. Requires role.manage.
	CreateRole(context.Context, *connect.Request[v1.CreateRoleRequest]) (*connect.Response[v1.CreateRoleResponse], error)
	// Updates role metadata. Requires role.manage.
	UpdateRole(context.Context, *connect.Request[v1.UpdateRoleRequest]) (*connect.Response[v1.UpdateRoleResponse], error)
	// Deletes a custom server role. Requires role.manage.
	DeleteRole(context.Context, *connect.Request[v1.DeleteRoleRequest]) (*connect.Response[v1.DeleteRoleResponse], error)
	// Replaces the custom role order. Requires role.manage.
	ReorderRoles(context.Context, *connect.Request[v1.ReorderRolesRequest]) (*connect.Response[v1.ReorderRolesResponse], error)
}

// NewRoleServiceClient constructs a client for the chatto.api.v1.RoleService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRoleServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RoleServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	roleServiceMethods := v1.File_chatto_api_v1_roles_proto.Services().ByName("RoleService").Methods()
	return &roleServiceClient{
		listRoles: connect.NewClient[v1.ListRolesRequest, v1.ListRolesResponse](
			httpClient,
			baseURL+RoleServiceListRolesProcedure,
			connect.WithSchema(roleServiceMethods.ByName("ListRoles")),
			connect.WithClientOptions(opts...),
		),
		getRole: connect.NewClient[v1.GetRoleRequest, v1.GetRoleResponse](
			httpClient,
			baseURL+RoleServiceGetRoleProcedure,
			connect.WithSchema(roleServiceMethods.ByName("GetRole")),
			connect.WithClientOptions(opts...),
		),
		createRole: connect.NewClient[v1.CreateRoleRequest, v1.CreateRoleResponse](
			httpClient,
			baseURL+RoleServiceCreateRoleProcedure,
			connect.WithSchema(roleServiceMethods.ByName("CreateRole")),
			connect.WithClientOptions(opts...),
		),
		updateRole: connect.NewClient[v1.UpdateRoleRequest, v1.UpdateRoleResponse](
			httpClient,
			baseURL+RoleServiceUpdateRoleProcedure,
			connect.WithSchema(roleServiceMethods.ByName("UpdateRole")),
			connect.WithClientOptions(opts...),
		),
		deleteRole: connect.NewClient[v1.DeleteRoleRequest, v1.DeleteRoleResponse](
			httpClient,
			baseURL+RoleServiceDeleteRoleProcedure,
			connect.WithSchema(roleServiceMethods.ByName("DeleteRole")),
			connect.WithClientOptions(opts...),
		),
		reorderRoles: connect.NewClient[v1.ReorderRolesRequest, v1.ReorderRolesResponse](
			httpClient,
			baseURL+RoleServiceReorderRolesProcedure,
			connect.WithSchema(roleServiceMethods.ByName("ReorderRoles")),
			connect.WithClientOptions(opts...),
		),
	}
}

// roleServiceClient implements RoleServiceClient.
type roleServiceClient struct {
	listRoles    *connect.Client[v1.ListRolesRequest, v1.ListRolesResponse]
	getRole      *connect.Client[v1.GetRoleRequest, v1.GetRoleResponse]
	createRole   *connect.Client[v1.CreateRoleRequest, v1.CreateRoleResponse]
	updateRole   *connect.Client[v1.UpdateRoleRequest, v1.UpdateRoleResponse]
	deleteRole   *connect.Client[v1.DeleteRoleRequest, v1.DeleteRoleResponse]
	reorderRoles *connect.Client[v1.ReorderRolesRequest, v1.ReorderRolesResponse]
}

// ListRoles calls chatto.api.v1.RoleService.ListRoles.
func (c *roleServiceClient) ListRoles(ctx context.Context, req *connect.Request[v1.ListRolesRequest]) (*connect.Response[v1.ListRolesResponse], error) {
	return c.listRoles.CallUnary(ctx, req)
}

// GetRole calls chatto.api.v1.RoleService.GetRole.
func (c *roleServiceClient) GetRole(ctx context.Context, req *connect.Request[v1.GetRoleRequest]) (*connect.Response[v1.GetRoleResponse], error) {
	return c.getRole.CallUnary(ctx, req)
}

// CreateRole calls chatto.api.v1.RoleService.CreateRole.
func (c *roleServiceClient) CreateRole(ctx context.Context, req *connect.Request[v1.CreateRoleRequest]) (*connect.Response[v1.CreateRoleResponse], error) {
	return c.createRole.CallUnary(ctx, req)
}

// UpdateRole calls chatto.api.v1.RoleService.UpdateRole.
func (c *roleServiceClient) UpdateRole(ctx context.Context, req *connect.Request[v1.UpdateRoleRequest]) (*connect.Response[v1.UpdateRoleResponse], error) {
	return c.updateRole.CallUnary(ctx, req)
}

// DeleteRole calls chatto.api.v1.RoleService.DeleteRole.
func (c *roleServiceClient) DeleteRole(ctx context.Context, req *connect.Request[v1.DeleteRoleRequest]) (*connect.Response[v1.DeleteRoleResponse], error) {
	return c.deleteRole.CallUnary(ctx, req)
}

// ReorderRoles calls chatto.api.v1.RoleService.ReorderRoles.
func (c *roleServiceClient) ReorderRoles(ctx context.Context, req *connect.Request[v1.ReorderRolesRequest]) (*connect.Response[v1.ReorderRolesResponse], error) {
	return c.reorderRoles.CallUnary(ctx, req)
}

// RoleServiceHandler is an implementation of the chatto.api.v1.RoleService service.
type RoleServiceHandler interface {
	// Lists the server role catalog. Requires an authenticated user.
	ListRoles(context.Context, *connect.Request[v1.ListRolesRequest]) (*connect.Response[v1.ListRolesResponse], error)
	// Gets one server role plus admin detail metadata. Returns NOT_FOUND when the
	// role does not exist.
	GetRole(context.Context, *connect.Request[v1.GetRoleRequest]) (*connect.Response[v1.GetRoleResponse], error)
	// Creates a custom server role. Requires role.manage.
	CreateRole(context.Context, *connect.Request[v1.CreateRoleRequest]) (*connect.Response[v1.CreateRoleResponse], error)
	// Updates role metadata. Requires role.manage.
	UpdateRole(context.Context, *connect.Request[v1.UpdateRoleRequest]) (*connect.Response[v1.UpdateRoleResponse], error)
	// Deletes a custom server role. Requires role.manage.
	DeleteRole(context.Context, *connect.Request[v1.DeleteRoleRequest]) (*connect.Response[v1.DeleteRoleResponse], error)
	// Replaces the custom role order. Requires role.manage.
	ReorderRoles(context.Context, *connect.Request[v1.ReorderRolesRequest]) (*connect.Response[v1.ReorderRolesResponse], error)
}

// NewRoleServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRoleServiceHandler(svc RoleServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	roleServiceMethods := v1.File_chatto_api_v1_roles_proto.Services().ByName("RoleService").Methods()
	roleServiceListRolesHandler := connect.NewUnaryHandler(
		RoleServiceListRolesProcedure,
		svc.ListRoles,
		connect.WithSchema(roleServiceMethods.ByName("ListRoles")),
		connect.WithHandlerOptions(opts...),
	)
	roleServiceGetRoleHandler := connect.NewUnaryHandler(
		RoleServiceGetRoleProcedure,
		svc.GetRole,
		connect.WithSchema(roleServiceMethods.ByName("GetRole")),
		connect.WithHandlerOptions(opts...),
	)
	roleServiceCreateRoleHandler := connect.NewUnaryHandler(
		RoleServiceCreateRoleProcedure,
		svc.CreateRole,
		connect.WithSchema(roleServiceMethods.ByName("CreateRole")),
		connect.WithHandlerOptions(opts...),
	)
	roleServiceUpdateRoleHandler := connect.NewUnaryHandler(
		RoleServiceUpdateRoleProcedure,
		svc.UpdateRole,
		connect.WithSchema(roleServiceMethods.ByName("UpdateRole")),
		connect.WithHandlerOptions(opts...),
	)
	roleServiceDeleteRoleHandler := connect.NewUnaryHandler(
		RoleServiceDeleteRoleProcedure,
		svc.DeleteRole,
		connect.WithSchema(roleServiceMethods.ByName("DeleteRole")),
		connect.WithHandlerOptions(opts...),
	)
	roleServiceReorderRolesHandler := connect.NewUnaryHandler(
		RoleServiceReorderRolesProcedure,
		svc.ReorderRoles,
		connect.WithSchema(roleServiceMethods.ByName("ReorderRoles")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chatto.api.v1.RoleService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RoleServiceListRolesProcedure:
			roleServiceListRolesHandler.ServeHTTP(w, r)
		case RoleServiceGetRoleProcedure:
			roleServiceGetRoleHandler.ServeHTTP(w, r)
		case RoleServiceCreateRoleProcedure:
			roleServiceCreateRoleHandler.ServeHTTP(w, r)
		case RoleServiceUpdateRoleProcedure:
			roleServiceUpdateRoleHandler.ServeHTTP(w, r)
		case RoleServiceDeleteRoleProcedure:
			roleServiceDeleteRoleHandler.ServeHTTP(w, r)
		case RoleServiceReorderRolesProcedure:
			roleServiceReorderRolesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRoleServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRoleServiceHandler struct{}

func (UnimplementedRoleServiceHandler) ListRoles(context.Context, *connect.Request[v1.ListRolesRequest]) (*connect.Response[v1.ListRolesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoleService.ListRoles is not implemented"))
}

func (UnimplementedRoleServiceHandler) GetRole(context.Context, *connect.Request[v1.GetRoleRequest]) (*connect.Response[v1.GetRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoleService.GetRole is not implemented"))
}

func (UnimplementedRoleServiceHandler) CreateRole(context.Context, *connect.Request[v1.CreateRoleRequest]) (*connect.Response[v1.CreateRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoleService.CreateRole is not implemented"))
}

func (UnimplementedRoleServiceHandler) UpdateRole(context.Context, *connect.Request[v1.UpdateRoleRequest]) (*connect.Response[v1.UpdateRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoleService.UpdateRole is not implemented"))
}

func (UnimplementedRoleServiceHandler) DeleteRole(context.Context, *connect.Request[v1.DeleteRoleRequest]) (*connect.Response[v1.DeleteRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoleService.DeleteRole is not implemented"))
}

func (UnimplementedRoleServiceHandler) ReorderRoles(context.Context, *connect.Request[v1.ReorderRolesRequest]) (*connect.Response[v1.ReorderRolesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoleService.ReorderRoles is not implemented"))
}
