// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chatto/api/v1/room_timeline.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "hmans.de/chatto/internal/pb/chatto/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RoomTimelineServiceName is the fully-qualified name of the RoomTimelineService service.
	RoomTimelineServiceName = "chatto.api.v1.RoomTimelineService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RoomTimelineServiceGetRoomEventsProcedure is the fully-qualified name of the
	// RoomTimelineService's GetRoomEvents RPC.
	RoomTimelineServiceGetRoomEventsProcedure = "/chatto.api.v1.RoomTimelineService/GetRoomEvents"
	// RoomTimelineServiceGetRoomEventsAroundProcedure is the fully-qualified name of the
	// RoomTimelineService's GetRoomEventsAround RPC.
	RoomTimelineServiceGetRoomEventsAroundProcedure = "/chatto.api.v1.RoomTimelineService/GetRoomEventsAround"
)

// RoomTimelineServiceClient is a client for the chatto.api.v1.RoomTimelineService service.
type RoomTimelineServiceClient interface {
	GetRoomEvents(context.Context, *connect.Request[v1.GetRoomEventsRequest]) (*connect.Response[v1.GetRoomEventsResponse], error)
	GetRoomEventsAround(context.Context, *connect.Request[v1.GetRoomEventsAroundRequest]) (*connect.Response[v1.GetRoomEventsAroundResponse], error)
}

// NewRoomTimelineServiceClient constructs a client for the chatto.api.v1.RoomTimelineService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRoomTimelineServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RoomTimelineServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	roomTimelineServiceMethods := v1.File_chatto_api_v1_room_timeline_proto.Services().ByName("RoomTimelineService").Methods()
	return &roomTimelineServiceClient{
		getRoomEvents: connect.NewClient[v1.GetRoomEventsRequest, v1.GetRoomEventsResponse](
			httpClient,
			baseURL+RoomTimelineServiceGetRoomEventsProcedure,
			connect.WithSchema(roomTimelineServiceMethods.ByName("GetRoomEvents")),
			connect.WithClientOptions(opts...),
		),
		getRoomEventsAround: connect.NewClient[v1.GetRoomEventsAroundRequest, v1.GetRoomEventsAroundResponse](
			httpClient,
			baseURL+RoomTimelineServiceGetRoomEventsAroundProcedure,
			connect.WithSchema(roomTimelineServiceMethods.ByName("GetRoomEventsAround")),
			connect.WithClientOptions(opts...),
		),
	}
}

// roomTimelineServiceClient implements RoomTimelineServiceClient.
type roomTimelineServiceClient struct {
	getRoomEvents       *connect.Client[v1.GetRoomEventsRequest, v1.GetRoomEventsResponse]
	getRoomEventsAround *connect.Client[v1.GetRoomEventsAroundRequest, v1.GetRoomEventsAroundResponse]
}

// GetRoomEvents calls chatto.api.v1.RoomTimelineService.GetRoomEvents.
func (c *roomTimelineServiceClient) GetRoomEvents(ctx context.Context, req *connect.Request[v1.GetRoomEventsRequest]) (*connect.Response[v1.GetRoomEventsResponse], error) {
	return c.getRoomEvents.CallUnary(ctx, req)
}

// GetRoomEventsAround calls chatto.api.v1.RoomTimelineService.GetRoomEventsAround.
func (c *roomTimelineServiceClient) GetRoomEventsAround(ctx context.Context, req *connect.Request[v1.GetRoomEventsAroundRequest]) (*connect.Response[v1.GetRoomEventsAroundResponse], error) {
	return c.getRoomEventsAround.CallUnary(ctx, req)
}

// RoomTimelineServiceHandler is an implementation of the chatto.api.v1.RoomTimelineService service.
type RoomTimelineServiceHandler interface {
	GetRoomEvents(context.Context, *connect.Request[v1.GetRoomEventsRequest]) (*connect.Response[v1.GetRoomEventsResponse], error)
	GetRoomEventsAround(context.Context, *connect.Request[v1.GetRoomEventsAroundRequest]) (*connect.Response[v1.GetRoomEventsAroundResponse], error)
}

// NewRoomTimelineServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRoomTimelineServiceHandler(svc RoomTimelineServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	roomTimelineServiceMethods := v1.File_chatto_api_v1_room_timeline_proto.Services().ByName("RoomTimelineService").Methods()
	roomTimelineServiceGetRoomEventsHandler := connect.NewUnaryHandler(
		RoomTimelineServiceGetRoomEventsProcedure,
		svc.GetRoomEvents,
		connect.WithSchema(roomTimelineServiceMethods.ByName("GetRoomEvents")),
		connect.WithHandlerOptions(opts...),
	)
	roomTimelineServiceGetRoomEventsAroundHandler := connect.NewUnaryHandler(
		RoomTimelineServiceGetRoomEventsAroundProcedure,
		svc.GetRoomEventsAround,
		connect.WithSchema(roomTimelineServiceMethods.ByName("GetRoomEventsAround")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chatto.api.v1.RoomTimelineService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RoomTimelineServiceGetRoomEventsProcedure:
			roomTimelineServiceGetRoomEventsHandler.ServeHTTP(w, r)
		case RoomTimelineServiceGetRoomEventsAroundProcedure:
			roomTimelineServiceGetRoomEventsAroundHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRoomTimelineServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRoomTimelineServiceHandler struct{}

func (UnimplementedRoomTimelineServiceHandler) GetRoomEvents(context.Context, *connect.Request[v1.GetRoomEventsRequest]) (*connect.Response[v1.GetRoomEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomTimelineService.GetRoomEvents is not implemented"))
}

func (UnimplementedRoomTimelineServiceHandler) GetRoomEventsAround(context.Context, *connect.Request[v1.GetRoomEventsAroundRequest]) (*connect.Response[v1.GetRoomEventsAroundResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomTimelineService.GetRoomEventsAround is not implemented"))
}
