// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/wire/v1/protocol.proto

package wirev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	v1 "hmans.de/chatto/internal/pb/chatto/core/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorCode is the stable error taxonomy for Chatto's protobuf WebSocket.
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED           ErrorCode = 0
	ErrorCode_ERROR_CODE_UNAUTHENTICATED       ErrorCode = 1
	ErrorCode_ERROR_CODE_PERMISSION_DENIED     ErrorCode = 2
	ErrorCode_ERROR_CODE_NOT_FOUND             ErrorCode = 3
	ErrorCode_ERROR_CODE_INVALID_ARGUMENT      ErrorCode = 4
	ErrorCode_ERROR_CODE_UNIMPLEMENTED         ErrorCode = 5
	ErrorCode_ERROR_CODE_INTERNAL              ErrorCode = 6
	ErrorCode_ERROR_CODE_FULL_REFRESH_REQUIRED ErrorCode = 7
	ErrorCode_ERROR_CODE_CANCELLED             ErrorCode = 8
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_UNAUTHENTICATED",
		2: "ERROR_CODE_PERMISSION_DENIED",
		3: "ERROR_CODE_NOT_FOUND",
		4: "ERROR_CODE_INVALID_ARGUMENT",
		5: "ERROR_CODE_UNIMPLEMENTED",
		6: "ERROR_CODE_INTERNAL",
		7: "ERROR_CODE_FULL_REFRESH_REQUIRED",
		8: "ERROR_CODE_CANCELLED",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":           0,
		"ERROR_CODE_UNAUTHENTICATED":       1,
		"ERROR_CODE_PERMISSION_DENIED":     2,
		"ERROR_CODE_NOT_FOUND":             3,
		"ERROR_CODE_INVALID_ARGUMENT":      4,
		"ERROR_CODE_UNIMPLEMENTED":         5,
		"ERROR_CODE_INTERNAL":              6,
		"ERROR_CODE_FULL_REFRESH_REQUIRED": 7,
		"ERROR_CODE_CANCELLED":             8,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_wire_v1_protocol_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_chatto_wire_v1_protocol_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_chatto_wire_v1_protocol_proto_rawDescGZIP(), []int{0}
}

// InvalidationKind identifies coarse client cache surfaces affected by an event.
type InvalidationKind int32

const (
	InvalidationKind_INVALIDATION_KIND_UNSPECIFIED   InvalidationKind = 0
	InvalidationKind_INVALIDATION_KIND_ROOM          InvalidationKind = 1
	InvalidationKind_INVALIDATION_KIND_ROOM_TIMELINE InvalidationKind = 2
	InvalidationKind_INVALIDATION_KIND_USER          InvalidationKind = 3
	InvalidationKind_INVALIDATION_KIND_VIEWER        InvalidationKind = 4
	InvalidationKind_INVALIDATION_KIND_SERVER        InvalidationKind = 5
)

// Enum value maps for InvalidationKind.
var (
	InvalidationKind_name = map[int32]string{
		0: "INVALIDATION_KIND_UNSPECIFIED",
		1: "INVALIDATION_KIND_ROOM",
		2: "INVALIDATION_KIND_ROOM_TIMELINE",
		3: "INVALIDATION_KIND_USER",
		4: "INVALIDATION_KIND_VIEWER",
		5: "INVALIDATION_KIND_SERVER",
	}
	InvalidationKind_value = map[string]int32{
		"INVALIDATION_KIND_UNSPECIFIED":   0,
		"INVALIDATION_KIND_ROOM":          1,
		"INVALIDATION_KIND_ROOM_TIMELINE": 2,
		"INVALIDATION_KIND_USER":          3,
		"INVALIDATION_KIND_VIEWER":        4,
		"INVALIDATION_KIND_SERVER":        5,
	}
)

func (x InvalidationKind) Enum() *InvalidationKind {
	p := new(InvalidationKind)
	*p = x
	return p
}

func (x InvalidationKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvalidationKind) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_wire_v1_protocol_proto_enumTypes[1].Descriptor()
}

func (InvalidationKind) Type() protoreflect.EnumType {
	return &file_chatto_wire_v1_protocol_proto_enumTypes[1]
}

func (x InvalidationKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvalidationKind.Descriptor instead.
func (InvalidationKind) EnumDescriptor() ([]byte, []int) {
	return file_chatto_wire_v1_protocol_proto_rawDescGZIP(), []int{1}
}

// ClientFrame is the outer frame sent by clients over /api/wire.
type ClientFrame struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	FrameId string                 `protobuf:"bytes,1,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ClientFrame_Hello
	//	*ClientFrame_Request
	//	*ClientFrame_Cancel
	//	*ClientFrame_Ack
	Kind          isClientFrame_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFrame) Reset() {
	*x = ClientFrame{}
	mi := &file_chatto_wire_v1_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFrame) ProtoMessage() {}

func (x *ClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_wire_v1_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFrame.ProtoReflect.Descriptor instead.
func (*ClientFrame) Descriptor() ([]byte, []int) {
	return file_chatto_wire_v1_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *ClientFrame) GetFrameId() string {
	if x != nil {
		return x.FrameId
	}
	return ""
}

func (x *ClientFrame) GetKind() isClientFrame_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ClientFrame) GetHello() *ClientHello {
	if x != nil {
		if x, ok := x.Kind.(*ClientFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ClientFrame) GetRequest() *Request {
	if x != nil {
		if x, ok := x.Kind.(*ClientFrame_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *ClientFrame) GetCancel() *CancelRequest {
	if x != nil {
		if x, ok := x.Kind.(*ClientFrame_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *ClientFrame) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Kind.(*ClientFrame_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isClientFrame_Kind interface {
	isClientFrame_Kind()
}

type ClientFrame_Hello struct {
	Hello *ClientHello `protobuf:"bytes,10,opt,name=hello,proto3,oneof"`
}

type ClientFrame_Request struct {
	Request *Request `protobuf:"bytes,11,opt,name=request,proto3,oneof"`
}

type ClientFrame_Cancel struct {
	Cancel *CancelRequest `protobuf:"bytes,12,opt,name=cancel,proto3,oneof"`
}

type ClientFrame_Ack struct {
	Ack *Ack `protobuf:"bytes,13,opt,name=ack,proto3,oneof"`
}

func (*ClientFrame_Hello) isClientFrame_Kind() {}

func (*ClientFrame_Request) isClientFrame_Kind() {}

func (*ClientFrame_Cancel) isClientFrame_Kind() {}

func (*ClientFrame_Ack) isClientFrame_Kind() {}

// ServerFrame is the outer frame sent by the server over /api/wire.
type ServerFrame struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	FrameId string                 `protobuf:"bytes,1,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ServerFrame_Hello
	//	*ServerFrame_Response
	//	*ServerFrame_Event
	//	*ServerFrame_Error
	//	*ServerFrame_Ping
	Kind          isServerFrame_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_chatto_wire_v1_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_wire_v1_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_chatto_wire_v1_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *ServerFrame) GetFrameId() string {
	if x != nil {
		return x.FrameId
	}
	return ""
}

func (x *ServerFrame) GetKind() isServerFrame_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ServerFrame) GetHello() *ServerHello {
	if x != nil {
		if x, ok := x.Kind.(*ServerFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ServerFrame) GetResponse() *Response {
	if x != nil {
		if x, ok := x.Kind.(*ServerFrame_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *ServerFrame) GetEvent() *StreamEvent {
	if x != nil {
		if x, ok := x.Kind.(*ServerFrame_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *ServerFrame) GetError() *WireError {
	if x != nil {
		if x, ok := x.Kind.(*ServerFrame_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerFrame) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Kind.(*ServerFrame_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isServerFrame_Kind interface {
	isServerFrame_Kind()
}

type ServerFrame_Hello struct {
	Hello *ServerHello `protobuf:"bytes,10,opt,name=hello,proto3,oneof"`
}

type ServerFrame_Response struct {
	Response *Response `protobuf:"bytes,11,opt,name=response,proto3,oneof"`
}

type ServerFrame_Event struct {
	Event *StreamEvent `protobuf:"bytes,12,opt,name=event,proto3,oneof"`
}

type ServerFrame_Error struct {
	Error *WireError `protobuf:"bytes,13,opt,name=error,proto3,oneof"`
}

type ServerFrame_Ping struct {
	Ping *Ping `protobuf:"bytes,14,opt,name=ping,proto3,oneof"`
}

func (*ServerFrame_Hello) isServerFrame_Kind() {}

func (*ServerFrame_Response) isServerFrame_Kind() {}

func (*ServerFrame_Event) isServerFrame_Kind() {}

func (*ServerFrame_Error) isServerFrame_Kind() {}

func (*ServerFrame_Ping) isServerFrame_Kind() {}

// ClientHello starts the wire session. Cookie-authenticated clients may omit
// bearer_token. Cross-origin clients can provide an opaque Chatto bearer token.
type ClientHello struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion  string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	ResumeAfter      string                 `protobuf:"bytes,2,opt,name=resume_after,json=resumeAfter,proto3" json:"resume_after,omitempty"`
	AcceptedFeatures []string               `protobuf:"bytes,3,rep,name=accepted_features,json=acceptedFeatures,proto3" json:"accepted_features,omitempty"`
	BearerToken      string                 `protobuf:"bytes,4,opt,name=bearer_token,json=bearerToken,proto3" json:"bearer_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_chatto_wire_v1_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_wire_v1_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_chatto_wire_v1_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *ClientHello) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *ClientHello) GetResumeAfter() string {
	if x != nil {
		return x.ResumeAfter
	}
	return ""
}

func (x *ClientHello) GetAcceptedFeatures() []string {
	if x != nil {
		return x.AcceptedFeatures
	}
	return nil
}

func (x *ClientHello) GetBearerToken() string {
	if x != nil {
		return x.BearerToken
	}
	return ""
}

// ServerHello acknowledges a successfully authenticated wire session.
type ServerHello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	ServerVersion   string                 `protobuf:"bytes,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	Methods         []string               `protobuf:"bytes,3,rep,name=methods,proto3" json:"methods,omitempty"`
	Features        []string               `protobuf:"bytes,4,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServerHello) Reset() {
	*x = ServerHello{}
	mi := &file_chatto_wire_v1_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHello) ProtoMessage() {}

func (x *ServerHello) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_wire_v1_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHello.ProtoReflect.Descriptor instead.
func (*ServerHello) Descriptor() ([]byte, []int) {
	return file_chatto_wire_v1_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *ServerHello) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *ServerHello) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *ServerHello) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *ServerHello) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

// Request carries one protobuf-encoded API request message.
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_chatto_wire_v1_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_wire_v1_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_chatto_wire_v1_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *Request) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Request) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Request) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// Response carries one protobuf-encoded API response message.
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_chatto_wire_v1_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_wire_v1_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_chatto_wire_v1_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *Response) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Response) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// CancelRequest asks the server to cancel an in-flight request.
type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_chatto_wire_v1_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_wire_v1_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_chatto_wire_v1_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *CancelRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Ack acknowledges a pushed stream event. It is currently advisory.
type Ack struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventId        string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	DeliveryCursor string                 `protobuf:"bytes,2,opt,name=delivery_cursor,json=deliveryCursor,proto3" json:"delivery_cursor,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_chatto_wire_v1_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_wire_v1_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_chatto_wire_v1_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *Ack) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Ack) GetDeliveryCursor() string {
	if x != nil {
		return x.DeliveryCursor
	}
	return ""
}

// Ping is a transport-level liveness frame.
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         int64                  `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_chatto_wire_v1_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_wire_v1_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_chatto_wire_v1_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *Ping) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Ping) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

// WireError reports request or connection errors in a schemaful way.
type WireError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Code          ErrorCode              `protobuf:"varint,2,opt,name=code,proto3,enum=chatto.wire.v1.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireError) Reset() {
	*x = WireError{}
	mi := &file_chatto_wire_v1_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireError) ProtoMessage() {}

func (x *WireError) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_wire_v1_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireError.ProtoReflect.Descriptor instead.
func (*WireError) Descriptor() ([]byte, []int) {
	return file_chatto_wire_v1_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *WireError) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WireError) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *WireError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WireError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

// StreamEvent is the client-facing event envelope for durable EVT facts,
// transient LiveEvent signals, and synthetic heartbeat events.
type StreamEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventId        string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	DeliveryCursor string                 `protobuf:"bytes,2,opt,name=delivery_cursor,json=deliveryCursor,proto3" json:"delivery_cursor,omitempty"`
	EventType      string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Invalidates    []*InvalidationHint    `protobuf:"bytes,4,rep,name=invalidates,proto3" json:"invalidates,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*StreamEvent_DurableEvent
	//	*StreamEvent_LiveEvent
	//	*StreamEvent_Heartbeat
	Payload       isStreamEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEvent) Reset() {
	*x = StreamEvent{}
	mi := &file_chatto_wire_v1_protocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEvent) ProtoMessage() {}

func (x *StreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_wire_v1_protocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEvent.ProtoReflect.Descriptor instead.
func (*StreamEvent) Descriptor() ([]byte, []int) {
	return file_chatto_wire_v1_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *StreamEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *StreamEvent) GetDeliveryCursor() string {
	if x != nil {
		return x.DeliveryCursor
	}
	return ""
}

func (x *StreamEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *StreamEvent) GetInvalidates() []*InvalidationHint {
	if x != nil {
		return x.Invalidates
	}
	return nil
}

func (x *StreamEvent) GetPayload() isStreamEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamEvent) GetDurableEvent() *v1.Event {
	if x != nil {
		if x, ok := x.Payload.(*StreamEvent_DurableEvent); ok {
			return x.DurableEvent
		}
	}
	return nil
}

func (x *StreamEvent) GetLiveEvent() *v1.LiveEvent {
	if x != nil {
		if x, ok := x.Payload.(*StreamEvent_LiveEvent); ok {
			return x.LiveEvent
		}
	}
	return nil
}

func (x *StreamEvent) GetHeartbeat() *v1.HeartbeatEvent {
	if x != nil {
		if x, ok := x.Payload.(*StreamEvent_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isStreamEvent_Payload interface {
	isStreamEvent_Payload()
}

type StreamEvent_DurableEvent struct {
	DurableEvent *v1.Event `protobuf:"bytes,10,opt,name=durable_event,json=durableEvent,proto3,oneof"`
}

type StreamEvent_LiveEvent struct {
	LiveEvent *v1.LiveEvent `protobuf:"bytes,11,opt,name=live_event,json=liveEvent,proto3,oneof"`
}

type StreamEvent_Heartbeat struct {
	Heartbeat *v1.HeartbeatEvent `protobuf:"bytes,12,opt,name=heartbeat,proto3,oneof"`
}

func (*StreamEvent_DurableEvent) isStreamEvent_Payload() {}

func (*StreamEvent_LiveEvent) isStreamEvent_Payload() {}

func (*StreamEvent_Heartbeat) isStreamEvent_Payload() {}

// InvalidationHint gives older clients a fallback when they do not understand
// the concrete event payload.
type InvalidationHint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          InvalidationKind       `protobuf:"varint,1,opt,name=kind,proto3,enum=chatto.wire.v1.InvalidationKind" json:"kind,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidationHint) Reset() {
	*x = InvalidationHint{}
	mi := &file_chatto_wire_v1_protocol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidationHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidationHint) ProtoMessage() {}

func (x *InvalidationHint) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_wire_v1_protocol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidationHint.ProtoReflect.Descriptor instead.
func (*InvalidationHint) Descriptor() ([]byte, []int) {
	return file_chatto_wire_v1_protocol_proto_rawDescGZIP(), []int{11}
}

func (x *InvalidationHint) GetKind() InvalidationKind {
	if x != nil {
		return x.Kind
	}
	return InvalidationKind_INVALIDATION_KIND_UNSPECIFIED
}

func (x *InvalidationHint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_chatto_wire_v1_protocol_proto protoreflect.FileDescriptor

const file_chatto_wire_v1_protocol_proto_rawDesc = "" +
	"\n" +
	"\x1dchatto/wire/v1/protocol.proto\x12\x0echatto.wire.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1achatto/core/v1/event.proto\x1a chatto/core/v1/live_events.proto\"\xfc\x01\n" +
	"\vClientFrame\x12\x19\n" +
	"\bframe_id\x18\x01 \x01(\tR\aframeId\x123\n" +
	"\x05hello\x18\n" +
	" \x01(\v2\x1b.chatto.wire.v1.ClientHelloH\x00R\x05hello\x123\n" +
	"\arequest\x18\v \x01(\v2\x17.chatto.wire.v1.RequestH\x00R\arequest\x127\n" +
	"\x06cancel\x18\f \x01(\v2\x1d.chatto.wire.v1.CancelRequestH\x00R\x06cancel\x12'\n" +
	"\x03ack\x18\r \x01(\v2\x13.chatto.wire.v1.AckH\x00R\x03ackB\x06\n" +
	"\x04kind\"\xb1\x02\n" +
	"\vServerFrame\x12\x19\n" +
	"\bframe_id\x18\x01 \x01(\tR\aframeId\x123\n" +
	"\x05hello\x18\n" +
	" \x01(\v2\x1b.chatto.wire.v1.ServerHelloH\x00R\x05hello\x126\n" +
	"\bresponse\x18\v \x01(\v2\x18.chatto.wire.v1.ResponseH\x00R\bresponse\x123\n" +
	"\x05event\x18\f \x01(\v2\x1b.chatto.wire.v1.StreamEventH\x00R\x05event\x121\n" +
	"\x05error\x18\r \x01(\v2\x19.chatto.wire.v1.WireErrorH\x00R\x05error\x12*\n" +
	"\x04ping\x18\x0e \x01(\v2\x14.chatto.wire.v1.PingH\x00R\x04pingB\x06\n" +
	"\x04kind\"\xab\x01\n" +
	"\vClientHello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12!\n" +
	"\fresume_after\x18\x02 \x01(\tR\vresumeAfter\x12+\n" +
	"\x11accepted_features\x18\x03 \x03(\tR\x10acceptedFeatures\x12!\n" +
	"\fbearer_token\x18\x04 \x01(\tR\vbearerToken\"\x95\x01\n" +
	"\vServerHello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12%\n" +
	"\x0eserver_version\x18\x02 \x01(\tR\rserverVersion\x12\x18\n" +
	"\amethods\x18\x03 \x03(\tR\amethods\x12\x1a\n" +
	"\bfeatures\x18\x04 \x03(\tR\bfeatures\"T\n" +
	"\aRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\"=\n" +
	"\bResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\".\n" +
	"\rCancelRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"I\n" +
	"\x03Ack\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12'\n" +
	"\x0fdelivery_cursor\x18\x02 \x01(\tR\x0edeliveryCursor\"Q\n" +
	"\x04Ping\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x03R\x05nonce\x123\n" +
	"\asent_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\"\x91\x01\n" +
	"\tWireError\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12-\n" +
	"\x04code\x18\x02 \x01(\x0e2\x19.chatto.wire.v1.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\"\xf9\x02\n" +
	"\vStreamEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12'\n" +
	"\x0fdelivery_cursor\x18\x02 \x01(\tR\x0edeliveryCursor\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12B\n" +
	"\vinvalidates\x18\x04 \x03(\v2 .chatto.wire.v1.InvalidationHintR\vinvalidates\x12<\n" +
	"\rdurable_event\x18\n" +
	" \x01(\v2\x15.chatto.core.v1.EventH\x00R\fdurableEvent\x12:\n" +
	"\n" +
	"live_event\x18\v \x01(\v2\x19.chatto.core.v1.LiveEventH\x00R\tliveEvent\x12>\n" +
	"\theartbeat\x18\f \x01(\v2\x1e.chatto.core.v1.HeartbeatEventH\x00R\theartbeatB\t\n" +
	"\apayload\"X\n" +
	"\x10InvalidationHint\x124\n" +
	"\x04kind\x18\x01 \x01(\x0e2 .chatto.wire.v1.InvalidationKindR\x04kind\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id*\x9b\x02\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aERROR_CODE_UNAUTHENTICATED\x10\x01\x12 \n" +
	"\x1cERROR_CODE_PERMISSION_DENIED\x10\x02\x12\x18\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\x03\x12\x1f\n" +
	"\x1bERROR_CODE_INVALID_ARGUMENT\x10\x04\x12\x1c\n" +
	"\x18ERROR_CODE_UNIMPLEMENTED\x10\x05\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\x06\x12$\n" +
	" ERROR_CODE_FULL_REFRESH_REQUIRED\x10\a\x12\x18\n" +
	"\x14ERROR_CODE_CANCELLED\x10\b*\xce\x01\n" +
	"\x10InvalidationKind\x12!\n" +
	"\x1dINVALIDATION_KIND_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16INVALIDATION_KIND_ROOM\x10\x01\x12#\n" +
	"\x1fINVALIDATION_KIND_ROOM_TIMELINE\x10\x02\x12\x1a\n" +
	"\x16INVALIDATION_KIND_USER\x10\x03\x12\x1c\n" +
	"\x18INVALIDATION_KIND_VIEWER\x10\x04\x12\x1c\n" +
	"\x18INVALIDATION_KIND_SERVER\x10\x05B\xb0\x01\n" +
	"\x12com.chatto.wire.v1B\rProtocolProtoP\x01Z1hmans.de/chatto/internal/pb/chatto/wire/v1;wirev1\xa2\x02\x03CWX\xaa\x02\x0eChatto.Wire.V1\xca\x02\x0eChatto\\Wire\\V1\xe2\x02\x1aChatto\\Wire\\V1\\GPBMetadata\xea\x02\x10Chatto::Wire::V1b\x06proto3"

var (
	file_chatto_wire_v1_protocol_proto_rawDescOnce sync.Once
	file_chatto_wire_v1_protocol_proto_rawDescData []byte
)

func file_chatto_wire_v1_protocol_proto_rawDescGZIP() []byte {
	file_chatto_wire_v1_protocol_proto_rawDescOnce.Do(func() {
		file_chatto_wire_v1_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_wire_v1_protocol_proto_rawDesc), len(file_chatto_wire_v1_protocol_proto_rawDesc)))
	})
	return file_chatto_wire_v1_protocol_proto_rawDescData
}

var file_chatto_wire_v1_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_chatto_wire_v1_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_chatto_wire_v1_protocol_proto_goTypes = []any{
	(ErrorCode)(0),                // 0: chatto.wire.v1.ErrorCode
	(InvalidationKind)(0),         // 1: chatto.wire.v1.InvalidationKind
	(*ClientFrame)(nil),           // 2: chatto.wire.v1.ClientFrame
	(*ServerFrame)(nil),           // 3: chatto.wire.v1.ServerFrame
	(*ClientHello)(nil),           // 4: chatto.wire.v1.ClientHello
	(*ServerHello)(nil),           // 5: chatto.wire.v1.ServerHello
	(*Request)(nil),               // 6: chatto.wire.v1.Request
	(*Response)(nil),              // 7: chatto.wire.v1.Response
	(*CancelRequest)(nil),         // 8: chatto.wire.v1.CancelRequest
	(*Ack)(nil),                   // 9: chatto.wire.v1.Ack
	(*Ping)(nil),                  // 10: chatto.wire.v1.Ping
	(*WireError)(nil),             // 11: chatto.wire.v1.WireError
	(*StreamEvent)(nil),           // 12: chatto.wire.v1.StreamEvent
	(*InvalidationHint)(nil),      // 13: chatto.wire.v1.InvalidationHint
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(*v1.Event)(nil),              // 15: chatto.core.v1.Event
	(*v1.LiveEvent)(nil),          // 16: chatto.core.v1.LiveEvent
	(*v1.HeartbeatEvent)(nil),     // 17: chatto.core.v1.HeartbeatEvent
}
var file_chatto_wire_v1_protocol_proto_depIdxs = []int32{
	4,  // 0: chatto.wire.v1.ClientFrame.hello:type_name -> chatto.wire.v1.ClientHello
	6,  // 1: chatto.wire.v1.ClientFrame.request:type_name -> chatto.wire.v1.Request
	8,  // 2: chatto.wire.v1.ClientFrame.cancel:type_name -> chatto.wire.v1.CancelRequest
	9,  // 3: chatto.wire.v1.ClientFrame.ack:type_name -> chatto.wire.v1.Ack
	5,  // 4: chatto.wire.v1.ServerFrame.hello:type_name -> chatto.wire.v1.ServerHello
	7,  // 5: chatto.wire.v1.ServerFrame.response:type_name -> chatto.wire.v1.Response
	12, // 6: chatto.wire.v1.ServerFrame.event:type_name -> chatto.wire.v1.StreamEvent
	11, // 7: chatto.wire.v1.ServerFrame.error:type_name -> chatto.wire.v1.WireError
	10, // 8: chatto.wire.v1.ServerFrame.ping:type_name -> chatto.wire.v1.Ping
	14, // 9: chatto.wire.v1.Ping.sent_at:type_name -> google.protobuf.Timestamp
	0,  // 10: chatto.wire.v1.WireError.code:type_name -> chatto.wire.v1.ErrorCode
	13, // 11: chatto.wire.v1.StreamEvent.invalidates:type_name -> chatto.wire.v1.InvalidationHint
	15, // 12: chatto.wire.v1.StreamEvent.durable_event:type_name -> chatto.core.v1.Event
	16, // 13: chatto.wire.v1.StreamEvent.live_event:type_name -> chatto.core.v1.LiveEvent
	17, // 14: chatto.wire.v1.StreamEvent.heartbeat:type_name -> chatto.core.v1.HeartbeatEvent
	1,  // 15: chatto.wire.v1.InvalidationHint.kind:type_name -> chatto.wire.v1.InvalidationKind
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_chatto_wire_v1_protocol_proto_init() }
func file_chatto_wire_v1_protocol_proto_init() {
	if File_chatto_wire_v1_protocol_proto != nil {
		return
	}
	file_chatto_wire_v1_protocol_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientFrame_Hello)(nil),
		(*ClientFrame_Request)(nil),
		(*ClientFrame_Cancel)(nil),
		(*ClientFrame_Ack)(nil),
	}
	file_chatto_wire_v1_protocol_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerFrame_Hello)(nil),
		(*ServerFrame_Response)(nil),
		(*ServerFrame_Event)(nil),
		(*ServerFrame_Error)(nil),
		(*ServerFrame_Ping)(nil),
	}
	file_chatto_wire_v1_protocol_proto_msgTypes[10].OneofWrappers = []any{
		(*StreamEvent_DurableEvent)(nil),
		(*StreamEvent_LiveEvent)(nil),
		(*StreamEvent_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_wire_v1_protocol_proto_rawDesc), len(file_chatto_wire_v1_protocol_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatto_wire_v1_protocol_proto_goTypes,
		DependencyIndexes: file_chatto_wire_v1_protocol_proto_depIdxs,
		EnumInfos:         file_chatto_wire_v1_protocol_proto_enumTypes,
		MessageInfos:      file_chatto_wire_v1_protocol_proto_msgTypes,
	}.Build()
	File_chatto_wire_v1_protocol_proto = out.File
	file_chatto_wire_v1_protocol_proto_goTypes = nil
	file_chatto_wire_v1_protocol_proto_depIdxs = nil
}
