// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file chatto/core/v1/event.proto (package chatto.core.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";
import { CallEndedEvent, CallParticipantJoinedEvent, CallParticipantLeftEvent, CallStartedEvent, RoomArchivedEvent, RoomCreatedEvent, RoomDeletedEvent, RoomUnarchivedEvent, RoomUpdatedEvent, ServerMemberDeletedEvent, UserJoinedRoomEvent, UserLeftRoomEvent } from "./room_events_pb.js";
import { MessageBodyEvent, MessageEditedEvent, MessagePostedEvent, MessageRetractedEvent } from "./message_events_pb.js";
import { ThreadCreatedEvent } from "./thread_events_pb.js";
import { AssetCreatedEvent, AssetDeletedEvent, AssetProcessingFailedEvent, AssetProcessingStartedEvent, AssetProcessingSucceededEvent } from "./asset_events_pb.js";
import { ServerBannerClearedEvent, ServerBannerSetEvent, ServerBlockedUsernamesChangedEvent, ServerDescriptionChangedEvent, ServerLogoClearedEvent, ServerLogoSetEvent, ServerMotdChangedEvent, ServerNameChangedEvent, ServerWelcomeMessageChangedEvent, UserRoomNotificationLevelClearedEvent, UserRoomNotificationLevelSetEvent, UserServerNotificationLevelClearedEvent, UserServerNotificationLevelSetEvent, UserTimeFormatChangedEvent, UserTimeFormatClearedEvent, UserTimezoneChangedEvent, UserTimezoneClearedEvent } from "./config_events_pb.js";
import { RoomAddedToGroupEvent, RoomGroupCreatedEvent, RoomGroupDeletedEvent, RoomGroupsReorderedEvent, RoomGroupUpdatedEvent, RoomRemovedFromGroupEvent, RoomsInGroupReorderedEvent } from "./room_group_events_pb.js";
import { UserAccountCreatedEvent, UserAccountDeletedEvent, UserAvatarClearedEvent, UserAvatarSetEvent, UserDEKGeneratedEvent, UserDisplayNameChangedEvent, UserExternalIdentityLinkedEvent, UserKeyShreddedEvent, UserLoginChangedEvent, UserLoginCooldownClearedEvent, UserLoginCooldownStartedEvent, UserOIDCSubjectLinkedEvent, UserPasswordHashChangedEvent, UserServerPreferencesChangedEvent, UserVerifiedEmailAddedEvent } from "./user_events_pb.js";
import { RbacPermissionClearedEvent, RbacPermissionDeniedEvent, RbacPermissionGrantedEvent, RbacRoleAssignedEvent, RbacRoleCreatedEvent, RbacRoleDeletedEvent, RbacRoleDescriptionChangedEvent, RbacRoleDisplayNameChangedEvent, RbacRolePingableChangedEvent, RbacRoleRevokedEvent, RbacRolesReorderedEvent } from "./rbac_events_pb.js";
import { RoomMemberBannedEvent, RoomMemberUnbannedEvent } from "./moderation_events_pb.js";
import { AccountDeletionConfirmationIssuedEvent, AuthCodeExchangeFailedEvent, AuthCodeExchangeSucceededEvent, AuthCodeIssuedEvent, BearerTokenIssuedEvent, BearerTokenRevokedEvent, EmailVerificationCodeIssuedEvent, LoginFailedEvent, LoginSucceededEvent, LogoutSucceededEvent, OAuthConsentDeniedEvent, OAuthConsentGrantedEvent, PasswordResetCompletedEvent, PasswordResetLinkIssuedEvent, RegistrationVerificationCodeIssuedEvent } from "./auth_events_pb.js";
import { ReactionAddedEvent, ReactionRemovedEvent } from "./reaction_events_pb.js";

/**
 *
 * Event is the wire-format envelope for durable domain facts. New writes
 * to the event-sourced EVT stream use this wrapper; projections consume it
 * as source-of-truth input.
 *
 * Field-number convention for the `event` oneof:
 *
 * - **< 1000**: persisted variants. Stored in JetStream, so the
 * field number is part of the on-disk wire format. **Don't change
 * or reuse these numbers** — old stream bytes have to decode.
 *
 * - **1050-1051**: durable reaction variants that kept their legacy
 * live tags during the EVT cutover. Treat them like persisted tags.
 *
 * - **>= 1000, except 1050-1051**: retired legacy live-only variant
 * numbers. New transient pubsub signals belong in LiveEvent, not Event.
 *
 * Category ownership for the top-level oneof tags is documented in the
 * sibling *_events.proto files. The top-level tag is the durable/event
 * envelope ID; message-internal field numbers remain local to that message.
 *
 * Authorization is handled by the API boundary, not this wrapper.
 *
 * @generated from message chatto.core.v1.Event
 */
export class Event extends Message<Event> {
  /**
   * Universal event identifier (NanoID) for forward-compatibility with
   * non-NATS systems.
   *
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * When this event was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 2;
   */
  createdAt?: Timestamp;

  /**
   * ID of the user who triggered this event.
   *
   * @generated from field: string actor_id = 3;
   */
  actorId = "";

  /**
   * The concrete event payload.
   *
   * =================================================================
   * PERSISTED VARIANTS (< 1000) — stored in JetStream.
   * Changing field numbers or message structure below affects stored
   * data. Message definitions live in the sibling *_events.proto files.
   * =================================================================
   *
   * @generated from oneof chatto.core.v1.Event.event
   */
  event: {
    /**
     * ----- Room lifecycle (300-309) -----
     *
     * @generated from field: chatto.core.v1.RoomCreatedEvent room_created = 300;
     */
    value: RoomCreatedEvent;
    case: "roomCreated";
  } | {
    /**
     * @generated from field: chatto.core.v1.RoomUpdatedEvent room_updated = 301;
     */
    value: RoomUpdatedEvent;
    case: "roomUpdated";
  } | {
    /**
     * @generated from field: chatto.core.v1.RoomDeletedEvent room_deleted = 302;
     */
    value: RoomDeletedEvent;
    case: "roomDeleted";
  } | {
    /**
     * @generated from field: chatto.core.v1.RoomArchivedEvent room_archived = 303;
     */
    value: RoomArchivedEvent;
    case: "roomArchived";
  } | {
    /**
     * Fields 305 / 306 were RoomBecameAutoJoinEvent / RoomBecameRegularEvent.
     * Removed alongside the auto-join feature; oneof tags don't reserve,
     * so don't reuse those numbers.
     *
     * @generated from field: chatto.core.v1.RoomUnarchivedEvent room_unarchived = 304;
     */
    value: RoomUnarchivedEvent;
    case: "roomUnarchived";
  } | {
    /**
     * ----- Room membership (310-329) -----
     *
     * @generated from field: chatto.core.v1.UserJoinedRoomEvent user_joined_room = 310;
     */
    value: UserJoinedRoomEvent;
    case: "userJoinedRoom";
  } | {
    /**
     * @generated from field: chatto.core.v1.UserLeftRoomEvent user_left_room = 311;
     */
    value: UserLeftRoomEvent;
    case: "userLeftRoom";
  } | {
    /**
     * @generated from field: chatto.core.v1.ServerMemberDeletedEvent server_member_deleted = 320;
     */
    value: ServerMemberDeletedEvent;
    case: "serverMemberDeleted";
  } | {
    /**
     * ----- Voice calls (330-339, durable room facts) -----
     *
     * @generated from field: chatto.core.v1.CallParticipantJoinedEvent voice_call_participant_joined = 330;
     */
    value: CallParticipantJoinedEvent;
    case: "voiceCallParticipantJoined";
  } | {
    /**
     * @generated from field: chatto.core.v1.CallParticipantLeftEvent voice_call_participant_left = 331;
     */
    value: CallParticipantLeftEvent;
    case: "voiceCallParticipantLeft";
  } | {
    /**
     * @generated from field: chatto.core.v1.CallStartedEvent voice_call_started = 332;
     */
    value: CallStartedEvent;
    case: "voiceCallStarted";
  } | {
    /**
     * @generated from field: chatto.core.v1.CallEndedEvent voice_call_ended = 333;
     */
    value: CallEndedEvent;
    case: "voiceCallEnded";
  } | {
    /**
     * ----- Messages (400-424) -----
     *
     * @generated from field: chatto.core.v1.MessagePostedEvent message_posted = 400;
     */
    value: MessagePostedEvent;
    case: "messagePosted";
  } | {
    /**
     * Durable edit / retract variants for the EVT stream (ADR-033/034/035,
     * issue #597). The old live-only MessageUpdatedEvent/MessageDeletedEvent
     * tags at 1040/1041 are now retired and reserved.
     *
     * @generated from field: chatto.core.v1.MessageEditedEvent message_edited = 401;
     */
    value: MessageEditedEvent;
    case: "messageEdited";
  } | {
    /**
     * @generated from field: chatto.core.v1.MessageRetractedEvent message_retracted = 402;
     */
    value: MessageRetractedEvent;
    case: "messageRetracted";
  } | {
    /**
     * Field 403 was ThreadReplyEchoEvent, now folded into MessagePostedEvent.
     *
     * @generated from field: chatto.core.v1.MessageBodyEvent message_body = 404;
     */
    value: MessageBodyEvent;
    case: "messageBody";
  } | {
    /**
     * ----- Threads (425-449, durable, room-owned) -----
     *
     * @generated from field: chatto.core.v1.ThreadCreatedEvent thread_created = 425;
     */
    value: ThreadCreatedEvent;
    case: "threadCreated";
  } | {
    /**
     * ----- Assets (450-474, durable) -----
     * The asset aggregate. AssetCreated establishes content identity for
     * one uploaded or generated binary; AssetProcessingStarted/Succeeded/
     * Failed track derivative work; AssetDeleted terminates the lifecycle.
     *
     * @generated from field: chatto.core.v1.AssetCreatedEvent asset_created = 450;
     */
    value: AssetCreatedEvent;
    case: "assetCreated";
  } | {
    /**
     * @generated from field: chatto.core.v1.AssetProcessingStartedEvent asset_processing_started = 451;
     */
    value: AssetProcessingStartedEvent;
    case: "assetProcessingStarted";
  } | {
    /**
     * @generated from field: chatto.core.v1.AssetProcessingSucceededEvent asset_processing_succeeded = 452;
     */
    value: AssetProcessingSucceededEvent;
    case: "assetProcessingSucceeded";
  } | {
    /**
     * @generated from field: chatto.core.v1.AssetProcessingFailedEvent asset_processing_failed = 453;
     */
    value: AssetProcessingFailedEvent;
    case: "assetProcessingFailed";
  } | {
    /**
     * @generated from field: chatto.core.v1.AssetDeletedEvent asset_deleted = 454;
     */
    value: AssetDeletedEvent;
    case: "assetDeleted";
  } | {
    /**
     * ----- Config / preferences (500-599, durable) -----
     * These variants live on the EVT stream (subjects under evt.config.>)
     * per ADRs 033/034/035. Member-visible server profile/config live
     * invalidation uses LiveEvent.ServerUpdatedEvent instead.
     *
     * @generated from field: chatto.core.v1.ServerNameChangedEvent server_name_changed = 501;
     */
    value: ServerNameChangedEvent;
    case: "serverNameChanged";
  } | {
    /**
     * @generated from field: chatto.core.v1.ServerDescriptionChangedEvent server_description_changed = 502;
     */
    value: ServerDescriptionChangedEvent;
    case: "serverDescriptionChanged";
  } | {
    /**
     * @generated from field: chatto.core.v1.ServerWelcomeMessageChangedEvent server_welcome_message_changed = 503;
     */
    value: ServerWelcomeMessageChangedEvent;
    case: "serverWelcomeMessageChanged";
  } | {
    /**
     * @generated from field: chatto.core.v1.ServerMotdChangedEvent server_motd_changed = 504;
     */
    value: ServerMotdChangedEvent;
    case: "serverMotdChanged";
  } | {
    /**
     * @generated from field: chatto.core.v1.ServerBlockedUsernamesChangedEvent server_blocked_usernames_changed = 505;
     */
    value: ServerBlockedUsernamesChangedEvent;
    case: "serverBlockedUsernamesChanged";
  } | {
    /**
     * @generated from field: chatto.core.v1.ServerLogoSetEvent server_logo_set = 506;
     */
    value: ServerLogoSetEvent;
    case: "serverLogoSet";
  } | {
    /**
     * @generated from field: chatto.core.v1.ServerLogoClearedEvent server_logo_cleared = 507;
     */
    value: ServerLogoClearedEvent;
    case: "serverLogoCleared";
  } | {
    /**
     * @generated from field: chatto.core.v1.ServerBannerSetEvent server_banner_set = 508;
     */
    value: ServerBannerSetEvent;
    case: "serverBannerSet";
  } | {
    /**
     * @generated from field: chatto.core.v1.ServerBannerClearedEvent server_banner_cleared = 509;
     */
    value: ServerBannerClearedEvent;
    case: "serverBannerCleared";
  } | {
    /**
     * @generated from field: chatto.core.v1.UserTimezoneChangedEvent user_timezone_changed = 510;
     */
    value: UserTimezoneChangedEvent;
    case: "userTimezoneChanged";
  } | {
    /**
     * @generated from field: chatto.core.v1.UserTimezoneClearedEvent user_timezone_cleared = 511;
     */
    value: UserTimezoneClearedEvent;
    case: "userTimezoneCleared";
  } | {
    /**
     * @generated from field: chatto.core.v1.UserTimeFormatChangedEvent user_time_format_changed = 512;
     */
    value: UserTimeFormatChangedEvent;
    case: "userTimeFormatChanged";
  } | {
    /**
     * @generated from field: chatto.core.v1.UserTimeFormatClearedEvent user_time_format_cleared = 513;
     */
    value: UserTimeFormatClearedEvent;
    case: "userTimeFormatCleared";
  } | {
    /**
     * @generated from field: chatto.core.v1.UserServerNotificationLevelSetEvent user_server_notification_level_set = 514;
     */
    value: UserServerNotificationLevelSetEvent;
    case: "userServerNotificationLevelSet";
  } | {
    /**
     * @generated from field: chatto.core.v1.UserServerNotificationLevelClearedEvent user_server_notification_level_cleared = 515;
     */
    value: UserServerNotificationLevelClearedEvent;
    case: "userServerNotificationLevelCleared";
  } | {
    /**
     * @generated from field: chatto.core.v1.UserRoomNotificationLevelSetEvent user_room_notification_level_set = 516;
     */
    value: UserRoomNotificationLevelSetEvent;
    case: "userRoomNotificationLevelSet";
  } | {
    /**
     * @generated from field: chatto.core.v1.UserRoomNotificationLevelClearedEvent user_room_notification_level_cleared = 517;
     */
    value: UserRoomNotificationLevelClearedEvent;
    case: "userRoomNotificationLevelCleared";
  } | {
    /**
     * ----- Room groups (600-609, durable, evt.group.{groupId}) -----
     * The group aggregate owns its room-membership AND room-ordering.
     * Move-room is two events (RoomRemovedFromGroup on source +
     * RoomAddedToGroup on target), matching ADR-034 Approach A.
     *
     * @generated from field: chatto.core.v1.RoomGroupCreatedEvent room_group_created = 600;
     */
    value: RoomGroupCreatedEvent;
    case: "roomGroupCreated";
  } | {
    /**
     * @generated from field: chatto.core.v1.RoomGroupUpdatedEvent room_group_updated = 601;
     */
    value: RoomGroupUpdatedEvent;
    case: "roomGroupUpdated";
  } | {
    /**
     * @generated from field: chatto.core.v1.RoomGroupDeletedEvent room_group_deleted = 602;
     */
    value: RoomGroupDeletedEvent;
    case: "roomGroupDeleted";
  } | {
    /**
     * @generated from field: chatto.core.v1.RoomAddedToGroupEvent room_added_to_group = 603;
     */
    value: RoomAddedToGroupEvent;
    case: "roomAddedToGroup";
  } | {
    /**
     * @generated from field: chatto.core.v1.RoomRemovedFromGroupEvent room_removed_from_group = 604;
     */
    value: RoomRemovedFromGroupEvent;
    case: "roomRemovedFromGroup";
  } | {
    /**
     * @generated from field: chatto.core.v1.RoomsInGroupReorderedEvent rooms_in_group_reordered = 605;
     */
    value: RoomsInGroupReorderedEvent;
    case: "roomsInGroupReordered";
  } | {
    /**
     * ----- Room layout (650-659, durable, evt.layout.{singleton}) -----
     * The layout aggregate is a singleton; the singletonID is a stable
     * constant ("default"). It owns the operator-defined inter-group
     * ordering for the sidebar. New groups appear at the end of the
     * sidebar implicitly via the RoomGroup projection's All() + the
     * reconciler in ListRoomGroupsOrdered; the layout aggregate only
     * tracks explicit reorders.
     *
     * @generated from field: chatto.core.v1.RoomGroupsReorderedEvent room_groups_reordered = 650;
     */
    value: RoomGroupsReorderedEvent;
    case: "roomGroupsReordered";
  } | {
    /**
     * ----- Users (700-799, durable, evt.user.{userId}) -----
     *
     * @generated from field: chatto.core.v1.UserAccountCreatedEvent user_account_created = 700;
     */
    value: UserAccountCreatedEvent;
    case: "userAccountCreated";
  } | {
    /**
     * @generated from field: chatto.core.v1.UserLoginChangedEvent user_login_changed = 701;
     */
    value: UserLoginChangedEvent;
    case: "userLoginChanged";
  } | {
    /**
     * @generated from field: chatto.core.v1.UserDisplayNameChangedEvent user_display_name_changed = 702;
     */
    value: UserDisplayNameChangedEvent;
    case: "userDisplayNameChanged";
  } | {
    /**
     * @generated from field: chatto.core.v1.UserAvatarSetEvent user_avatar_set = 703;
     */
    value: UserAvatarSetEvent;
    case: "userAvatarSet";
  } | {
    /**
     * @generated from field: chatto.core.v1.UserAvatarClearedEvent user_avatar_cleared = 704;
     */
    value: UserAvatarClearedEvent;
    case: "userAvatarCleared";
  } | {
    /**
     * @generated from field: chatto.core.v1.UserVerifiedEmailAddedEvent user_verified_email_added = 705;
     */
    value: UserVerifiedEmailAddedEvent;
    case: "userVerifiedEmailAdded";
  } | {
    /**
     * @generated from field: chatto.core.v1.UserPasswordHashChangedEvent user_password_hash_changed = 706;
     */
    value: UserPasswordHashChangedEvent;
    case: "userPasswordHashChanged";
  } | {
    /**
     * @generated from field: chatto.core.v1.UserOIDCSubjectLinkedEvent user_oidc_subject_linked = 707;
     */
    value: UserOIDCSubjectLinkedEvent;
    case: "userOidcSubjectLinked";
  } | {
    /**
     * @generated from field: chatto.core.v1.UserServerPreferencesChangedEvent user_server_preferences_changed = 708;
     */
    value: UserServerPreferencesChangedEvent;
    case: "userServerPreferencesChanged";
  } | {
    /**
     * @generated from field: chatto.core.v1.UserLoginCooldownClearedEvent user_login_cooldown_cleared = 709;
     */
    value: UserLoginCooldownClearedEvent;
    case: "userLoginCooldownCleared";
  } | {
    /**
     * @generated from field: chatto.core.v1.UserAccountDeletedEvent user_account_deleted = 710;
     */
    value: UserAccountDeletedEvent;
    case: "userAccountDeleted";
  } | {
    /**
     * @generated from field: chatto.core.v1.UserLoginCooldownStartedEvent user_login_cooldown_started = 711;
     */
    value: UserLoginCooldownStartedEvent;
    case: "userLoginCooldownStarted";
  } | {
    /**
     * @generated from field: chatto.core.v1.UserKeyShreddedEvent user_key_shredded = 712;
     */
    value: UserKeyShreddedEvent;
    case: "userKeyShredded";
  } | {
    /**
     * @generated from field: chatto.core.v1.UserDEKGeneratedEvent user_dek_generated = 713;
     */
    value: UserDEKGeneratedEvent;
    case: "userDekGenerated";
  } | {
    /**
     * @generated from field: chatto.core.v1.UserExternalIdentityLinkedEvent user_external_identity_linked = 714;
     */
    value: UserExternalIdentityLinkedEvent;
    case: "userExternalIdentityLinked";
  } | {
    /**
     * ----- RBAC (800-839, durable, evt.rbac.>) -----
     *
     * @generated from field: chatto.core.v1.RbacRoleCreatedEvent rbac_role_created = 800;
     */
    value: RbacRoleCreatedEvent;
    case: "rbacRoleCreated";
  } | {
    /**
     * @generated from field: chatto.core.v1.RbacRoleDisplayNameChangedEvent rbac_role_display_name_changed = 801;
     */
    value: RbacRoleDisplayNameChangedEvent;
    case: "rbacRoleDisplayNameChanged";
  } | {
    /**
     * @generated from field: chatto.core.v1.RbacRoleDescriptionChangedEvent rbac_role_description_changed = 802;
     */
    value: RbacRoleDescriptionChangedEvent;
    case: "rbacRoleDescriptionChanged";
  } | {
    /**
     * @generated from field: chatto.core.v1.RbacRoleDeletedEvent rbac_role_deleted = 803;
     */
    value: RbacRoleDeletedEvent;
    case: "rbacRoleDeleted";
  } | {
    /**
     * @generated from field: chatto.core.v1.RbacRolesReorderedEvent rbac_roles_reordered = 804;
     */
    value: RbacRolesReorderedEvent;
    case: "rbacRolesReordered";
  } | {
    /**
     * @generated from field: chatto.core.v1.RbacRoleAssignedEvent rbac_role_assigned = 805;
     */
    value: RbacRoleAssignedEvent;
    case: "rbacRoleAssigned";
  } | {
    /**
     * @generated from field: chatto.core.v1.RbacRoleRevokedEvent rbac_role_revoked = 806;
     */
    value: RbacRoleRevokedEvent;
    case: "rbacRoleRevoked";
  } | {
    /**
     * @generated from field: chatto.core.v1.RbacPermissionGrantedEvent rbac_permission_granted = 810;
     */
    value: RbacPermissionGrantedEvent;
    case: "rbacPermissionGranted";
  } | {
    /**
     * @generated from field: chatto.core.v1.RbacPermissionDeniedEvent rbac_permission_denied = 811;
     */
    value: RbacPermissionDeniedEvent;
    case: "rbacPermissionDenied";
  } | {
    /**
     * @generated from field: chatto.core.v1.RbacPermissionClearedEvent rbac_permission_cleared = 812;
     */
    value: RbacPermissionClearedEvent;
    case: "rbacPermissionCleared";
  } | {
    /**
     * @generated from field: chatto.core.v1.RbacRolePingableChangedEvent rbac_role_pingable_changed = 813;
     */
    value: RbacRolePingableChangedEvent;
    case: "rbacRolePingableChanged";
  } | {
    /**
     * ----- Moderation (840-899, durable, room-owned) -----
     *
     * @generated from field: chatto.core.v1.RoomMemberBannedEvent room_member_banned = 840;
     */
    value: RoomMemberBannedEvent;
    case: "roomMemberBanned";
  } | {
    /**
     * @generated from field: chatto.core.v1.RoomMemberUnbannedEvent room_member_unbanned = 841;
     */
    value: RoomMemberUnbannedEvent;
    case: "roomMemberUnbanned";
  } | {
    /**
     * ----- Auth/security audit (900-999, durable, evt.auth.server / evt.user.{userId}) -----
     * These facts are intentionally minimal: no raw token, verification code,
     * link, IP address, password, auth code, bearer token, OAuth redirect URI,
     * or unhashed email is persisted in EVT.
     *
     * @generated from field: chatto.core.v1.RegistrationVerificationCodeIssuedEvent registration_verification_code_issued = 900;
     */
    value: RegistrationVerificationCodeIssuedEvent;
    case: "registrationVerificationCodeIssued";
  } | {
    /**
     * @generated from field: chatto.core.v1.EmailVerificationCodeIssuedEvent email_verification_code_issued = 901;
     */
    value: EmailVerificationCodeIssuedEvent;
    case: "emailVerificationCodeIssued";
  } | {
    /**
     * @generated from field: chatto.core.v1.PasswordResetLinkIssuedEvent password_reset_link_issued = 902;
     */
    value: PasswordResetLinkIssuedEvent;
    case: "passwordResetLinkIssued";
  } | {
    /**
     * @generated from field: chatto.core.v1.AccountDeletionConfirmationIssuedEvent account_deletion_confirmation_issued = 903;
     */
    value: AccountDeletionConfirmationIssuedEvent;
    case: "accountDeletionConfirmationIssued";
  } | {
    /**
     * @generated from field: chatto.core.v1.PasswordResetCompletedEvent password_reset_completed = 904;
     */
    value: PasswordResetCompletedEvent;
    case: "passwordResetCompleted";
  } | {
    /**
     * @generated from field: chatto.core.v1.LoginSucceededEvent login_succeeded = 905;
     */
    value: LoginSucceededEvent;
    case: "loginSucceeded";
  } | {
    /**
     * @generated from field: chatto.core.v1.LoginFailedEvent login_failed = 906;
     */
    value: LoginFailedEvent;
    case: "loginFailed";
  } | {
    /**
     * @generated from field: chatto.core.v1.LogoutSucceededEvent logout_succeeded = 907;
     */
    value: LogoutSucceededEvent;
    case: "logoutSucceeded";
  } | {
    /**
     * @generated from field: chatto.core.v1.AuthCodeIssuedEvent auth_code_issued = 908;
     */
    value: AuthCodeIssuedEvent;
    case: "authCodeIssued";
  } | {
    /**
     * @generated from field: chatto.core.v1.AuthCodeExchangeSucceededEvent auth_code_exchange_succeeded = 909;
     */
    value: AuthCodeExchangeSucceededEvent;
    case: "authCodeExchangeSucceeded";
  } | {
    /**
     * @generated from field: chatto.core.v1.AuthCodeExchangeFailedEvent auth_code_exchange_failed = 910;
     */
    value: AuthCodeExchangeFailedEvent;
    case: "authCodeExchangeFailed";
  } | {
    /**
     * @generated from field: chatto.core.v1.BearerTokenIssuedEvent bearer_token_issued = 911;
     */
    value: BearerTokenIssuedEvent;
    case: "bearerTokenIssued";
  } | {
    /**
     * @generated from field: chatto.core.v1.BearerTokenRevokedEvent bearer_token_revoked = 912;
     */
    value: BearerTokenRevokedEvent;
    case: "bearerTokenRevoked";
  } | {
    /**
     * @generated from field: chatto.core.v1.OAuthConsentGrantedEvent oauth_consent_granted = 913;
     */
    value: OAuthConsentGrantedEvent;
    case: "oauthConsentGranted";
  } | {
    /**
     * @generated from field: chatto.core.v1.OAuthConsentDeniedEvent oauth_consent_denied = 914;
     */
    value: OAuthConsentDeniedEvent;
    case: "oauthConsentDenied";
  } | {
    /**
     * ----- Reactions (1050-1059) — durable legacy-tag exception -----
     * Reaction events are stored on EVT today. They kept the legacy
     * 1050/1051 tags during the cutover, so treat these two tags as
     * frozen durable IDs even though they sit in the >=1000 range.
     *
     * @generated from field: chatto.core.v1.ReactionAddedEvent reaction_added = 1050;
     */
    value: ReactionAddedEvent;
    case: "reactionAdded";
  } | {
    /**
     * @generated from field: chatto.core.v1.ReactionRemovedEvent reaction_removed = 1051;
     */
    value: ReactionRemovedEvent;
    case: "reactionRemoved";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<Event>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.core.v1.Event";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "created_at", kind: "message", T: Timestamp },
    { no: 3, name: "actor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 300, name: "room_created", kind: "message", T: RoomCreatedEvent, oneof: "event" },
    { no: 301, name: "room_updated", kind: "message", T: RoomUpdatedEvent, oneof: "event" },
    { no: 302, name: "room_deleted", kind: "message", T: RoomDeletedEvent, oneof: "event" },
    { no: 303, name: "room_archived", kind: "message", T: RoomArchivedEvent, oneof: "event" },
    { no: 304, name: "room_unarchived", kind: "message", T: RoomUnarchivedEvent, oneof: "event" },
    { no: 310, name: "user_joined_room", kind: "message", T: UserJoinedRoomEvent, oneof: "event" },
    { no: 311, name: "user_left_room", kind: "message", T: UserLeftRoomEvent, oneof: "event" },
    { no: 320, name: "server_member_deleted", kind: "message", T: ServerMemberDeletedEvent, oneof: "event" },
    { no: 330, name: "voice_call_participant_joined", kind: "message", T: CallParticipantJoinedEvent, oneof: "event" },
    { no: 331, name: "voice_call_participant_left", kind: "message", T: CallParticipantLeftEvent, oneof: "event" },
    { no: 332, name: "voice_call_started", kind: "message", T: CallStartedEvent, oneof: "event" },
    { no: 333, name: "voice_call_ended", kind: "message", T: CallEndedEvent, oneof: "event" },
    { no: 400, name: "message_posted", kind: "message", T: MessagePostedEvent, oneof: "event" },
    { no: 401, name: "message_edited", kind: "message", T: MessageEditedEvent, oneof: "event" },
    { no: 402, name: "message_retracted", kind: "message", T: MessageRetractedEvent, oneof: "event" },
    { no: 404, name: "message_body", kind: "message", T: MessageBodyEvent, oneof: "event" },
    { no: 425, name: "thread_created", kind: "message", T: ThreadCreatedEvent, oneof: "event" },
    { no: 450, name: "asset_created", kind: "message", T: AssetCreatedEvent, oneof: "event" },
    { no: 451, name: "asset_processing_started", kind: "message", T: AssetProcessingStartedEvent, oneof: "event" },
    { no: 452, name: "asset_processing_succeeded", kind: "message", T: AssetProcessingSucceededEvent, oneof: "event" },
    { no: 453, name: "asset_processing_failed", kind: "message", T: AssetProcessingFailedEvent, oneof: "event" },
    { no: 454, name: "asset_deleted", kind: "message", T: AssetDeletedEvent, oneof: "event" },
    { no: 501, name: "server_name_changed", kind: "message", T: ServerNameChangedEvent, oneof: "event" },
    { no: 502, name: "server_description_changed", kind: "message", T: ServerDescriptionChangedEvent, oneof: "event" },
    { no: 503, name: "server_welcome_message_changed", kind: "message", T: ServerWelcomeMessageChangedEvent, oneof: "event" },
    { no: 504, name: "server_motd_changed", kind: "message", T: ServerMotdChangedEvent, oneof: "event" },
    { no: 505, name: "server_blocked_usernames_changed", kind: "message", T: ServerBlockedUsernamesChangedEvent, oneof: "event" },
    { no: 506, name: "server_logo_set", kind: "message", T: ServerLogoSetEvent, oneof: "event" },
    { no: 507, name: "server_logo_cleared", kind: "message", T: ServerLogoClearedEvent, oneof: "event" },
    { no: 508, name: "server_banner_set", kind: "message", T: ServerBannerSetEvent, oneof: "event" },
    { no: 509, name: "server_banner_cleared", kind: "message", T: ServerBannerClearedEvent, oneof: "event" },
    { no: 510, name: "user_timezone_changed", kind: "message", T: UserTimezoneChangedEvent, oneof: "event" },
    { no: 511, name: "user_timezone_cleared", kind: "message", T: UserTimezoneClearedEvent, oneof: "event" },
    { no: 512, name: "user_time_format_changed", kind: "message", T: UserTimeFormatChangedEvent, oneof: "event" },
    { no: 513, name: "user_time_format_cleared", kind: "message", T: UserTimeFormatClearedEvent, oneof: "event" },
    { no: 514, name: "user_server_notification_level_set", kind: "message", T: UserServerNotificationLevelSetEvent, oneof: "event" },
    { no: 515, name: "user_server_notification_level_cleared", kind: "message", T: UserServerNotificationLevelClearedEvent, oneof: "event" },
    { no: 516, name: "user_room_notification_level_set", kind: "message", T: UserRoomNotificationLevelSetEvent, oneof: "event" },
    { no: 517, name: "user_room_notification_level_cleared", kind: "message", T: UserRoomNotificationLevelClearedEvent, oneof: "event" },
    { no: 600, name: "room_group_created", kind: "message", T: RoomGroupCreatedEvent, oneof: "event" },
    { no: 601, name: "room_group_updated", kind: "message", T: RoomGroupUpdatedEvent, oneof: "event" },
    { no: 602, name: "room_group_deleted", kind: "message", T: RoomGroupDeletedEvent, oneof: "event" },
    { no: 603, name: "room_added_to_group", kind: "message", T: RoomAddedToGroupEvent, oneof: "event" },
    { no: 604, name: "room_removed_from_group", kind: "message", T: RoomRemovedFromGroupEvent, oneof: "event" },
    { no: 605, name: "rooms_in_group_reordered", kind: "message", T: RoomsInGroupReorderedEvent, oneof: "event" },
    { no: 650, name: "room_groups_reordered", kind: "message", T: RoomGroupsReorderedEvent, oneof: "event" },
    { no: 700, name: "user_account_created", kind: "message", T: UserAccountCreatedEvent, oneof: "event" },
    { no: 701, name: "user_login_changed", kind: "message", T: UserLoginChangedEvent, oneof: "event" },
    { no: 702, name: "user_display_name_changed", kind: "message", T: UserDisplayNameChangedEvent, oneof: "event" },
    { no: 703, name: "user_avatar_set", kind: "message", T: UserAvatarSetEvent, oneof: "event" },
    { no: 704, name: "user_avatar_cleared", kind: "message", T: UserAvatarClearedEvent, oneof: "event" },
    { no: 705, name: "user_verified_email_added", kind: "message", T: UserVerifiedEmailAddedEvent, oneof: "event" },
    { no: 706, name: "user_password_hash_changed", kind: "message", T: UserPasswordHashChangedEvent, oneof: "event" },
    { no: 707, name: "user_oidc_subject_linked", kind: "message", T: UserOIDCSubjectLinkedEvent, oneof: "event" },
    { no: 708, name: "user_server_preferences_changed", kind: "message", T: UserServerPreferencesChangedEvent, oneof: "event" },
    { no: 709, name: "user_login_cooldown_cleared", kind: "message", T: UserLoginCooldownClearedEvent, oneof: "event" },
    { no: 710, name: "user_account_deleted", kind: "message", T: UserAccountDeletedEvent, oneof: "event" },
    { no: 711, name: "user_login_cooldown_started", kind: "message", T: UserLoginCooldownStartedEvent, oneof: "event" },
    { no: 712, name: "user_key_shredded", kind: "message", T: UserKeyShreddedEvent, oneof: "event" },
    { no: 713, name: "user_dek_generated", kind: "message", T: UserDEKGeneratedEvent, oneof: "event" },
    { no: 714, name: "user_external_identity_linked", kind: "message", T: UserExternalIdentityLinkedEvent, oneof: "event" },
    { no: 800, name: "rbac_role_created", kind: "message", T: RbacRoleCreatedEvent, oneof: "event" },
    { no: 801, name: "rbac_role_display_name_changed", kind: "message", T: RbacRoleDisplayNameChangedEvent, oneof: "event" },
    { no: 802, name: "rbac_role_description_changed", kind: "message", T: RbacRoleDescriptionChangedEvent, oneof: "event" },
    { no: 803, name: "rbac_role_deleted", kind: "message", T: RbacRoleDeletedEvent, oneof: "event" },
    { no: 804, name: "rbac_roles_reordered", kind: "message", T: RbacRolesReorderedEvent, oneof: "event" },
    { no: 805, name: "rbac_role_assigned", kind: "message", T: RbacRoleAssignedEvent, oneof: "event" },
    { no: 806, name: "rbac_role_revoked", kind: "message", T: RbacRoleRevokedEvent, oneof: "event" },
    { no: 810, name: "rbac_permission_granted", kind: "message", T: RbacPermissionGrantedEvent, oneof: "event" },
    { no: 811, name: "rbac_permission_denied", kind: "message", T: RbacPermissionDeniedEvent, oneof: "event" },
    { no: 812, name: "rbac_permission_cleared", kind: "message", T: RbacPermissionClearedEvent, oneof: "event" },
    { no: 813, name: "rbac_role_pingable_changed", kind: "message", T: RbacRolePingableChangedEvent, oneof: "event" },
    { no: 840, name: "room_member_banned", kind: "message", T: RoomMemberBannedEvent, oneof: "event" },
    { no: 841, name: "room_member_unbanned", kind: "message", T: RoomMemberUnbannedEvent, oneof: "event" },
    { no: 900, name: "registration_verification_code_issued", kind: "message", T: RegistrationVerificationCodeIssuedEvent, oneof: "event" },
    { no: 901, name: "email_verification_code_issued", kind: "message", T: EmailVerificationCodeIssuedEvent, oneof: "event" },
    { no: 902, name: "password_reset_link_issued", kind: "message", T: PasswordResetLinkIssuedEvent, oneof: "event" },
    { no: 903, name: "account_deletion_confirmation_issued", kind: "message", T: AccountDeletionConfirmationIssuedEvent, oneof: "event" },
    { no: 904, name: "password_reset_completed", kind: "message", T: PasswordResetCompletedEvent, oneof: "event" },
    { no: 905, name: "login_succeeded", kind: "message", T: LoginSucceededEvent, oneof: "event" },
    { no: 906, name: "login_failed", kind: "message", T: LoginFailedEvent, oneof: "event" },
    { no: 907, name: "logout_succeeded", kind: "message", T: LogoutSucceededEvent, oneof: "event" },
    { no: 908, name: "auth_code_issued", kind: "message", T: AuthCodeIssuedEvent, oneof: "event" },
    { no: 909, name: "auth_code_exchange_succeeded", kind: "message", T: AuthCodeExchangeSucceededEvent, oneof: "event" },
    { no: 910, name: "auth_code_exchange_failed", kind: "message", T: AuthCodeExchangeFailedEvent, oneof: "event" },
    { no: 911, name: "bearer_token_issued", kind: "message", T: BearerTokenIssuedEvent, oneof: "event" },
    { no: 912, name: "bearer_token_revoked", kind: "message", T: BearerTokenRevokedEvent, oneof: "event" },
    { no: 913, name: "oauth_consent_granted", kind: "message", T: OAuthConsentGrantedEvent, oneof: "event" },
    { no: 914, name: "oauth_consent_denied", kind: "message", T: OAuthConsentDeniedEvent, oneof: "event" },
    { no: 1050, name: "reaction_added", kind: "message", T: ReactionAddedEvent, oneof: "event" },
    { no: 1051, name: "reaction_removed", kind: "message", T: ReactionRemovedEvent, oneof: "event" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Event {
    return new Event().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Event {
    return new Event().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Event {
    return new Event().fromJsonString(jsonString, options);
  }

  static equals(a: Event | PlainMessage<Event> | undefined, b: Event | PlainMessage<Event> | undefined): boolean {
    return proto3.util.equals(Event, a, b);
  }
}

