// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file chatto/core/v1/push.proto (package chatto.core.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 *
 * PushSubscription stores the Web Push subscription data for a user's browser.
 *
 * Subscriptions are stored in the RUNTIME_STATE KV bucket with key format:
 * push_subscription.{userId}.{subscriptionHash}
 *
 * The subscriptionHash is derived from the endpoint URL to allow multiple
 * devices/browsers per user while preventing duplicate subscriptions.
 *
 * @generated from message chatto.core.v1.PushSubscription
 */
export class PushSubscription extends Message<PushSubscription> {
  /**
   * The push service endpoint URL (provided by the browser)
   *
   * @generated from field: string endpoint = 1;
   */
  endpoint = "";

  /**
   * The client's P-256 ECDH public key for message encryption (base64url-encoded)
   *
   * @generated from field: string p256dh = 2;
   */
  p256dh = "";

  /**
   * Authentication secret for message encryption (base64url-encoded)
   *
   * @generated from field: string auth = 3;
   */
  auth = "";

  /**
   * When this subscription was created
   *
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp;

  /**
   * User agent string (for debugging/device identification)
   *
   * @generated from field: string user_agent = 5;
   */
  userAgent = "";

  constructor(data?: PartialMessage<PushSubscription>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.core.v1.PushSubscription";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "endpoint", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "p256dh", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "auth", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "created_at", kind: "message", T: Timestamp },
    { no: 5, name: "user_agent", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PushSubscription {
    return new PushSubscription().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PushSubscription {
    return new PushSubscription().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PushSubscription {
    return new PushSubscription().fromJsonString(jsonString, options);
  }

  static equals(a: PushSubscription | PlainMessage<PushSubscription> | undefined, b: PushSubscription | PlainMessage<PushSubscription> | undefined): boolean {
    return proto3.util.equals(PushSubscription, a, b);
  }
}

