// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file chatto/core/v1/rbac_events.proto (package chatto.core.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum chatto.core.v1.RbacPermissionScopeKind
 */
export enum RbacPermissionScopeKind {
  /**
   * @generated from enum value: RBAC_PERMISSION_SCOPE_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: RBAC_PERMISSION_SCOPE_KIND_SERVER = 1;
   */
  SERVER = 1,

  /**
   * @generated from enum value: RBAC_PERMISSION_SCOPE_KIND_GROUP = 2;
   */
  GROUP = 2,

  /**
   * @generated from enum value: RBAC_PERMISSION_SCOPE_KIND_ROOM = 3;
   */
  ROOM = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(RbacPermissionScopeKind)
proto3.util.setEnumType(RbacPermissionScopeKind, "chatto.core.v1.RbacPermissionScopeKind", [
  { no: 0, name: "RBAC_PERMISSION_SCOPE_KIND_UNSPECIFIED" },
  { no: 1, name: "RBAC_PERMISSION_SCOPE_KIND_SERVER" },
  { no: 2, name: "RBAC_PERMISSION_SCOPE_KIND_GROUP" },
  { no: 3, name: "RBAC_PERMISSION_SCOPE_KIND_ROOM" },
]);

/**
 * @generated from enum chatto.core.v1.RbacPermissionSubjectKind
 */
export enum RbacPermissionSubjectKind {
  /**
   * @generated from enum value: RBAC_PERMISSION_SUBJECT_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: RBAC_PERMISSION_SUBJECT_KIND_ROLE = 1;
   */
  ROLE = 1,

  /**
   * @generated from enum value: RBAC_PERMISSION_SUBJECT_KIND_USER = 2;
   */
  USER = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(RbacPermissionSubjectKind)
proto3.util.setEnumType(RbacPermissionSubjectKind, "chatto.core.v1.RbacPermissionSubjectKind", [
  { no: 0, name: "RBAC_PERMISSION_SUBJECT_KIND_UNSPECIFIED" },
  { no: 1, name: "RBAC_PERMISSION_SUBJECT_KIND_ROLE" },
  { no: 2, name: "RBAC_PERMISSION_SUBJECT_KIND_USER" },
]);

/**
 * @generated from message chatto.core.v1.RbacRoleCreatedEvent
 */
export class RbacRoleCreatedEvent extends Message<RbacRoleCreatedEvent> {
  /**
   * @generated from field: string role_name = 1;
   */
  roleName = "";

  /**
   * @generated from field: string display_name = 2;
   */
  displayName = "";

  /**
   * @generated from field: string description = 3;
   */
  description = "";

  /**
   * @generated from field: int32 rank = 4;
   */
  rank = 0;

  /**
   * @generated from field: bool pingable = 5;
   */
  pingable = false;

  constructor(data?: PartialMessage<RbacRoleCreatedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.core.v1.RbacRoleCreatedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "role_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "rank", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "pingable", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RbacRoleCreatedEvent {
    return new RbacRoleCreatedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RbacRoleCreatedEvent {
    return new RbacRoleCreatedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RbacRoleCreatedEvent {
    return new RbacRoleCreatedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RbacRoleCreatedEvent | PlainMessage<RbacRoleCreatedEvent> | undefined, b: RbacRoleCreatedEvent | PlainMessage<RbacRoleCreatedEvent> | undefined): boolean {
    return proto3.util.equals(RbacRoleCreatedEvent, a, b);
  }
}

/**
 * @generated from message chatto.core.v1.RbacRoleDisplayNameChangedEvent
 */
export class RbacRoleDisplayNameChangedEvent extends Message<RbacRoleDisplayNameChangedEvent> {
  /**
   * @generated from field: string role_name = 1;
   */
  roleName = "";

  /**
   * @generated from field: string display_name = 2;
   */
  displayName = "";

  constructor(data?: PartialMessage<RbacRoleDisplayNameChangedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.core.v1.RbacRoleDisplayNameChangedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "role_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RbacRoleDisplayNameChangedEvent {
    return new RbacRoleDisplayNameChangedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RbacRoleDisplayNameChangedEvent {
    return new RbacRoleDisplayNameChangedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RbacRoleDisplayNameChangedEvent {
    return new RbacRoleDisplayNameChangedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RbacRoleDisplayNameChangedEvent | PlainMessage<RbacRoleDisplayNameChangedEvent> | undefined, b: RbacRoleDisplayNameChangedEvent | PlainMessage<RbacRoleDisplayNameChangedEvent> | undefined): boolean {
    return proto3.util.equals(RbacRoleDisplayNameChangedEvent, a, b);
  }
}

/**
 * @generated from message chatto.core.v1.RbacRoleDescriptionChangedEvent
 */
export class RbacRoleDescriptionChangedEvent extends Message<RbacRoleDescriptionChangedEvent> {
  /**
   * @generated from field: string role_name = 1;
   */
  roleName = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  constructor(data?: PartialMessage<RbacRoleDescriptionChangedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.core.v1.RbacRoleDescriptionChangedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "role_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RbacRoleDescriptionChangedEvent {
    return new RbacRoleDescriptionChangedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RbacRoleDescriptionChangedEvent {
    return new RbacRoleDescriptionChangedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RbacRoleDescriptionChangedEvent {
    return new RbacRoleDescriptionChangedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RbacRoleDescriptionChangedEvent | PlainMessage<RbacRoleDescriptionChangedEvent> | undefined, b: RbacRoleDescriptionChangedEvent | PlainMessage<RbacRoleDescriptionChangedEvent> | undefined): boolean {
    return proto3.util.equals(RbacRoleDescriptionChangedEvent, a, b);
  }
}

/**
 * @generated from message chatto.core.v1.RbacRolePingableChangedEvent
 */
export class RbacRolePingableChangedEvent extends Message<RbacRolePingableChangedEvent> {
  /**
   * @generated from field: string role_name = 1;
   */
  roleName = "";

  /**
   * @generated from field: bool pingable = 2;
   */
  pingable = false;

  constructor(data?: PartialMessage<RbacRolePingableChangedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.core.v1.RbacRolePingableChangedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "role_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "pingable", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RbacRolePingableChangedEvent {
    return new RbacRolePingableChangedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RbacRolePingableChangedEvent {
    return new RbacRolePingableChangedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RbacRolePingableChangedEvent {
    return new RbacRolePingableChangedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RbacRolePingableChangedEvent | PlainMessage<RbacRolePingableChangedEvent> | undefined, b: RbacRolePingableChangedEvent | PlainMessage<RbacRolePingableChangedEvent> | undefined): boolean {
    return proto3.util.equals(RbacRolePingableChangedEvent, a, b);
  }
}

/**
 * @generated from message chatto.core.v1.RbacRoleDeletedEvent
 */
export class RbacRoleDeletedEvent extends Message<RbacRoleDeletedEvent> {
  /**
   * @generated from field: string role_name = 1;
   */
  roleName = "";

  constructor(data?: PartialMessage<RbacRoleDeletedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.core.v1.RbacRoleDeletedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "role_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RbacRoleDeletedEvent {
    return new RbacRoleDeletedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RbacRoleDeletedEvent {
    return new RbacRoleDeletedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RbacRoleDeletedEvent {
    return new RbacRoleDeletedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RbacRoleDeletedEvent | PlainMessage<RbacRoleDeletedEvent> | undefined, b: RbacRoleDeletedEvent | PlainMessage<RbacRoleDeletedEvent> | undefined): boolean {
    return proto3.util.equals(RbacRoleDeletedEvent, a, b);
  }
}

/**
 * @generated from message chatto.core.v1.RbacRolesReorderedEvent
 */
export class RbacRolesReorderedEvent extends Message<RbacRolesReorderedEvent> {
  /**
   * @generated from field: repeated string role_names = 1;
   */
  roleNames: string[] = [];

  constructor(data?: PartialMessage<RbacRolesReorderedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.core.v1.RbacRolesReorderedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "role_names", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RbacRolesReorderedEvent {
    return new RbacRolesReorderedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RbacRolesReorderedEvent {
    return new RbacRolesReorderedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RbacRolesReorderedEvent {
    return new RbacRolesReorderedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RbacRolesReorderedEvent | PlainMessage<RbacRolesReorderedEvent> | undefined, b: RbacRolesReorderedEvent | PlainMessage<RbacRolesReorderedEvent> | undefined): boolean {
    return proto3.util.equals(RbacRolesReorderedEvent, a, b);
  }
}

/**
 * @generated from message chatto.core.v1.RbacRoleAssignedEvent
 */
export class RbacRoleAssignedEvent extends Message<RbacRoleAssignedEvent> {
  /**
   * @generated from field: string user_id = 1;
   */
  userId = "";

  /**
   * @generated from field: string role_name = 2;
   */
  roleName = "";

  constructor(data?: PartialMessage<RbacRoleAssignedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.core.v1.RbacRoleAssignedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "role_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RbacRoleAssignedEvent {
    return new RbacRoleAssignedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RbacRoleAssignedEvent {
    return new RbacRoleAssignedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RbacRoleAssignedEvent {
    return new RbacRoleAssignedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RbacRoleAssignedEvent | PlainMessage<RbacRoleAssignedEvent> | undefined, b: RbacRoleAssignedEvent | PlainMessage<RbacRoleAssignedEvent> | undefined): boolean {
    return proto3.util.equals(RbacRoleAssignedEvent, a, b);
  }
}

/**
 * @generated from message chatto.core.v1.RbacRoleRevokedEvent
 */
export class RbacRoleRevokedEvent extends Message<RbacRoleRevokedEvent> {
  /**
   * @generated from field: string user_id = 1;
   */
  userId = "";

  /**
   * @generated from field: string role_name = 2;
   */
  roleName = "";

  constructor(data?: PartialMessage<RbacRoleRevokedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.core.v1.RbacRoleRevokedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "role_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RbacRoleRevokedEvent {
    return new RbacRoleRevokedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RbacRoleRevokedEvent {
    return new RbacRoleRevokedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RbacRoleRevokedEvent {
    return new RbacRoleRevokedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RbacRoleRevokedEvent | PlainMessage<RbacRoleRevokedEvent> | undefined, b: RbacRoleRevokedEvent | PlainMessage<RbacRoleRevokedEvent> | undefined): boolean {
    return proto3.util.equals(RbacRoleRevokedEvent, a, b);
  }
}

/**
 * @generated from message chatto.core.v1.RbacPermissionScope
 */
export class RbacPermissionScope extends Message<RbacPermissionScope> {
  /**
   * @generated from field: chatto.core.v1.RbacPermissionScopeKind kind = 1;
   */
  kind = RbacPermissionScopeKind.UNSPECIFIED;

  /**
   * Empty for server-scope decisions. For group and room scope, this is the
   * target group ID or room ID.
   *
   * @generated from field: string id = 2;
   */
  id = "";

  constructor(data?: PartialMessage<RbacPermissionScope>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.core.v1.RbacPermissionScope";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "kind", kind: "enum", T: proto3.getEnumType(RbacPermissionScopeKind) },
    { no: 2, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RbacPermissionScope {
    return new RbacPermissionScope().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RbacPermissionScope {
    return new RbacPermissionScope().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RbacPermissionScope {
    return new RbacPermissionScope().fromJsonString(jsonString, options);
  }

  static equals(a: RbacPermissionScope | PlainMessage<RbacPermissionScope> | undefined, b: RbacPermissionScope | PlainMessage<RbacPermissionScope> | undefined): boolean {
    return proto3.util.equals(RbacPermissionScope, a, b);
  }
}

/**
 * @generated from message chatto.core.v1.RbacPermissionSubject
 */
export class RbacPermissionSubject extends Message<RbacPermissionSubject> {
  /**
   * @generated from field: chatto.core.v1.RbacPermissionSubjectKind kind = 1;
   */
  kind = RbacPermissionSubjectKind.UNSPECIFIED;

  /**
   * Role name for ROLE subjects; user ID for USER subjects.
   *
   * @generated from field: string id = 2;
   */
  id = "";

  constructor(data?: PartialMessage<RbacPermissionSubject>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.core.v1.RbacPermissionSubject";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "kind", kind: "enum", T: proto3.getEnumType(RbacPermissionSubjectKind) },
    { no: 2, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RbacPermissionSubject {
    return new RbacPermissionSubject().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RbacPermissionSubject {
    return new RbacPermissionSubject().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RbacPermissionSubject {
    return new RbacPermissionSubject().fromJsonString(jsonString, options);
  }

  static equals(a: RbacPermissionSubject | PlainMessage<RbacPermissionSubject> | undefined, b: RbacPermissionSubject | PlainMessage<RbacPermissionSubject> | undefined): boolean {
    return proto3.util.equals(RbacPermissionSubject, a, b);
  }
}

/**
 * @generated from message chatto.core.v1.RbacPermissionGrantedEvent
 */
export class RbacPermissionGrantedEvent extends Message<RbacPermissionGrantedEvent> {
  /**
   * @generated from field: string permission = 3;
   */
  permission = "";

  /**
   * @generated from field: chatto.core.v1.RbacPermissionScope scope = 4;
   */
  scope?: RbacPermissionScope;

  /**
   * @generated from field: chatto.core.v1.RbacPermissionSubject subject = 5;
   */
  subject?: RbacPermissionSubject;

  constructor(data?: PartialMessage<RbacPermissionGrantedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.core.v1.RbacPermissionGrantedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 3, name: "permission", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "scope", kind: "message", T: RbacPermissionScope },
    { no: 5, name: "subject", kind: "message", T: RbacPermissionSubject },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RbacPermissionGrantedEvent {
    return new RbacPermissionGrantedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RbacPermissionGrantedEvent {
    return new RbacPermissionGrantedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RbacPermissionGrantedEvent {
    return new RbacPermissionGrantedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RbacPermissionGrantedEvent | PlainMessage<RbacPermissionGrantedEvent> | undefined, b: RbacPermissionGrantedEvent | PlainMessage<RbacPermissionGrantedEvent> | undefined): boolean {
    return proto3.util.equals(RbacPermissionGrantedEvent, a, b);
  }
}

/**
 * @generated from message chatto.core.v1.RbacPermissionDeniedEvent
 */
export class RbacPermissionDeniedEvent extends Message<RbacPermissionDeniedEvent> {
  /**
   * @generated from field: string permission = 3;
   */
  permission = "";

  /**
   * @generated from field: chatto.core.v1.RbacPermissionScope scope = 4;
   */
  scope?: RbacPermissionScope;

  /**
   * @generated from field: chatto.core.v1.RbacPermissionSubject subject = 5;
   */
  subject?: RbacPermissionSubject;

  constructor(data?: PartialMessage<RbacPermissionDeniedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.core.v1.RbacPermissionDeniedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 3, name: "permission", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "scope", kind: "message", T: RbacPermissionScope },
    { no: 5, name: "subject", kind: "message", T: RbacPermissionSubject },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RbacPermissionDeniedEvent {
    return new RbacPermissionDeniedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RbacPermissionDeniedEvent {
    return new RbacPermissionDeniedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RbacPermissionDeniedEvent {
    return new RbacPermissionDeniedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RbacPermissionDeniedEvent | PlainMessage<RbacPermissionDeniedEvent> | undefined, b: RbacPermissionDeniedEvent | PlainMessage<RbacPermissionDeniedEvent> | undefined): boolean {
    return proto3.util.equals(RbacPermissionDeniedEvent, a, b);
  }
}

/**
 * Removes any explicit allow or deny, returning this permission to inherited/no-decision state.
 *
 * @generated from message chatto.core.v1.RbacPermissionClearedEvent
 */
export class RbacPermissionClearedEvent extends Message<RbacPermissionClearedEvent> {
  /**
   * @generated from field: string permission = 3;
   */
  permission = "";

  /**
   * @generated from field: chatto.core.v1.RbacPermissionScope scope = 4;
   */
  scope?: RbacPermissionScope;

  /**
   * @generated from field: chatto.core.v1.RbacPermissionSubject subject = 5;
   */
  subject?: RbacPermissionSubject;

  constructor(data?: PartialMessage<RbacPermissionClearedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.core.v1.RbacPermissionClearedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 3, name: "permission", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "scope", kind: "message", T: RbacPermissionScope },
    { no: 5, name: "subject", kind: "message", T: RbacPermissionSubject },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RbacPermissionClearedEvent {
    return new RbacPermissionClearedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RbacPermissionClearedEvent {
    return new RbacPermissionClearedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RbacPermissionClearedEvent {
    return new RbacPermissionClearedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RbacPermissionClearedEvent | PlainMessage<RbacPermissionClearedEvent> | undefined, b: RbacPermissionClearedEvent | PlainMessage<RbacPermissionClearedEvent> | undefined): boolean {
    return proto3.util.equals(RbacPermissionClearedEvent, a, b);
  }
}

