// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file chatto/core/v1/user_preferences.proto (package chatto.core.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * TimeFormat controls how times are displayed to the user.
 *
 * @generated from enum chatto.core.v1.TimeFormat
 */
export enum TimeFormat {
  /**
   * Not set - use browser/locale default.
   *
   * @generated from enum value: TIME_FORMAT_UNSPECIFIED = 0;
   */
  TIME_FORMAT_UNSPECIFIED = 0,

  /**
   * 12-hour format (e.g., 2:30 PM).
   *
   * @generated from enum value: TIME_FORMAT_12H = 1;
   */
  TIME_FORMAT_12H = 1,

  /**
   * 24-hour format (e.g., 14:30).
   *
   * @generated from enum value: TIME_FORMAT_24H = 2;
   */
  TIME_FORMAT_24H = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(TimeFormat)
proto3.util.setEnumType(TimeFormat, "chatto.core.v1.TimeFormat", [
  { no: 0, name: "TIME_FORMAT_UNSPECIFIED" },
  { no: 1, name: "TIME_FORMAT_12H" },
  { no: 2, name: "TIME_FORMAT_24H" },
]);

/**
 * NotificationLevel controls how a user receives notifications for a space or room.
 * Stored per-user per-space (and optionally per-room) in the space's CONFIG KV bucket.
 *
 * @generated from enum chatto.core.v1.NotificationLevel
 */
export enum NotificationLevel {
  /**
   * Use inherited default (server default for rooms, NORMAL for server).
   *
   * @generated from enum value: NOTIFICATION_LEVEL_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Suppress all notifications and unread markers.
   *
   * @generated from enum value: NOTIFICATION_LEVEL_MUTED = 1;
   */
  MUTED = 1,

  /**
   * Standard behavior: unread markers + notifications for mentions/DMs/threads.
   *
   * @generated from enum value: NOTIFICATION_LEVEL_NORMAL = 2;
   */
  NORMAL = 2,

  /**
   * Like NORMAL, plus a notification for every new root message in the room.
   *
   * @generated from enum value: NOTIFICATION_LEVEL_ALL_MESSAGES = 3;
   */
  ALL_MESSAGES = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(NotificationLevel)
proto3.util.setEnumType(NotificationLevel, "chatto.core.v1.NotificationLevel", [
  { no: 0, name: "NOTIFICATION_LEVEL_UNSPECIFIED" },
  { no: 1, name: "NOTIFICATION_LEVEL_MUTED" },
  { no: 2, name: "NOTIFICATION_LEVEL_NORMAL" },
  { no: 3, name: "NOTIFICATION_LEVEL_ALL_MESSAGES" },
]);

/**
 * ServerUserPreferences stores per-user display preferences at the server level.
 * Stored in INSTANCE KV bucket with key "user_preferences.{userId}" (legacy
 * names retained per ADR-029).
 * All fields are optional - absence means "use browser/locale default".
 *
 * @generated from message chatto.core.v1.ServerUserPreferences
 */
export class ServerUserPreferences extends Message<ServerUserPreferences> {
  /**
   * IANA timezone name (e.g., "America/New_York", "Europe/Berlin").
   * If absent or empty, the frontend uses the browser's local timezone.
   *
   * @generated from field: optional string timezone = 1;
   */
  timezone?: string;

  /**
   * Preferred time display format.
   * TIME_FORMAT_UNSPECIFIED means the frontend uses the browser's locale default.
   *
   * @generated from field: chatto.core.v1.TimeFormat time_format = 2;
   */
  timeFormat = TimeFormat.TIME_FORMAT_UNSPECIFIED;

  constructor(data?: PartialMessage<ServerUserPreferences>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.core.v1.ServerUserPreferences";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "timezone", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "time_format", kind: "enum", T: proto3.getEnumType(TimeFormat) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServerUserPreferences {
    return new ServerUserPreferences().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServerUserPreferences {
    return new ServerUserPreferences().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServerUserPreferences {
    return new ServerUserPreferences().fromJsonString(jsonString, options);
  }

  static equals(a: ServerUserPreferences | PlainMessage<ServerUserPreferences> | undefined, b: ServerUserPreferences | PlainMessage<ServerUserPreferences> | undefined): boolean {
    return proto3.util.equals(ServerUserPreferences, a, b);
  }
}

/**
 * UserPreferences stores per-user preferences scoped to the server.
 * Stored in the server's CONFIG KV bucket with key "user_preferences.{userId}".
 *
 * @generated from message chatto.core.v1.UserPreferences
 */
export class UserPreferences extends Message<UserPreferences> {
  /**
   * Notification level for the server (UNSPECIFIED = inherit system default of NORMAL).
   *
   * @generated from field: chatto.core.v1.NotificationLevel notification_level = 1;
   */
  notificationLevel = NotificationLevel.UNSPECIFIED;

  constructor(data?: PartialMessage<UserPreferences>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.core.v1.UserPreferences";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "notification_level", kind: "enum", T: proto3.getEnumType(NotificationLevel) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserPreferences {
    return new UserPreferences().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserPreferences {
    return new UserPreferences().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserPreferences {
    return new UserPreferences().fromJsonString(jsonString, options);
  }

  static equals(a: UserPreferences | PlainMessage<UserPreferences> | undefined, b: UserPreferences | PlainMessage<UserPreferences> | undefined): boolean {
    return proto3.util.equals(UserPreferences, a, b);
  }
}

/**
 * RoomUserPreferences stores per-user preferences for a room within a space.
 * Stored in SPACE_{spaceId}_CONFIG KV bucket with key "room_user_preferences.{userId}.{roomId}".
 *
 * @generated from message chatto.core.v1.RoomUserPreferences
 */
export class RoomUserPreferences extends Message<RoomUserPreferences> {
  /**
   * Notification level for the room (UNSPECIFIED = inherit from server preference).
   *
   * @generated from field: chatto.core.v1.NotificationLevel notification_level = 1;
   */
  notificationLevel = NotificationLevel.UNSPECIFIED;

  constructor(data?: PartialMessage<RoomUserPreferences>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.core.v1.RoomUserPreferences";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "notification_level", kind: "enum", T: proto3.getEnumType(NotificationLevel) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoomUserPreferences {
    return new RoomUserPreferences().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoomUserPreferences {
    return new RoomUserPreferences().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoomUserPreferences {
    return new RoomUserPreferences().fromJsonString(jsonString, options);
  }

  static equals(a: RoomUserPreferences | PlainMessage<RoomUserPreferences> | undefined, b: RoomUserPreferences | PlainMessage<RoomUserPreferences> | undefined): boolean {
    return proto3.util.equals(RoomUserPreferences, a, b);
  }
}

