// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/api/v1/chat.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "hmans.de/chatto/internal/pb/chatto/core/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Viewer is the current authenticated user context.
type Viewer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *v1.User               `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Viewer) Reset() {
	*x = Viewer{}
	mi := &file_chatto_api_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Viewer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Viewer) ProtoMessage() {}

func (x *Viewer) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Viewer.ProtoReflect.Descriptor instead.
func (*Viewer) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *Viewer) GetUser() *v1.User {
	if x != nil {
		return x.User
	}
	return nil
}

// GetViewerRequest requests the current authenticated user.
type GetViewerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetViewerRequest) Reset() {
	*x = GetViewerRequest{}
	mi := &file_chatto_api_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetViewerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetViewerRequest) ProtoMessage() {}

func (x *GetViewerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetViewerRequest.ProtoReflect.Descriptor instead.
func (*GetViewerRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_chat_proto_rawDescGZIP(), []int{1}
}

// GetViewerResponse returns the current authenticated user.
type GetViewerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Viewer        *Viewer                `protobuf:"bytes,1,opt,name=viewer,proto3" json:"viewer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetViewerResponse) Reset() {
	*x = GetViewerResponse{}
	mi := &file_chatto_api_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetViewerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetViewerResponse) ProtoMessage() {}

func (x *GetViewerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetViewerResponse.ProtoReflect.Descriptor instead.
func (*GetViewerResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *GetViewerResponse) GetViewer() *Viewer {
	if x != nil {
		return x.Viewer
	}
	return nil
}

// ListMyRoomsRequest requests rooms the current user participates in.
type ListMyRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          v1.RoomKind            `protobuf:"varint,1,opt,name=kind,proto3,enum=chatto.core.v1.RoomKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyRoomsRequest) Reset() {
	*x = ListMyRoomsRequest{}
	mi := &file_chatto_api_v1_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyRoomsRequest) ProtoMessage() {}

func (x *ListMyRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyRoomsRequest.ProtoReflect.Descriptor instead.
func (*ListMyRoomsRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ListMyRoomsRequest) GetKind() v1.RoomKind {
	if x != nil {
		return x.Kind
	}
	return v1.RoomKind(0)
}

// ListMyRoomsResponse returns rooms the current user participates in.
type ListMyRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*v1.Room             `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyRoomsResponse) Reset() {
	*x = ListMyRoomsResponse{}
	mi := &file_chatto_api_v1_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyRoomsResponse) ProtoMessage() {}

func (x *ListMyRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyRoomsResponse.ProtoReflect.Descriptor instead.
func (*ListMyRoomsResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_chat_proto_rawDescGZIP(), []int{4}
}

func (x *ListMyRoomsResponse) GetRooms() []*v1.Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

// GetRoomTimelineRequest requests visible room timeline events.
type GetRoomTimelineRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoomId         string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Limit          int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	BeforeSequence uint64                 `protobuf:"varint,3,opt,name=before_sequence,json=beforeSequence,proto3" json:"before_sequence,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRoomTimelineRequest) Reset() {
	*x = GetRoomTimelineRequest{}
	mi := &file_chatto_api_v1_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomTimelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomTimelineRequest) ProtoMessage() {}

func (x *GetRoomTimelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomTimelineRequest.ProtoReflect.Descriptor instead.
func (*GetRoomTimelineRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_chat_proto_rawDescGZIP(), []int{5}
}

func (x *GetRoomTimelineRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetRoomTimelineRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetRoomTimelineRequest) GetBeforeSequence() uint64 {
	if x != nil {
		return x.BeforeSequence
	}
	return 0
}

// TimelineEvent pairs a room event with its EVT stream sequence.
type TimelineEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *v1.Event              `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineEvent) Reset() {
	*x = TimelineEvent{}
	mi := &file_chatto_api_v1_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineEvent) ProtoMessage() {}

func (x *TimelineEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineEvent.ProtoReflect.Descriptor instead.
func (*TimelineEvent) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_chat_proto_rawDescGZIP(), []int{6}
}

func (x *TimelineEvent) GetEvent() *v1.Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *TimelineEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// GetRoomTimelineResponse returns a page of room timeline events.
type GetRoomTimelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*TimelineEvent       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	HasOlder      bool                   `protobuf:"varint,2,opt,name=has_older,json=hasOlder,proto3" json:"has_older,omitempty"`
	HasNewer      bool                   `protobuf:"varint,3,opt,name=has_newer,json=hasNewer,proto3" json:"has_newer,omitempty"`
	StartSequence uint64                 `protobuf:"varint,4,opt,name=start_sequence,json=startSequence,proto3" json:"start_sequence,omitempty"`
	EndSequence   uint64                 `protobuf:"varint,5,opt,name=end_sequence,json=endSequence,proto3" json:"end_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomTimelineResponse) Reset() {
	*x = GetRoomTimelineResponse{}
	mi := &file_chatto_api_v1_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomTimelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomTimelineResponse) ProtoMessage() {}

func (x *GetRoomTimelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomTimelineResponse.ProtoReflect.Descriptor instead.
func (*GetRoomTimelineResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_chat_proto_rawDescGZIP(), []int{7}
}

func (x *GetRoomTimelineResponse) GetEvents() []*TimelineEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetRoomTimelineResponse) GetHasOlder() bool {
	if x != nil {
		return x.HasOlder
	}
	return false
}

func (x *GetRoomTimelineResponse) GetHasNewer() bool {
	if x != nil {
		return x.HasNewer
	}
	return false
}

func (x *GetRoomTimelineResponse) GetStartSequence() uint64 {
	if x != nil {
		return x.StartSequence
	}
	return 0
}

func (x *GetRoomTimelineResponse) GetEndSequence() uint64 {
	if x != nil {
		return x.EndSequence
	}
	return 0
}

// PostMessageRequest posts a message into a room.
type PostMessageRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	RoomId                string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Body                  string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	ThreadRootEventId     string                 `protobuf:"bytes,3,opt,name=thread_root_event_id,json=threadRootEventId,proto3" json:"thread_root_event_id,omitempty"`
	InReplyToEventId      string                 `protobuf:"bytes,4,opt,name=in_reply_to_event_id,json=inReplyToEventId,proto3" json:"in_reply_to_event_id,omitempty"`
	AlsoSendToChannel     bool                   `protobuf:"varint,5,opt,name=also_send_to_channel,json=alsoSendToChannel,proto3" json:"also_send_to_channel,omitempty"`
	LargeMentionConfirmed bool                   `protobuf:"varint,6,opt,name=large_mention_confirmed,json=largeMentionConfirmed,proto3" json:"large_mention_confirmed,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PostMessageRequest) Reset() {
	*x = PostMessageRequest{}
	mi := &file_chatto_api_v1_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMessageRequest) ProtoMessage() {}

func (x *PostMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMessageRequest.ProtoReflect.Descriptor instead.
func (*PostMessageRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_chat_proto_rawDescGZIP(), []int{8}
}

func (x *PostMessageRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PostMessageRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *PostMessageRequest) GetThreadRootEventId() string {
	if x != nil {
		return x.ThreadRootEventId
	}
	return ""
}

func (x *PostMessageRequest) GetInReplyToEventId() string {
	if x != nil {
		return x.InReplyToEventId
	}
	return ""
}

func (x *PostMessageRequest) GetAlsoSendToChannel() bool {
	if x != nil {
		return x.AlsoSendToChannel
	}
	return false
}

func (x *PostMessageRequest) GetLargeMentionConfirmed() bool {
	if x != nil {
		return x.LargeMentionConfirmed
	}
	return false
}

// PostMessageResponse returns the committed message event.
type PostMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *v1.Event              `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostMessageResponse) Reset() {
	*x = PostMessageResponse{}
	mi := &file_chatto_api_v1_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMessageResponse) ProtoMessage() {}

func (x *PostMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMessageResponse.ProtoReflect.Descriptor instead.
func (*PostMessageResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_chat_proto_rawDescGZIP(), []int{9}
}

func (x *PostMessageResponse) GetEvent() *v1.Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *PostMessageResponse) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// SendTypingIndicatorRequest publishes a transient typing signal.
type SendTypingIndicatorRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RoomId            string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ThreadRootEventId string                 `protobuf:"bytes,2,opt,name=thread_root_event_id,json=threadRootEventId,proto3" json:"thread_root_event_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SendTypingIndicatorRequest) Reset() {
	*x = SendTypingIndicatorRequest{}
	mi := &file_chatto_api_v1_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTypingIndicatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTypingIndicatorRequest) ProtoMessage() {}

func (x *SendTypingIndicatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTypingIndicatorRequest.ProtoReflect.Descriptor instead.
func (*SendTypingIndicatorRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_chat_proto_rawDescGZIP(), []int{10}
}

func (x *SendTypingIndicatorRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SendTypingIndicatorRequest) GetThreadRootEventId() string {
	if x != nil {
		return x.ThreadRootEventId
	}
	return ""
}

// SendTypingIndicatorResponse is empty on success.
type SendTypingIndicatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTypingIndicatorResponse) Reset() {
	*x = SendTypingIndicatorResponse{}
	mi := &file_chatto_api_v1_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTypingIndicatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTypingIndicatorResponse) ProtoMessage() {}

func (x *SendTypingIndicatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTypingIndicatorResponse.ProtoReflect.Descriptor instead.
func (*SendTypingIndicatorResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_chat_proto_rawDescGZIP(), []int{11}
}

var File_chatto_api_v1_chat_proto protoreflect.FileDescriptor

const file_chatto_api_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x18chatto/api/v1/chat.proto\x12\rchatto.api.v1\x1a\x1achatto/core/v1/event.proto\x1a\x1bchatto/core/v1/models.proto\"2\n" +
	"\x06Viewer\x12(\n" +
	"\x04user\x18\x01 \x01(\v2\x14.chatto.core.v1.UserR\x04user\"\x12\n" +
	"\x10GetViewerRequest\"B\n" +
	"\x11GetViewerResponse\x12-\n" +
	"\x06viewer\x18\x01 \x01(\v2\x15.chatto.api.v1.ViewerR\x06viewer\"B\n" +
	"\x12ListMyRoomsRequest\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.chatto.core.v1.RoomKindR\x04kind\"A\n" +
	"\x13ListMyRoomsResponse\x12*\n" +
	"\x05rooms\x18\x01 \x03(\v2\x14.chatto.core.v1.RoomR\x05rooms\"p\n" +
	"\x16GetRoomTimelineRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12'\n" +
	"\x0fbefore_sequence\x18\x03 \x01(\x04R\x0ebeforeSequence\"X\n" +
	"\rTimelineEvent\x12+\n" +
	"\x05event\x18\x01 \x01(\v2\x15.chatto.core.v1.EventR\x05event\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\"\xd3\x01\n" +
	"\x17GetRoomTimelineResponse\x124\n" +
	"\x06events\x18\x01 \x03(\v2\x1c.chatto.api.v1.TimelineEventR\x06events\x12\x1b\n" +
	"\thas_older\x18\x02 \x01(\bR\bhasOlder\x12\x1b\n" +
	"\thas_newer\x18\x03 \x01(\bR\bhasNewer\x12%\n" +
	"\x0estart_sequence\x18\x04 \x01(\x04R\rstartSequence\x12!\n" +
	"\fend_sequence\x18\x05 \x01(\x04R\vendSequence\"\x8b\x02\n" +
	"\x12PostMessageRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12/\n" +
	"\x14thread_root_event_id\x18\x03 \x01(\tR\x11threadRootEventId\x12.\n" +
	"\x14in_reply_to_event_id\x18\x04 \x01(\tR\x10inReplyToEventId\x12/\n" +
	"\x14also_send_to_channel\x18\x05 \x01(\bR\x11alsoSendToChannel\x126\n" +
	"\x17large_mention_confirmed\x18\x06 \x01(\bR\x15largeMentionConfirmed\"^\n" +
	"\x13PostMessageResponse\x12+\n" +
	"\x05event\x18\x01 \x01(\v2\x15.chatto.core.v1.EventR\x05event\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\"f\n" +
	"\x1aSendTypingIndicatorRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12/\n" +
	"\x14thread_root_event_id\x18\x02 \x01(\tR\x11threadRootEventId\"\x1d\n" +
	"\x1bSendTypingIndicatorResponse2\xde\x03\n" +
	"\x10ChattoApiService\x12N\n" +
	"\tGetViewer\x12\x1f.chatto.api.v1.GetViewerRequest\x1a .chatto.api.v1.GetViewerResponse\x12T\n" +
	"\vListMyRooms\x12!.chatto.api.v1.ListMyRoomsRequest\x1a\".chatto.api.v1.ListMyRoomsResponse\x12`\n" +
	"\x0fGetRoomTimeline\x12%.chatto.api.v1.GetRoomTimelineRequest\x1a&.chatto.api.v1.GetRoomTimelineResponse\x12T\n" +
	"\vPostMessage\x12!.chatto.api.v1.PostMessageRequest\x1a\".chatto.api.v1.PostMessageResponse\x12l\n" +
	"\x13SendTypingIndicator\x12).chatto.api.v1.SendTypingIndicatorRequest\x1a*.chatto.api.v1.SendTypingIndicatorResponseB\xa5\x01\n" +
	"\x11com.chatto.api.v1B\tChatProtoP\x01Z/hmans.de/chatto/internal/pb/chatto/api/v1;apiv1\xa2\x02\x03CAX\xaa\x02\rChatto.Api.V1\xca\x02\rChatto\\Api\\V1\xe2\x02\x19Chatto\\Api\\V1\\GPBMetadata\xea\x02\x0fChatto::Api::V1b\x06proto3"

var (
	file_chatto_api_v1_chat_proto_rawDescOnce sync.Once
	file_chatto_api_v1_chat_proto_rawDescData []byte
)

func file_chatto_api_v1_chat_proto_rawDescGZIP() []byte {
	file_chatto_api_v1_chat_proto_rawDescOnce.Do(func() {
		file_chatto_api_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_api_v1_chat_proto_rawDesc), len(file_chatto_api_v1_chat_proto_rawDesc)))
	})
	return file_chatto_api_v1_chat_proto_rawDescData
}

var file_chatto_api_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_chatto_api_v1_chat_proto_goTypes = []any{
	(*Viewer)(nil),                      // 0: chatto.api.v1.Viewer
	(*GetViewerRequest)(nil),            // 1: chatto.api.v1.GetViewerRequest
	(*GetViewerResponse)(nil),           // 2: chatto.api.v1.GetViewerResponse
	(*ListMyRoomsRequest)(nil),          // 3: chatto.api.v1.ListMyRoomsRequest
	(*ListMyRoomsResponse)(nil),         // 4: chatto.api.v1.ListMyRoomsResponse
	(*GetRoomTimelineRequest)(nil),      // 5: chatto.api.v1.GetRoomTimelineRequest
	(*TimelineEvent)(nil),               // 6: chatto.api.v1.TimelineEvent
	(*GetRoomTimelineResponse)(nil),     // 7: chatto.api.v1.GetRoomTimelineResponse
	(*PostMessageRequest)(nil),          // 8: chatto.api.v1.PostMessageRequest
	(*PostMessageResponse)(nil),         // 9: chatto.api.v1.PostMessageResponse
	(*SendTypingIndicatorRequest)(nil),  // 10: chatto.api.v1.SendTypingIndicatorRequest
	(*SendTypingIndicatorResponse)(nil), // 11: chatto.api.v1.SendTypingIndicatorResponse
	(*v1.User)(nil),                     // 12: chatto.core.v1.User
	(v1.RoomKind)(0),                    // 13: chatto.core.v1.RoomKind
	(*v1.Room)(nil),                     // 14: chatto.core.v1.Room
	(*v1.Event)(nil),                    // 15: chatto.core.v1.Event
}
var file_chatto_api_v1_chat_proto_depIdxs = []int32{
	12, // 0: chatto.api.v1.Viewer.user:type_name -> chatto.core.v1.User
	0,  // 1: chatto.api.v1.GetViewerResponse.viewer:type_name -> chatto.api.v1.Viewer
	13, // 2: chatto.api.v1.ListMyRoomsRequest.kind:type_name -> chatto.core.v1.RoomKind
	14, // 3: chatto.api.v1.ListMyRoomsResponse.rooms:type_name -> chatto.core.v1.Room
	15, // 4: chatto.api.v1.TimelineEvent.event:type_name -> chatto.core.v1.Event
	6,  // 5: chatto.api.v1.GetRoomTimelineResponse.events:type_name -> chatto.api.v1.TimelineEvent
	15, // 6: chatto.api.v1.PostMessageResponse.event:type_name -> chatto.core.v1.Event
	1,  // 7: chatto.api.v1.ChattoApiService.GetViewer:input_type -> chatto.api.v1.GetViewerRequest
	3,  // 8: chatto.api.v1.ChattoApiService.ListMyRooms:input_type -> chatto.api.v1.ListMyRoomsRequest
	5,  // 9: chatto.api.v1.ChattoApiService.GetRoomTimeline:input_type -> chatto.api.v1.GetRoomTimelineRequest
	8,  // 10: chatto.api.v1.ChattoApiService.PostMessage:input_type -> chatto.api.v1.PostMessageRequest
	10, // 11: chatto.api.v1.ChattoApiService.SendTypingIndicator:input_type -> chatto.api.v1.SendTypingIndicatorRequest
	2,  // 12: chatto.api.v1.ChattoApiService.GetViewer:output_type -> chatto.api.v1.GetViewerResponse
	4,  // 13: chatto.api.v1.ChattoApiService.ListMyRooms:output_type -> chatto.api.v1.ListMyRoomsResponse
	7,  // 14: chatto.api.v1.ChattoApiService.GetRoomTimeline:output_type -> chatto.api.v1.GetRoomTimelineResponse
	9,  // 15: chatto.api.v1.ChattoApiService.PostMessage:output_type -> chatto.api.v1.PostMessageResponse
	11, // 16: chatto.api.v1.ChattoApiService.SendTypingIndicator:output_type -> chatto.api.v1.SendTypingIndicatorResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_chatto_api_v1_chat_proto_init() }
func file_chatto_api_v1_chat_proto_init() {
	if File_chatto_api_v1_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_api_v1_chat_proto_rawDesc), len(file_chatto_api_v1_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatto_api_v1_chat_proto_goTypes,
		DependencyIndexes: file_chatto_api_v1_chat_proto_depIdxs,
		MessageInfos:      file_chatto_api_v1_chat_proto_msgTypes,
	}.Build()
	File_chatto_api_v1_chat_proto = out.File
	file_chatto_api_v1_chat_proto_goTypes = nil
	file_chatto_api_v1_chat_proto_depIdxs = nil
}
