// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/api/v1/server_state.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Server profile fields visible to authenticated members.
type ServerMemberProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Public server profile and branding.
	PublicProfile *ServerPublicProfile `protobuf:"bytes,1,opt,name=public_profile,json=publicProfile,proto3" json:"public_profile,omitempty"`
	// Optional message of the day shown to authenticated members.
	Motd          *string `protobuf:"bytes,2,opt,name=motd,proto3,oneof" json:"motd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMemberProfile) Reset() {
	*x = ServerMemberProfile{}
	mi := &file_chatto_api_v1_server_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMemberProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMemberProfile) ProtoMessage() {}

func (x *ServerMemberProfile) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_server_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMemberProfile.ProtoReflect.Descriptor instead.
func (*ServerMemberProfile) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_server_state_proto_rawDescGZIP(), []int{0}
}

func (x *ServerMemberProfile) GetPublicProfile() *ServerPublicProfile {
	if x != nil {
		return x.PublicProfile
	}
	return nil
}

func (x *ServerMemberProfile) GetMotd() string {
	if x != nil && x.Motd != nil {
		return *x.Motd
	}
	return ""
}

// Effective server/channel permission decisions for the authenticated user.
type ServerViewerPermissions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One row per permission known to the server.
	Permissions   []*PermissionGrant `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerViewerPermissions) Reset() {
	*x = ServerViewerPermissions{}
	mi := &file_chatto_api_v1_server_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerViewerPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerViewerPermissions) ProtoMessage() {}

func (x *ServerViewerPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_server_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerViewerPermissions.ProtoReflect.Descriptor instead.
func (*ServerViewerPermissions) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_server_state_proto_rawDescGZIP(), []int{1}
}

func (x *ServerViewerPermissions) GetPermissions() []*PermissionGrant {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// Non-permission server state for the authenticated user.
type ServerViewerState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether any joined channel room has unread messages.
	HasUnreadRooms bool `protobuf:"varint,1,opt,name=has_unread_rooms,json=hasUnreadRooms,proto3" json:"has_unread_rooms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServerViewerState) Reset() {
	*x = ServerViewerState{}
	mi := &file_chatto_api_v1_server_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerViewerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerViewerState) ProtoMessage() {}

func (x *ServerViewerState) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_server_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerViewerState.ProtoReflect.Descriptor instead.
func (*ServerViewerState) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_server_state_proto_rawDescGZIP(), []int{2}
}

func (x *ServerViewerState) GetHasUnreadRooms() bool {
	if x != nil {
		return x.HasUnreadRooms
	}
	return false
}

// Request for authenticated server state.
type GetServerStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerStateRequest) Reset() {
	*x = GetServerStateRequest{}
	mi := &file_chatto_api_v1_server_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerStateRequest) ProtoMessage() {}

func (x *GetServerStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_server_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerStateRequest.ProtoReflect.Descriptor instead.
func (*GetServerStateRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_server_state_proto_rawDescGZIP(), []int{3}
}

// Authenticated server runtime settings used by clients.
type ServerRuntimeConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether Web Push notifications are fully configured.
	PushNotificationsEnabled bool `protobuf:"varint,1,opt,name=push_notifications_enabled,json=pushNotificationsEnabled,proto3" json:"push_notifications_enabled,omitempty"`
	// Optional VAPID public key for Web Push registration.
	VapidPublicKey *string `protobuf:"bytes,2,opt,name=vapid_public_key,json=vapidPublicKey,proto3,oneof" json:"vapid_public_key,omitempty"`
	// Optional LiveKit URL for voice calls.
	LivekitUrl *string `protobuf:"bytes,3,opt,name=livekit_url,json=livekitUrl,proto3,oneof" json:"livekit_url,omitempty"`
	// Whether direct email/password registration is enabled.
	DirectRegistrationEnabled bool `protobuf:"varint,4,opt,name=direct_registration_enabled,json=directRegistrationEnabled,proto3" json:"direct_registration_enabled,omitempty"`
	// Whether video processing is enabled.
	VideoProcessingEnabled bool `protobuf:"varint,5,opt,name=video_processing_enabled,json=videoProcessingEnabled,proto3" json:"video_processing_enabled,omitempty"`
	// Maximum general upload size in bytes.
	MaxUploadSize int64 `protobuf:"varint,6,opt,name=max_upload_size,json=maxUploadSize,proto3" json:"max_upload_size,omitempty"`
	// Maximum video upload size in bytes.
	MaxVideoUploadSize int64 `protobuf:"varint,7,opt,name=max_video_upload_size,json=maxVideoUploadSize,proto3" json:"max_video_upload_size,omitempty"`
	// Message edit window in seconds.
	MessageEditWindowSeconds int32 `protobuf:"varint,8,opt,name=message_edit_window_seconds,json=messageEditWindowSeconds,proto3" json:"message_edit_window_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ServerRuntimeConfig) Reset() {
	*x = ServerRuntimeConfig{}
	mi := &file_chatto_api_v1_server_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerRuntimeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRuntimeConfig) ProtoMessage() {}

func (x *ServerRuntimeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_server_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRuntimeConfig.ProtoReflect.Descriptor instead.
func (*ServerRuntimeConfig) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_server_state_proto_rawDescGZIP(), []int{4}
}

func (x *ServerRuntimeConfig) GetPushNotificationsEnabled() bool {
	if x != nil {
		return x.PushNotificationsEnabled
	}
	return false
}

func (x *ServerRuntimeConfig) GetVapidPublicKey() string {
	if x != nil && x.VapidPublicKey != nil {
		return *x.VapidPublicKey
	}
	return ""
}

func (x *ServerRuntimeConfig) GetLivekitUrl() string {
	if x != nil && x.LivekitUrl != nil {
		return *x.LivekitUrl
	}
	return ""
}

func (x *ServerRuntimeConfig) GetDirectRegistrationEnabled() bool {
	if x != nil {
		return x.DirectRegistrationEnabled
	}
	return false
}

func (x *ServerRuntimeConfig) GetVideoProcessingEnabled() bool {
	if x != nil {
		return x.VideoProcessingEnabled
	}
	return false
}

func (x *ServerRuntimeConfig) GetMaxUploadSize() int64 {
	if x != nil {
		return x.MaxUploadSize
	}
	return 0
}

func (x *ServerRuntimeConfig) GetMaxVideoUploadSize() int64 {
	if x != nil {
		return x.MaxVideoUploadSize
	}
	return 0
}

func (x *ServerRuntimeConfig) GetMessageEditWindowSeconds() int32 {
	if x != nil {
		return x.MessageEditWindowSeconds
	}
	return 0
}

// Authenticated server state used by the web client and public API clients.
type GetServerStateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Authenticated server profile and branding.
	Profile *ServerMemberProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	// Authenticated runtime settings used by clients.
	Runtime *ServerRuntimeConfig `protobuf:"bytes,2,opt,name=runtime,proto3" json:"runtime,omitempty"`
	// Effective server/channel permission decisions for the authenticated user.
	ViewerPermissions *ServerViewerPermissions `protobuf:"bytes,3,opt,name=viewer_permissions,json=viewerPermissions,proto3" json:"viewer_permissions,omitempty"`
	// Non-permission server state for the authenticated user.
	ViewerState   *ServerViewerState `protobuf:"bytes,4,opt,name=viewer_state,json=viewerState,proto3" json:"viewer_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerStateResponse) Reset() {
	*x = GetServerStateResponse{}
	mi := &file_chatto_api_v1_server_state_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerStateResponse) ProtoMessage() {}

func (x *GetServerStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_server_state_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerStateResponse.ProtoReflect.Descriptor instead.
func (*GetServerStateResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_server_state_proto_rawDescGZIP(), []int{5}
}

func (x *GetServerStateResponse) GetProfile() *ServerMemberProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *GetServerStateResponse) GetRuntime() *ServerRuntimeConfig {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *GetServerStateResponse) GetViewerPermissions() *ServerViewerPermissions {
	if x != nil {
		return x.ViewerPermissions
	}
	return nil
}

func (x *GetServerStateResponse) GetViewerState() *ServerViewerState {
	if x != nil {
		return x.ViewerState
	}
	return nil
}

var File_chatto_api_v1_server_state_proto protoreflect.FileDescriptor

const file_chatto_api_v1_server_state_proto_rawDesc = "" +
	"\n" +
	" chatto/api/v1/server_state.proto\x12\rchatto.api.v1\x1a\x1fchatto/api/v1/permissions.proto\x1a\x1achatto/api/v1/server.proto\"\x82\x01\n" +
	"\x13ServerMemberProfile\x12I\n" +
	"\x0epublic_profile\x18\x01 \x01(\v2\".chatto.api.v1.ServerPublicProfileR\rpublicProfile\x12\x17\n" +
	"\x04motd\x18\x02 \x01(\tH\x00R\x04motd\x88\x01\x01B\a\n" +
	"\x05_motd\"[\n" +
	"\x17ServerViewerPermissions\x12@\n" +
	"\vpermissions\x18\x01 \x03(\v2\x1e.chatto.api.v1.PermissionGrantR\vpermissions\"=\n" +
	"\x11ServerViewerState\x12(\n" +
	"\x10has_unread_rooms\x18\x01 \x01(\bR\x0ehasUnreadRooms\"\x17\n" +
	"\x15GetServerStateRequest\"\xe1\x03\n" +
	"\x13ServerRuntimeConfig\x12<\n" +
	"\x1apush_notifications_enabled\x18\x01 \x01(\bR\x18pushNotificationsEnabled\x12-\n" +
	"\x10vapid_public_key\x18\x02 \x01(\tH\x00R\x0evapidPublicKey\x88\x01\x01\x12$\n" +
	"\vlivekit_url\x18\x03 \x01(\tH\x01R\n" +
	"livekitUrl\x88\x01\x01\x12>\n" +
	"\x1bdirect_registration_enabled\x18\x04 \x01(\bR\x19directRegistrationEnabled\x128\n" +
	"\x18video_processing_enabled\x18\x05 \x01(\bR\x16videoProcessingEnabled\x12&\n" +
	"\x0fmax_upload_size\x18\x06 \x01(\x03R\rmaxUploadSize\x121\n" +
	"\x15max_video_upload_size\x18\a \x01(\x03R\x12maxVideoUploadSize\x12=\n" +
	"\x1bmessage_edit_window_seconds\x18\b \x01(\x05R\x18messageEditWindowSecondsB\x13\n" +
	"\x11_vapid_public_keyB\x0e\n" +
	"\f_livekit_url\"\xb0\x02\n" +
	"\x16GetServerStateResponse\x12<\n" +
	"\aprofile\x18\x01 \x01(\v2\".chatto.api.v1.ServerMemberProfileR\aprofile\x12<\n" +
	"\aruntime\x18\x02 \x01(\v2\".chatto.api.v1.ServerRuntimeConfigR\aruntime\x12U\n" +
	"\x12viewer_permissions\x18\x03 \x01(\v2&.chatto.api.v1.ServerViewerPermissionsR\x11viewerPermissions\x12C\n" +
	"\fviewer_state\x18\x04 \x01(\v2 .chatto.api.v1.ServerViewerStateR\vviewerState2n\n" +
	"\rServerService\x12]\n" +
	"\x0eGetServerState\x12$.chatto.api.v1.GetServerStateRequest\x1a%.chatto.api.v1.GetServerStateResponseB\xac\x01\n" +
	"\x11com.chatto.api.v1B\x10ServerStateProtoP\x01Z/hmans.de/chatto/internal/pb/chatto/api/v1;apiv1\xa2\x02\x03CAX\xaa\x02\rChatto.Api.V1\xca\x02\rChatto\\Api\\V1\xe2\x02\x19Chatto\\Api\\V1\\GPBMetadata\xea\x02\x0fChatto::Api::V1b\x06proto3"

var (
	file_chatto_api_v1_server_state_proto_rawDescOnce sync.Once
	file_chatto_api_v1_server_state_proto_rawDescData []byte
)

func file_chatto_api_v1_server_state_proto_rawDescGZIP() []byte {
	file_chatto_api_v1_server_state_proto_rawDescOnce.Do(func() {
		file_chatto_api_v1_server_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_api_v1_server_state_proto_rawDesc), len(file_chatto_api_v1_server_state_proto_rawDesc)))
	})
	return file_chatto_api_v1_server_state_proto_rawDescData
}

var file_chatto_api_v1_server_state_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_chatto_api_v1_server_state_proto_goTypes = []any{
	(*ServerMemberProfile)(nil),     // 0: chatto.api.v1.ServerMemberProfile
	(*ServerViewerPermissions)(nil), // 1: chatto.api.v1.ServerViewerPermissions
	(*ServerViewerState)(nil),       // 2: chatto.api.v1.ServerViewerState
	(*GetServerStateRequest)(nil),   // 3: chatto.api.v1.GetServerStateRequest
	(*ServerRuntimeConfig)(nil),     // 4: chatto.api.v1.ServerRuntimeConfig
	(*GetServerStateResponse)(nil),  // 5: chatto.api.v1.GetServerStateResponse
	(*ServerPublicProfile)(nil),     // 6: chatto.api.v1.ServerPublicProfile
	(*PermissionGrant)(nil),         // 7: chatto.api.v1.PermissionGrant
}
var file_chatto_api_v1_server_state_proto_depIdxs = []int32{
	6, // 0: chatto.api.v1.ServerMemberProfile.public_profile:type_name -> chatto.api.v1.ServerPublicProfile
	7, // 1: chatto.api.v1.ServerViewerPermissions.permissions:type_name -> chatto.api.v1.PermissionGrant
	0, // 2: chatto.api.v1.GetServerStateResponse.profile:type_name -> chatto.api.v1.ServerMemberProfile
	4, // 3: chatto.api.v1.GetServerStateResponse.runtime:type_name -> chatto.api.v1.ServerRuntimeConfig
	1, // 4: chatto.api.v1.GetServerStateResponse.viewer_permissions:type_name -> chatto.api.v1.ServerViewerPermissions
	2, // 5: chatto.api.v1.GetServerStateResponse.viewer_state:type_name -> chatto.api.v1.ServerViewerState
	3, // 6: chatto.api.v1.ServerService.GetServerState:input_type -> chatto.api.v1.GetServerStateRequest
	5, // 7: chatto.api.v1.ServerService.GetServerState:output_type -> chatto.api.v1.GetServerStateResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_chatto_api_v1_server_state_proto_init() }
func file_chatto_api_v1_server_state_proto_init() {
	if File_chatto_api_v1_server_state_proto != nil {
		return
	}
	file_chatto_api_v1_permissions_proto_init()
	file_chatto_api_v1_server_proto_init()
	file_chatto_api_v1_server_state_proto_msgTypes[0].OneofWrappers = []any{}
	file_chatto_api_v1_server_state_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_api_v1_server_state_proto_rawDesc), len(file_chatto_api_v1_server_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatto_api_v1_server_state_proto_goTypes,
		DependencyIndexes: file_chatto_api_v1_server_state_proto_depIdxs,
		MessageInfos:      file_chatto_api_v1_server_state_proto_msgTypes,
	}.Build()
	File_chatto_api_v1_server_state_proto = out.File
	file_chatto_api_v1_server_state_proto_goTypes = nil
	file_chatto_api_v1_server_state_proto_depIdxs = nil
}
