// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/atproto/v1/store.proto

package atprotov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ATProtoAuthRequest persists the state of an in-flight OAuth flow between
// the initial PAR submission and the callback. Stored at
// `atproto.auth_request.{state}` in the MEMORY_CACHE KV bucket with a short
// per-key TTL — the consent screen is the only thing keeping these alive.
//
// Field names mirror the indigo `oauth.AuthRequestData` struct one-to-one so
// the adapter conversion is mechanical.
type ATProtoAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	AuthServerUrl string                 `protobuf:"bytes,2,opt,name=auth_server_url,json=authServerUrl,proto3" json:"auth_server_url,omitempty"`
	// May be empty when the flow started from an auth server URL rather than
	// an account identifier.
	AccountDid                   string   `protobuf:"bytes,3,opt,name=account_did,json=accountDid,proto3" json:"account_did,omitempty"`
	Scopes                       []string `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`
	RequestUri                   string   `protobuf:"bytes,5,opt,name=request_uri,json=requestUri,proto3" json:"request_uri,omitempty"`
	AuthServerTokenEndpoint      string   `protobuf:"bytes,6,opt,name=auth_server_token_endpoint,json=authServerTokenEndpoint,proto3" json:"auth_server_token_endpoint,omitempty"`
	AuthServerRevocationEndpoint string   `protobuf:"bytes,7,opt,name=auth_server_revocation_endpoint,json=authServerRevocationEndpoint,proto3" json:"auth_server_revocation_endpoint,omitempty"`
	PkceVerifier                 string   `protobuf:"bytes,8,opt,name=pkce_verifier,json=pkceVerifier,proto3" json:"pkce_verifier,omitempty"`
	DpopAuthServerNonce          string   `protobuf:"bytes,9,opt,name=dpop_auth_server_nonce,json=dpopAuthServerNonce,proto3" json:"dpop_auth_server_nonce,omitempty"`
	// P-256 private key in multibase encoding, generated per-session for DPoP.
	// SECRET: see file-header comment on ATProtoSession.
	DpopPrivateKeyMultibase string `protobuf:"bytes,10,opt,name=dpop_private_key_multibase,json=dpopPrivateKeyMultibase,proto3" json:"dpop_private_key_multibase,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ATProtoAuthRequest) Reset() {
	*x = ATProtoAuthRequest{}
	mi := &file_chatto_atproto_v1_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ATProtoAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ATProtoAuthRequest) ProtoMessage() {}

func (x *ATProtoAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_atproto_v1_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ATProtoAuthRequest.ProtoReflect.Descriptor instead.
func (*ATProtoAuthRequest) Descriptor() ([]byte, []int) {
	return file_chatto_atproto_v1_store_proto_rawDescGZIP(), []int{0}
}

func (x *ATProtoAuthRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ATProtoAuthRequest) GetAuthServerUrl() string {
	if x != nil {
		return x.AuthServerUrl
	}
	return ""
}

func (x *ATProtoAuthRequest) GetAccountDid() string {
	if x != nil {
		return x.AccountDid
	}
	return ""
}

func (x *ATProtoAuthRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *ATProtoAuthRequest) GetRequestUri() string {
	if x != nil {
		return x.RequestUri
	}
	return ""
}

func (x *ATProtoAuthRequest) GetAuthServerTokenEndpoint() string {
	if x != nil {
		return x.AuthServerTokenEndpoint
	}
	return ""
}

func (x *ATProtoAuthRequest) GetAuthServerRevocationEndpoint() string {
	if x != nil {
		return x.AuthServerRevocationEndpoint
	}
	return ""
}

func (x *ATProtoAuthRequest) GetPkceVerifier() string {
	if x != nil {
		return x.PkceVerifier
	}
	return ""
}

func (x *ATProtoAuthRequest) GetDpopAuthServerNonce() string {
	if x != nil {
		return x.DpopAuthServerNonce
	}
	return ""
}

func (x *ATProtoAuthRequest) GetDpopPrivateKeyMultibase() string {
	if x != nil {
		return x.DpopPrivateKeyMultibase
	}
	return ""
}

// ATProtoSession persists an authenticated OAuth session post-callback.
// Stored at `atproto.session.{sha256(did + ":" + session_id)}` in the
// MEMORY_CACHE KV bucket. In the current sign-in flow, the local entry is
// deleted within milliseconds of being written, after the callback has fetched
// the optional account email. Chatto does not retain the tokens and does not
// revoke the PDS-side grant, but public/loopback ATProto clients may still be
// asked for consent on every sign-in by the PDS. Any future feature that retains
// sessions beyond identification should wrap the secret fields via the KMS
// service (ADR-007 territory) rather than relying on plaintext KV.
//
// Field names mirror the indigo `oauth.ClientSessionData` struct one-to-one.
type ATProtoSession struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	AccountDid                   string                 `protobuf:"bytes,1,opt,name=account_did,json=accountDid,proto3" json:"account_did,omitempty"`
	SessionId                    string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	HostUrl                      string                 `protobuf:"bytes,3,opt,name=host_url,json=hostUrl,proto3" json:"host_url,omitempty"`
	AuthServerUrl                string                 `protobuf:"bytes,4,opt,name=auth_server_url,json=authServerUrl,proto3" json:"auth_server_url,omitempty"`
	AuthServerTokenEndpoint      string                 `protobuf:"bytes,5,opt,name=auth_server_token_endpoint,json=authServerTokenEndpoint,proto3" json:"auth_server_token_endpoint,omitempty"`
	AuthServerRevocationEndpoint string                 `protobuf:"bytes,6,opt,name=auth_server_revocation_endpoint,json=authServerRevocationEndpoint,proto3" json:"auth_server_revocation_endpoint,omitempty"`
	// Space-joined scopes, matching the OAuth wire format.
	Scopes string `protobuf:"bytes,7,opt,name=scopes,proto3" json:"scopes,omitempty"`
	// SECRET — access token for the resource server (PDS).
	AccessToken string `protobuf:"bytes,8,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// SECRET — refresh token for the authorization server.
	RefreshToken        string `protobuf:"bytes,9,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	DpopAuthServerNonce string `protobuf:"bytes,10,opt,name=dpop_auth_server_nonce,json=dpopAuthServerNonce,proto3" json:"dpop_auth_server_nonce,omitempty"`
	DpopHostNonce       string `protobuf:"bytes,11,opt,name=dpop_host_nonce,json=dpopHostNonce,proto3" json:"dpop_host_nonce,omitempty"`
	// SECRET — P-256 private key in multibase encoding, used for DPoP signing.
	DpopPrivateKeyMultibase string `protobuf:"bytes,12,opt,name=dpop_private_key_multibase,json=dpopPrivateKeyMultibase,proto3" json:"dpop_private_key_multibase,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ATProtoSession) Reset() {
	*x = ATProtoSession{}
	mi := &file_chatto_atproto_v1_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ATProtoSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ATProtoSession) ProtoMessage() {}

func (x *ATProtoSession) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_atproto_v1_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ATProtoSession.ProtoReflect.Descriptor instead.
func (*ATProtoSession) Descriptor() ([]byte, []int) {
	return file_chatto_atproto_v1_store_proto_rawDescGZIP(), []int{1}
}

func (x *ATProtoSession) GetAccountDid() string {
	if x != nil {
		return x.AccountDid
	}
	return ""
}

func (x *ATProtoSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ATProtoSession) GetHostUrl() string {
	if x != nil {
		return x.HostUrl
	}
	return ""
}

func (x *ATProtoSession) GetAuthServerUrl() string {
	if x != nil {
		return x.AuthServerUrl
	}
	return ""
}

func (x *ATProtoSession) GetAuthServerTokenEndpoint() string {
	if x != nil {
		return x.AuthServerTokenEndpoint
	}
	return ""
}

func (x *ATProtoSession) GetAuthServerRevocationEndpoint() string {
	if x != nil {
		return x.AuthServerRevocationEndpoint
	}
	return ""
}

func (x *ATProtoSession) GetScopes() string {
	if x != nil {
		return x.Scopes
	}
	return ""
}

func (x *ATProtoSession) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ATProtoSession) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *ATProtoSession) GetDpopAuthServerNonce() string {
	if x != nil {
		return x.DpopAuthServerNonce
	}
	return ""
}

func (x *ATProtoSession) GetDpopHostNonce() string {
	if x != nil {
		return x.DpopHostNonce
	}
	return ""
}

func (x *ATProtoSession) GetDpopPrivateKeyMultibase() string {
	if x != nil {
		return x.DpopPrivateKeyMultibase
	}
	return ""
}

var File_chatto_atproto_v1_store_proto protoreflect.FileDescriptor

const file_chatto_atproto_v1_store_proto_rawDesc = "" +
	"\n" +
	"\x1dchatto/atproto/v1/store.proto\x12\x11chatto.atproto.v1\"\xc7\x03\n" +
	"\x12ATProtoAuthRequest\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12&\n" +
	"\x0fauth_server_url\x18\x02 \x01(\tR\rauthServerUrl\x12\x1f\n" +
	"\vaccount_did\x18\x03 \x01(\tR\n" +
	"accountDid\x12\x16\n" +
	"\x06scopes\x18\x04 \x03(\tR\x06scopes\x12\x1f\n" +
	"\vrequest_uri\x18\x05 \x01(\tR\n" +
	"requestUri\x12;\n" +
	"\x1aauth_server_token_endpoint\x18\x06 \x01(\tR\x17authServerTokenEndpoint\x12E\n" +
	"\x1fauth_server_revocation_endpoint\x18\a \x01(\tR\x1cauthServerRevocationEndpoint\x12#\n" +
	"\rpkce_verifier\x18\b \x01(\tR\fpkceVerifier\x123\n" +
	"\x16dpop_auth_server_nonce\x18\t \x01(\tR\x13dpopAuthServerNonce\x12;\n" +
	"\x1adpop_private_key_multibase\x18\n" +
	" \x01(\tR\x17dpopPrivateKeyMultibase\"\x91\x04\n" +
	"\x0eATProtoSession\x12\x1f\n" +
	"\vaccount_did\x18\x01 \x01(\tR\n" +
	"accountDid\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x19\n" +
	"\bhost_url\x18\x03 \x01(\tR\ahostUrl\x12&\n" +
	"\x0fauth_server_url\x18\x04 \x01(\tR\rauthServerUrl\x12;\n" +
	"\x1aauth_server_token_endpoint\x18\x05 \x01(\tR\x17authServerTokenEndpoint\x12E\n" +
	"\x1fauth_server_revocation_endpoint\x18\x06 \x01(\tR\x1cauthServerRevocationEndpoint\x12\x16\n" +
	"\x06scopes\x18\a \x01(\tR\x06scopes\x12!\n" +
	"\faccess_token\x18\b \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\t \x01(\tR\frefreshToken\x123\n" +
	"\x16dpop_auth_server_nonce\x18\n" +
	" \x01(\tR\x13dpopAuthServerNonce\x12&\n" +
	"\x0fdpop_host_nonce\x18\v \x01(\tR\rdpopHostNonce\x12;\n" +
	"\x1adpop_private_key_multibase\x18\f \x01(\tR\x17dpopPrivateKeyMultibaseB\xc2\x01\n" +
	"\x15com.chatto.atproto.v1B\n" +
	"StoreProtoP\x01Z7hmans.de/chatto/internal/pb/chatto/atproto/v1;atprotov1\xa2\x02\x03CAX\xaa\x02\x11Chatto.Atproto.V1\xca\x02\x11Chatto\\Atproto\\V1\xe2\x02\x1dChatto\\Atproto\\V1\\GPBMetadata\xea\x02\x13Chatto::Atproto::V1b\x06proto3"

var (
	file_chatto_atproto_v1_store_proto_rawDescOnce sync.Once
	file_chatto_atproto_v1_store_proto_rawDescData []byte
)

func file_chatto_atproto_v1_store_proto_rawDescGZIP() []byte {
	file_chatto_atproto_v1_store_proto_rawDescOnce.Do(func() {
		file_chatto_atproto_v1_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_atproto_v1_store_proto_rawDesc), len(file_chatto_atproto_v1_store_proto_rawDesc)))
	})
	return file_chatto_atproto_v1_store_proto_rawDescData
}

var file_chatto_atproto_v1_store_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chatto_atproto_v1_store_proto_goTypes = []any{
	(*ATProtoAuthRequest)(nil), // 0: chatto.atproto.v1.ATProtoAuthRequest
	(*ATProtoSession)(nil),     // 1: chatto.atproto.v1.ATProtoSession
}
var file_chatto_atproto_v1_store_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chatto_atproto_v1_store_proto_init() }
func file_chatto_atproto_v1_store_proto_init() {
	if File_chatto_atproto_v1_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_atproto_v1_store_proto_rawDesc), len(file_chatto_atproto_v1_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatto_atproto_v1_store_proto_goTypes,
		DependencyIndexes: file_chatto_atproto_v1_store_proto_depIdxs,
		MessageInfos:      file_chatto_atproto_v1_store_proto_msgTypes,
	}.Build()
	File_chatto_atproto_v1_store_proto = out.File
	file_chatto_atproto_v1_store_proto_goTypes = nil
	file_chatto_atproto_v1_store_proto_depIdxs = nil
}
