// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/api/v1/account.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeleteAvatarRequest, DeleteAvatarResponse, DeleteMyAccountRequest, DeleteMyAccountResponse, RequestAccountDeletionRequest, RequestAccountDeletionResponse, UpdateProfileRequest, UpdateProfileResponse, UpdateSettingsRequest, UpdateSettingsResponse, UploadAvatarRequest, UploadAvatarResponse } from "./account_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Self-service account, profile, avatar, and display preference commands.
 *
 * @generated from service chatto.api.v1.AccountService
 */
export const AccountService = {
  typeName: "chatto.api.v1.AccountService",
  methods: {
    /**
     * Updates the authenticated user's login and/or display name.
     *
     * @generated from rpc chatto.api.v1.AccountService.UpdateProfile
     */
    updateProfile: {
      name: "UpdateProfile",
      I: UpdateProfileRequest,
      O: UpdateProfileResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Uploads and sets the authenticated user's avatar.
     *
     * @generated from rpc chatto.api.v1.AccountService.UploadAvatar
     */
    uploadAvatar: {
      name: "UploadAvatar",
      I: UploadAvatarRequest,
      O: UploadAvatarResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Deletes the authenticated user's avatar. The call is idempotent.
     *
     * @generated from rpc chatto.api.v1.AccountService.DeleteAvatar
     */
    deleteAvatar: {
      name: "DeleteAvatar",
      I: DeleteAvatarRequest,
      O: DeleteAvatarResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Updates the authenticated user's display preferences.
     *
     * @generated from rpc chatto.api.v1.AccountService.UpdateSettings
     */
    updateSettings: {
      name: "UpdateSettings",
      I: UpdateSettingsRequest,
      O: UpdateSettingsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Issues a short-lived token used to confirm self-deletion.
     *
     * @generated from rpc chatto.api.v1.AccountService.RequestAccountDeletion
     */
    requestAccountDeletion: {
      name: "RequestAccountDeletion",
      I: RequestAccountDeletionRequest,
      O: RequestAccountDeletionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Permanently deletes the authenticated account after token validation.
     *
     * @generated from rpc chatto.api.v1.AccountService.DeleteMyAccount
     */
    deleteMyAccount: {
      name: "DeleteMyAccount",
      I: DeleteMyAccountRequest,
      O: DeleteMyAccountResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

