// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/api/v1/admin_user_management.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AssignRoleRequest, AssignRoleResponse, ClearUsernameCooldownRequest, ClearUsernameCooldownResponse, GetMemberRequest, GetMemberResponse, ListMembersRequest, ListMembersResponse, RevokeRoleRequest, RevokeRoleResponse, UpdateUserRequest, UpdateUserResponse } from "./admin_user_management_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Server-admin user identity and cooldown commands.
 *
 * @generated from service chatto.api.v1.AdminUserManagementService
 */
export const AdminUserManagementService = {
  typeName: "chatto.api.v1.AdminUserManagementService",
  methods: {
    /**
     * Lists server members for the admin members screen.
     *
     * @generated from rpc chatto.api.v1.AdminUserManagementService.ListMembers
     */
    listMembers: {
      name: "ListMembers",
      I: ListMembersRequest,
      O: ListMembersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Gets one server member plus role/permission metadata for admin details.
     * Returns NOT_FOUND when the user does not exist.
     *
     * @generated from rpc chatto.api.v1.AdminUserManagementService.GetMember
     */
    getMember: {
      name: "GetMember",
      I: GetMemberRequest,
      O: GetMemberResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Assigns a server role to a user.
     *
     * @generated from rpc chatto.api.v1.AdminUserManagementService.AssignRole
     */
    assignRole: {
      name: "AssignRole",
      I: AssignRoleRequest,
      O: AssignRoleResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Revokes a server role from a user.
     *
     * @generated from rpc chatto.api.v1.AdminUserManagementService.RevokeRole
     */
    revokeRole: {
      name: "RevokeRole",
      I: RevokeRoleRequest,
      O: RevokeRoleResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Updates a user's login and/or display name as an admin action.
     *
     * @generated from rpc chatto.api.v1.AdminUserManagementService.UpdateUser
     */
    updateUser: {
      name: "UpdateUser",
      I: UpdateUserRequest,
      O: UpdateUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Clears the target user's self-service username-change cooldown.
     *
     * @generated from rpc chatto.api.v1.AdminUserManagementService.ClearUsernameCooldown
     */
    clearUsernameCooldown: {
      name: "ClearUsernameCooldown",
      I: ClearUsernameCooldownRequest,
      O: ClearUsernameCooldownResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

