// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file chatto/api/v1/link_previews.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * Request to fetch server-side link preview metadata for a URL.
 *
 * @generated from message chatto.api.v1.FetchLinkPreviewRequest
 */
export class FetchLinkPreviewRequest extends Message<FetchLinkPreviewRequest> {
  /**
   * URL to preview.
   *
   * @generated from field: string url = 1;
   */
  url = "";

  constructor(data?: PartialMessage<FetchLinkPreviewRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.FetchLinkPreviewRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FetchLinkPreviewRequest {
    return new FetchLinkPreviewRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FetchLinkPreviewRequest {
    return new FetchLinkPreviewRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FetchLinkPreviewRequest {
    return new FetchLinkPreviewRequest().fromJsonString(jsonString, options);
  }

  static equals(a: FetchLinkPreviewRequest | PlainMessage<FetchLinkPreviewRequest> | undefined, b: FetchLinkPreviewRequest | PlainMessage<FetchLinkPreviewRequest> | undefined): boolean {
    return proto3.util.equals(FetchLinkPreviewRequest, a, b);
  }
}

/**
 * Link preview metadata returned to clients before posting a message.
 *
 * @generated from message chatto.api.v1.FetchedLinkPreview
 */
export class FetchedLinkPreview extends Message<FetchedLinkPreview> {
  /**
   * Previewed URL.
   *
   * @generated from field: string url = 1;
   */
  url = "";

  /**
   * Page or embed title.
   *
   * @generated from field: string title = 2;
   */
  title = "";

  /**
   * Page or embed description.
   *
   * @generated from field: string description = 3;
   */
  description = "";

  /**
   * Preview image URL, when available.
   *
   * @generated from field: string image_url = 4;
   */
  imageUrl = "";

  /**
   * Existing server asset ID for the preview image, when available.
   *
   * @generated from field: string image_asset_id = 5;
   */
  imageAssetId = "";

  /**
   * Site name, when known.
   *
   * @generated from field: string site_name = 6;
   */
  siteName = "";

  /**
   * Embed provider or type, when recognized.
   *
   * @generated from field: string embed_type = 7;
   */
  embedType = "";

  /**
   * Provider-specific embed ID, when recognized.
   *
   * @generated from field: string embed_id = 8;
   */
  embedId = "";

  constructor(data?: PartialMessage<FetchedLinkPreview>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.FetchedLinkPreview";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "image_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "image_asset_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "site_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "embed_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "embed_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FetchedLinkPreview {
    return new FetchedLinkPreview().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FetchedLinkPreview {
    return new FetchedLinkPreview().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FetchedLinkPreview {
    return new FetchedLinkPreview().fromJsonString(jsonString, options);
  }

  static equals(a: FetchedLinkPreview | PlainMessage<FetchedLinkPreview> | undefined, b: FetchedLinkPreview | PlainMessage<FetchedLinkPreview> | undefined): boolean {
    return proto3.util.equals(FetchedLinkPreview, a, b);
  }
}

/**
 * Result of fetching link preview metadata.
 *
 * @generated from message chatto.api.v1.FetchLinkPreviewResponse
 */
export class FetchLinkPreviewResponse extends Message<FetchLinkPreviewResponse> {
  /**
   * Preview metadata, or absent when the URL cannot be previewed.
   *
   * @generated from field: chatto.api.v1.FetchedLinkPreview preview = 1;
   */
  preview?: FetchedLinkPreview;

  constructor(data?: PartialMessage<FetchLinkPreviewResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.FetchLinkPreviewResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "preview", kind: "message", T: FetchedLinkPreview },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FetchLinkPreviewResponse {
    return new FetchLinkPreviewResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FetchLinkPreviewResponse {
    return new FetchLinkPreviewResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FetchLinkPreviewResponse {
    return new FetchLinkPreviewResponse().fromJsonString(jsonString, options);
  }

  static equals(a: FetchLinkPreviewResponse | PlainMessage<FetchLinkPreviewResponse> | undefined, b: FetchLinkPreviewResponse | PlainMessage<FetchLinkPreviewResponse> | undefined): boolean {
    return proto3.util.equals(FetchLinkPreviewResponse, a, b);
  }
}

