// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/api/v1/roles.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateRoleRequest, CreateRoleResponse, DeleteRoleRequest, DeleteRoleResponse, GetRoleRequest, GetRoleResponse, ListRolesRequest, ListRolesResponse, ReorderRolesRequest, ReorderRolesResponse, UpdateRoleRequest, UpdateRoleResponse } from "./roles_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Provides authenticated role catalog reads and admin role CRUD.
 *
 * @generated from service chatto.api.v1.RoleService
 */
export const RoleService = {
  typeName: "chatto.api.v1.RoleService",
  methods: {
    /**
     * Lists the server role catalog. Requires an authenticated user.
     *
     * @generated from rpc chatto.api.v1.RoleService.ListRoles
     */
    listRoles: {
      name: "ListRoles",
      I: ListRolesRequest,
      O: ListRolesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Gets one server role plus admin detail metadata. Returns NOT_FOUND when the
     * role does not exist.
     *
     * @generated from rpc chatto.api.v1.RoleService.GetRole
     */
    getRole: {
      name: "GetRole",
      I: GetRoleRequest,
      O: GetRoleResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Creates a custom server role. Requires role.manage.
     *
     * @generated from rpc chatto.api.v1.RoleService.CreateRole
     */
    createRole: {
      name: "CreateRole",
      I: CreateRoleRequest,
      O: CreateRoleResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Updates role metadata. Requires role.manage.
     *
     * @generated from rpc chatto.api.v1.RoleService.UpdateRole
     */
    updateRole: {
      name: "UpdateRole",
      I: UpdateRoleRequest,
      O: UpdateRoleResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Deletes a custom server role. Requires role.manage.
     *
     * @generated from rpc chatto.api.v1.RoleService.DeleteRole
     */
    deleteRole: {
      name: "DeleteRole",
      I: DeleteRoleRequest,
      O: DeleteRoleResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Replaces the custom role order. Requires role.manage.
     *
     * @generated from rpc chatto.api.v1.RoleService.ReorderRoles
     */
    reorderRoles: {
      name: "ReorderRoles",
      I: ReorderRolesRequest,
      O: ReorderRolesResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

