// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/api/v1/voice_calls.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetCallTokenRequest, GetCallTokenResponse, JoinCallRequest, JoinCallResponse, LeaveCallRequest, LeaveCallResponse, ListActiveCallRoomsRequest, ListActiveCallRoomsResponse, ListCallParticipantsRequest, ListCallParticipantsResponse } from "./voice_calls_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Voice-call request/response APIs backed by Chatto call-state projections.
 *
 * @generated from service chatto.api.v1.VoiceCallService
 */
export const VoiceCallService = {
  typeName: "chatto.api.v1.VoiceCallService",
  methods: {
    /**
     * Lists channel room IDs that currently have active calls.
     *
     * Returns an empty list when LiveKit is not configured.
     *
     * @generated from rpc chatto.api.v1.VoiceCallService.ListActiveCallRooms
     */
    listActiveCallRooms: {
      name: "ListActiveCallRooms",
      I: ListActiveCallRoomsRequest,
      O: ListActiveCallRoomsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Lists participants currently observed in a room's active call.
     *
     * The caller must be a member of the room.
     *
     * @generated from rpc chatto.api.v1.VoiceCallService.ListCallParticipants
     */
    listCallParticipants: {
      name: "ListCallParticipants",
      I: ListCallParticipantsRequest,
      O: ListCallParticipantsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Records the caller's intent to join a room call.
     *
     * Returns joined=false when LiveKit is not configured.
     *
     * @generated from rpc chatto.api.v1.VoiceCallService.JoinCall
     */
    joinCall: {
      name: "JoinCall",
      I: JoinCallRequest,
      O: JoinCallResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Issues a LiveKit token for joining the room's active call.
     *
     * The caller must be a member of the room and a call must already be active.
     *
     * @generated from rpc chatto.api.v1.VoiceCallService.GetCallToken
     */
    getCallToken: {
      name: "GetCallToken",
      I: GetCallTokenRequest,
      O: GetCallTokenResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Records the caller's intent to leave a room call.
     *
     * Returns left=false when LiveKit is not configured.
     *
     * @generated from rpc chatto.api.v1.VoiceCallService.LeaveCall
     */
    leaveCall: {
      name: "LeaveCall",
      I: LeaveCallRequest,
      O: LeaveCallResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

